Repository actor-framework/actor-framework, pull requests merged in 2018-07, with the labels that each got.

#720 Fix LDFLAG handling with whitespaces
  CMakeLists.txt
Labels: needs review

#717 Fix "unused" warnings when using OpenSSL 1.1
  libcaf_openssl/src/manager.cpp
  libcaf_openssl/src/session.cpp
Labels: needs review

#725 Use Jenkins Cmake plugin on Windows
  Jenkinsfile
Labels: improvement, needs review

#730 Improve deterministic I/O DSL and port remote group test to DSL
  libcaf_core/test/config_option.cpp
  libcaf_io/src/middleman.cpp
  libcaf_io/test/remote_group.cpp
  libcaf_test/caf/test/dsl.hpp
  libcaf_test/caf/test/io_dsl.hpp
  scripts/indent_trace_log.py
Labels: needs review, refactoring

#731 Call remove_from_loop in manager::detach
  libcaf_io/caf/io/datagram_servant.hpp
  libcaf_io/caf/io/doorman.hpp
  libcaf_io/caf/io/network/default_multiplexer.hpp
  libcaf_io/caf/io/network/manager.hpp
  libcaf_io/caf/io/scribe.hpp
  libcaf_io/src/datagram_servant.cpp
  libcaf_io/src/default_multiplexer.cpp
  libcaf_io/src/doorman.cpp
  libcaf_io/src/manager.cpp
  libcaf_io/src/scribe.cpp
  libcaf_io/src/stream.cpp
  libcaf_io/test/default_multiplexer.cpp
Labels: bugfix, needs review

#734 Add URI to config_value
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/detail/parser/read_ini.hpp
  libcaf_core/src/config_value.cpp
  libcaf_core/test/read_ini.cpp
Labels: needs review, new feature
