Repository actor-framework/actor-framework, pull requests merged in 2018-09, with the labels that each got.

#751 Fix segfault on changing to empty behavior
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/test/behavior.cpp
Labels: needs review

#758 Add timespan to builtin types
  libcaf_core/caf/type_nr.hpp
  libcaf_core/src/uniform_type_info_map.cpp
Labels: bugfix, needs review

#759 Fix potential deadlock in the thread-safe clock
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/detail/thread_safe_actor_clock.hpp
  libcaf_core/caf/variant.hpp
  libcaf_core/src/actor_system.cpp
  libcaf_core/src/thread_safe_actor_clock.cpp
Labels: bugfix, needs review

#760 Implement graceful shutdown of streams after quit
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/detail/stream_source_impl.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/stream_manager.hpp
  libcaf_core/caf/typed_event_based_actor.hpp
  libcaf_core/caf/upstream_msg.hpp
  libcaf_core/src/event_based_actor.cpp
  libcaf_core/src/logger.cpp
  libcaf_core/src/monitorable_actor.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/src/stream_manager.cpp
  libcaf_core/src/stringification_inspector.cpp
  libcaf_core/test/logger.cpp
  libcaf_core/test/native_streaming_classes.cpp
  libcaf_core/test/pipeline_streaming.cpp
  libcaf_io/caf/io/broker_servant.hpp
  libcaf_io/caf/io/typed_broker.hpp
  libcaf_io/src/broker.cpp
  libcaf_io/src/middleman.cpp
Labels: needs review

#764 Implement delayed_send for groups
  libcaf_core/caf/group.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/test/delayed_send.cpp
Labels: improvement, needs review
