Repository actor-framework/actor-framework, pull requests merged in 2018-08, with the labels that each got.

#740 Allow policies to signal internal buffering
  libcaf_io/caf/io/network/stream.hpp
  libcaf_io/caf/policy/tcp.hpp
  libcaf_io/caf/policy/udp.hpp
  libcaf_openssl/caf/openssl/session.hpp
  libcaf_openssl/src/middleman_actor.cpp
  libcaf_openssl/src/session.cpp
  libcaf_openssl/test/remote_actor.cpp
Labels: bugfix, needs review

#744 Fix the "quiet" log level
  CMakeLists.txt
  libcaf_core/caf/make_actor.hpp
  libcaf_core/src/actor_registry.cpp
  libcaf_core/src/logger.cpp
  libcaf_core/test/logger.cpp
Labels: needs review

#745 Make container streambuffer more flexible
  libcaf_core/caf/streambuf.hpp
  libcaf_core/test/streambuf.cpp
Labels: improvement, needs review

#748 Fix pedantic compiler warnings
  libcaf_core/src/make_config_option.cpp
  libcaf_core/src/raise_error.cpp
  libcaf_io/src/default_multiplexer.cpp
  libcaf_io/src/instance.cpp
Labels: needs review
