Repository actor-framework/actor-framework, pull requests merged in 2018-11, with the labels that each got.

#789 Fix missing return
  libcaf_core/caf/local_actor.hpp
Labels: bugfix, needs review

#791 Add copy-on-write tuple implementation
  libcaf_core/caf/cow_tuple.hpp
  libcaf_core/test/cow_tuple.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: needs review

#793 Add missing <string> include to use std::string
  libcaf_core/caf/detail/is_primitive_config_value.hpp
Labels: needs review

#795 Fix invalid class names in CAF log output
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/pretty_type_name.hpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/string_algorithms.hpp
  libcaf_core/src/logger.cpp
  libcaf_core/src/replies_to.cpp
  libcaf_core/src/string_algorithms.cpp
  libcaf_core/test/logger.cpp
Labels: bugfix, needs review

#799 Fix comments of 2 UDP functions, where port still referred to TCP
  libcaf_io/caf/io/middleman.hpp
Labels: documentation, needs review

#798 Clean up string algorithms header and fix caf::split
  libcaf_core/caf/string_algorithms.hpp
  libcaf_core/src/string_algorithms.cpp
  libcaf_core/test/string_algorithms.cpp
Labels: bugfix, needs review, refactoring
