Repository actor-framework/actor-framework, pull requests merged in 2018-05, with the labels that each got.

#691 Fix update message in config server
  libcaf_core/src/actor_system.cpp
Labels: bugfix, needs review

#651 Configure Jenkins via a related file in the repository
  Jenkinsfile
Labels: needs review

#697 Add operator< for variant
  libcaf_core/caf/variant.hpp
  libcaf_core/test/variant.cpp
Labels: improvement, needs review
