Repository actor-framework/actor-framework, pull requests merged in 2018-10, with the labels that each got.

#765 Demote internal messages from INFO to DEBUG
  libcaf_core/src/actor_registry.cpp
  libcaf_io/caf/io/basp/instance.hpp
  libcaf_io/src/basp_broker.cpp
  libcaf_io/src/default_multiplexer.cpp
Labels: needs review

#768 Fix dictionary emplace with char array
  libcaf_core/caf/dictionary.hpp
  libcaf_core/test/dictionary.cpp
Labels: bug, needs review

#778 Add free function to set values in config_value dictionaries
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/dictionary.hpp
  libcaf_core/src/config_value.cpp
  libcaf_core/test/config_value.cpp
Labels: needs review, new feature

#779 Use insert for faster appending in xsputn
  libcaf_core/caf/streambuf.hpp
Labels: needs review

#777 Add non-overriding receive timouts to actor clock
  libcaf_core/caf/actor_clock.hpp
  libcaf_core/caf/detail/simple_actor_clock.hpp
  libcaf_core/src/simple_actor_clock.cpp
  libcaf_core/test/actor_clock.cpp
Labels: needs review

#783 Fix exit reason propagation in monitorable_actor
  libcaf_core/src/monitorable_actor.cpp
  libcaf_io/src/basp_broker.cpp
Labels: needs review

#782 Fix verbosity config option default
  libcaf_core/caf/defaults.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/defaults.cpp
Labels: needs review

#784 Add missing <string> include to use std::string.
  libcaf_io/caf/io/hook.hpp
Labels: needs review

#785 Add explicit close-on-exec check for sockets
  libcaf_io/src/default_multiplexer.cpp
Labels: needs review

#787 Fix stringification inspector concept modeling
  libcaf_core/caf/detail/stringification_inspector.hpp
Labels: needs review
