Repository actor-framework/actor-framework, pull requests merged in 2019-10, with the labels that each got.

#924 Replace Sleep(0) with yield() call on Windows
  libcaf_core/caf/policy/work_stealing.hpp
Labels: performance

#923 Add/improve to_string and ostream overloads
  libcaf_core/caf/atom.hpp
  libcaf_core/caf/dictionary.hpp
  libcaf_core/caf/node_id.hpp
  libcaf_core/src/actor_control_block.cpp
  libcaf_core/src/atom.cpp
Labels: new feature, refactoring

#926 Implement generic unboxing of maps and lists
  libcaf_core/caf/config_value.hpp
  libcaf_core/src/config_value.cpp
  libcaf_core/test/config_value.cpp
Labels: new feature

#927 Auto-generate to_string implementations for enums
  CMakeLists.txt
  cmake/caf-generate-enum-strings.cpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/enum_to_string.hpp
  libcaf_core/caf/exit_reason.hpp
  libcaf_core/caf/intrusive/inbox_result.hpp
  libcaf_core/caf/intrusive/task_result.hpp
  libcaf_core/caf/message_priority.hpp
  libcaf_core/caf/pec.hpp
  libcaf_core/src/abstract_actor.cpp
  libcaf_core/src/duration.cpp
  libcaf_core/src/exit_reason.cpp
  libcaf_core/src/pec.cpp
  libcaf_core/src/sec.cpp
  libcaf_core/src/stream_priority.cpp
  libcaf_core/test/serialization.cpp
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/io/network/operation.hpp
  libcaf_io/src/io/basp/message_type.cpp
Labels: build harness, refactoring

#930 Use fold expression in the data_processor if available
  libcaf_core/caf/data_processor.hpp
  libcaf_core/caf/meta/load_callback.hpp
  libcaf_core/caf/meta/save_callback.hpp
  libcaf_core/test/optional.cpp
  libcaf_core/test/typed_spawn.cpp
  libcaf_io/test/io/basp_broker.cpp
Labels: performance

#931 Fix several issues with config values
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/config_value_field.hpp
  libcaf_core/caf/config_value_object_access.hpp
  libcaf_core/caf/detail/config_value_field_base.hpp
  libcaf_core/caf/detail/config_value_field_impl.hpp
  libcaf_core/caf/detail/parse.hpp
  libcaf_core/test/actor_system_config.cpp
  libcaf_core/test/make_config_value_field.cpp
Labels: bugfix, refactoring

#934 Fix error handling in remote_group
  libcaf_io/src/io/middleman.cpp
Labels: bugfix

#936 Fix silent dropping of errors in request().then()
  libcaf_core/caf/response_handle.hpp
  libcaf_core/caf/scheduled_actor.hpp
Labels: bugfix

#938 Add config_value adaptors for complex user types
  libcaf_core/caf/all.hpp
  libcaf_core/caf/config_value_adaptor.hpp
  libcaf_core/caf/config_value_adaptor_access.hpp
  libcaf_core/caf/config_value_adaptor_field.hpp
  libcaf_core/caf/detail/config_value_adaptor_field_impl.hpp
  libcaf_core/test/config_value_adaptor.cpp
Labels: new feature

#943 Fix compilation of the python binding and apply clang format
  libcaf_python/src/main.cpp
Labels: bugfix

#952 Fix excessive buffering in stream stages
  libcaf_core/caf/inbound_path.hpp
  libcaf_core/src/inbound_path.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/src/stream_manager.cpp
  libcaf_core/test/native_streaming_classes.cpp
Labels: bugfix

#953 Fix verbosity level with disabled console output
  libcaf_core/src/logger.cpp
Labels: bug
