Repository actor-framework/actor-framework, pull requests merged in 2019-11, with the labels that each got.

#954 Avoid repeated calls to stream finalizers
  libcaf_core/caf/stream_manager.hpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/src/stream_manager.cpp
  libcaf_core/test/pipeline_streaming.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: bugfix

#957 Replace messy request_response unit test
  libcaf_core/caf/response_handle.hpp
  libcaf_core/test/mixin/requester.cpp
  libcaf_core/test/request_response.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: refactoring

#958 Provide uniform access to actor properties
  libcaf_core/caf/actor.hpp
  libcaf_core/caf/actor_marker.hpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_traits.hpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/detail/implicit_conversions.hpp
  libcaf_core/caf/detail/spawn_fwd.hpp
  libcaf_core/caf/event_based_actor.hpp
  libcaf_core/caf/mixin/behavior_changer.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/scoped_actor.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_io/caf/io/typed_broker.hpp
Labels: refactoring

#963 Raise error when opening user-defined config fails
  libcaf_core/src/actor_system_config.cpp
Labels: bugfix

#961 Make messages visible to the actor profiler
  libcaf_core/caf/actor_profiler.hpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/detail/profiled_send.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/mixin/requester.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/response_promise.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/caf/typed_actor_view_base.hpp
  libcaf_core/src/response_promise.cpp
  libcaf_core/test/actor_profiler.cpp
Labels: new feature

#965 Remove localhost connections from I/O unit tests
  libcaf_io/test/io/basp/message_queue.cpp
  libcaf_io/test/io/broker.cpp
  libcaf_io/test/io/network/default_multiplexer.cpp
  libcaf_io/test/io/remote_actor.cpp
  libcaf_io/test/io/remote_spawn.cpp
  libcaf_io/test/io/triggering.cpp
  libcaf_io/test/io/typed_broker.cpp
  libcaf_io/test/io/typed_remote_actor.cpp
  libcaf_io/test/io/unpublish.cpp
  libcaf_test/caf/test/io_dsl.hpp
Labels: refactoring

#967 forward arguments as *-value'ness is unknown
  libcaf_core/caf/callback.hpp
Labels: bugfix

#955 OpenBSD support
  CMakeLists.txt
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/config.hpp
  libcaf_io/CMakeLists.txt
  libcaf_io/src/io/network/interfaces.cpp
  libcaf_io/src/io/network/native_socket.cpp
  libcaf_opencl/CMakeLists.txt
  libcaf_openssl/CMakeLists.txt
Labels: improvement

#968 Enable C++17
  CMakeLists.txt
  Jenkinsfile
  cmake/check-compiler-features.cpp
  cmake/get_compiler_version.cpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/src/group_manager.cpp
Labels: build harness

#964 Implement new fan_out_request function
  doc/tex/MessagePassing.tex
  examples/CMakeLists.txt
  examples/message_passing/fan_out_request.cpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/mixin/requester.hpp
  libcaf_core/caf/policy/fan_in_responses.hpp
  libcaf_core/caf/policy/single_response.hpp
  libcaf_core/caf/response_handle.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/test/mixin/requester.cpp
  libcaf_core/test/policy/fan_in_responses.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: new feature

#969 Revert breaking change
  libcaf_core/caf/actor_traits.hpp
Labels: bugfix

#970 Generate unique node ID for each actor system
  libcaf_core/src/node_id.cpp
Labels: bugfix

#979 Fix remote address lookup for datagram handles
  libcaf_io/caf/io/network/acceptor_manager.hpp
  libcaf_io/caf/io/network/datagram_handler.hpp
  libcaf_io/caf/io/network/datagram_manager.hpp
  libcaf_io/caf/io/network/datagram_servant_impl.hpp
  libcaf_io/caf/io/network/manager.hpp
  libcaf_io/caf/io/network/stream_manager.hpp
  libcaf_io/src/io/abstract_broker.cpp
  libcaf_io/src/io/network/datagram_handler.cpp
  libcaf_io/src/io/network/datagram_servant_impl.cpp
  libcaf_io/src/io/network/test_multiplexer.cpp
Labels: bugfix

#977 Fix pointed out typos
  libcaf_core/caf/actor_storage.hpp
  libcaf_core/caf/intrusive/lifo_inbox.hpp
  libcaf_core/caf/stream_manager.hpp
  libcaf_core/caf/stream_sink_driver.hpp
  libcaf_core/caf/stream_stage_driver.hpp
  libcaf_io/caf/io/abstract_broker.hpp
  scripts/make_release.bash
Labels: bugfix, improvement

#981 Add customization point for injecting tracing data
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/mailbox_element.hpp
  libcaf_core/caf/sec.hpp
  libcaf_core/caf/tracing_data.hpp
  libcaf_core/caf/tracing_data_factory.hpp
  libcaf_core/src/actor_system.cpp
  libcaf_core/src/tracing_data.cpp
  libcaf_core/src/tracing_data_factory.cpp
  libcaf_core/test/tracing_data.cpp
Labels: new feature

#982 Fix undefined behavior, build with UBSan in Jenkins
  CMakeLists.txt
  Jenkinsfile
  configure
  libcaf_core/caf/detail/init_fun_factory.hpp
  libcaf_core/caf/intrusive/forward_iterator.hpp
  libcaf_core/caf/intrusive/task_queue.hpp
  libcaf_core/caf/mixin/subscriber.hpp
  libcaf_core/src/node_id.cpp
  libcaf_core/test/intrusive/drr_queue.cpp
  libcaf_core/test/intrusive/task_queue.cpp
Labels: diagnostic

#984 Fix conversion constructor for caf::span
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/test/span.cpp
Labels: bugfix

#988 Do not use thread_local for MinGW
  libcaf_core/caf/config.hpp
Labels: bugfix

#987 Resurrect serialized_size function
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/deserializer.hpp
  libcaf_core/caf/detail/serialized_size.hpp
  libcaf_core/caf/read_inspector.hpp
  libcaf_core/caf/serializer.hpp
  libcaf_core/caf/write_inspector.hpp
  libcaf_core/src/detail/serialized_size.cpp
  libcaf_core/test/detail/serialized_size.cpp
Labels: new feature
