Repository actor-framework/actor-framework, pull requests merged in 2019-12, with the labels that each got.

#990 Make credit computation configurable
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/attach_stream_stage.hpp
  libcaf_core/caf/credit_controller.hpp
  libcaf_core/caf/defaults.hpp
  libcaf_core/caf/detail/complexity_based_credit_controller.hpp
  libcaf_core/caf/detail/size_based_credit_controller.hpp
  libcaf_core/caf/detail/test_credit_controller.hpp
  libcaf_core/caf/inbound_path.hpp
  libcaf_core/caf/scheduler/worker.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/complexity_based_credit_controller.cpp
  libcaf_core/src/credit_controller.cpp
  libcaf_core/src/defaults.cpp
  libcaf_core/src/inbound_path.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/src/size_based_credit_controller.cpp
  libcaf_core/src/stream_manager.cpp
  libcaf_core/src/test_credit_controller.cpp
  libcaf_core/test/inbound_path.cpp
  libcaf_core/test/native_streaming_classes.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: new feature

#995 Denoise gcc build on linux
  libcaf_core/caf/detail/init_fun_factory.hpp
  libcaf_core/caf/outbound_path.hpp
  libcaf_core/caf/settings.hpp
Labels: diagnostic

#996 Remove CAF_NO_THREAD_LOCAL and its workarounds
  cmake/check-compiler-features.cpp
  libcaf_core/caf/config.hpp
  libcaf_core/caf/logger.hpp
  libcaf_core/src/logger.cpp
Labels: refactoring

#994 Remove legacy duration type (replaced by timespan)
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/after.hpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/behavior.hpp
  libcaf_core/caf/detail/behavior_impl.hpp
  libcaf_core/caf/detail/blocking_behavior.hpp
  libcaf_core/caf/duration.hpp
  libcaf_core/caf/function_view.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/message_handler.hpp
  libcaf_core/caf/mixin/requester.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/scheduler/abstract_coordinator.hpp
  libcaf_core/caf/timeout_definition.hpp
  libcaf_core/caf/timespan.hpp
  libcaf_core/caf/type_nr.hpp
  libcaf_core/caf/typed_behavior.hpp
  libcaf_core/caf/uniform_type_info_map.hpp
  libcaf_core/src/blocking_actor.cpp
  libcaf_core/src/detail/behavior_impl.cpp
  libcaf_core/src/detail/blocking_behavior.cpp
  libcaf_core/src/duration.cpp
  libcaf_core/src/local_actor.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/src/scheduler/abstract_coordinator.cpp
  libcaf_core/src/uniform_type_info_map.cpp
  libcaf_core/test/actor_clock.cpp
  libcaf_core/test/binary_deserializer.cpp
  libcaf_core/test/binary_serializer.cpp
  libcaf_core/test/serialization.cpp
  libcaf_core/test/simple_timeout.cpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_io/src/io/middleman.cpp
Labels: refactoring

#997 Remove all opencl references
  Jenkinsfile
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/src/actor_system.cpp
  libcaf_core/src/actor_system_config.cpp
  tools/caf-run.cpp
Labels: refactoring

#998 Tweak build scaffold
  cmake/FindCAF.cmake
  configure
Labels: bugfix, improvement

#1001 change syntax to Bibtex
  README.md
Labels: documentation

#1004 fixes compile error in libcaf_openssl/middleman_actor.cpp on windows
  libcaf_openssl/src/openssl/middleman_actor.cpp
Labels: bugfix
