Repository actor-framework/actor-framework, pull requests merged in 2019-08, with the labels that each got.

#863 Make node_id opaque and add an URI-based alternative
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_control_block.hpp
  libcaf_core/caf/atom.hpp
  libcaf_core/caf/detail/fnv_hash.hpp
  libcaf_core/caf/node_id.hpp
  libcaf_core/caf/uri.hpp
  libcaf_core/src/atom.cpp
  libcaf_core/src/fnv_hash.cpp
  libcaf_core/src/node_id.cpp
  libcaf_core/src/uri.cpp
  libcaf_io/src/basp_broker.cpp
  libcaf_io/src/ip_endpoint.cpp
  libcaf_io/src/middleman.cpp
  libcaf_io/src/routing_table.cpp
  libcaf_io/test/basp.cpp
  libcaf_io/test/worker.cpp
  tools/caf-vec.cpp
Labels: new feature

#865 Add byte and span replacements
  libcaf_core/caf/byte.hpp
  libcaf_core/caf/span.hpp
  libcaf_core/test/byte.cpp
  libcaf_core/test/span.cpp
Labels: new feature

#868 Fix handling of containers with user-defined types
  libcaf_core/caf/data_processor.hpp
Labels: bugfix

#873 Support [a.b] nesting and relax key name parsing
  libcaf_core/caf/detail/parser/read_ini.hpp
  libcaf_core/test/read_ini.cpp
Labels: bugfix, new feature

#872 Properly store CLI remainder in config
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/test/actor_system_config.cpp
Labels: bugfix

#879 Fix potential segfault with logging enabled
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/uniform_type_info_map.hpp
  libcaf_core/src/inbound_path.cpp
  libcaf_core/src/message.cpp
  libcaf_core/src/uniform_type_info_map.cpp
Labels: bugfix

#877 Fix output of --dump-config
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/settings.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/settings.cpp
Labels: bugfix

#875 Add templatized serializer and deserialiser implementations + tests
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/binary_deserializer.hpp
  libcaf_core/caf/binary_serializer.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/serializer_impl.hpp
  libcaf_core/caf/span.hpp
  libcaf_core/src/binary_deserializer.cpp
  libcaf_core/test/serializer_impl.cpp
Labels: refactoring

#881 Fix potential deadlock in proxy_registry
  libcaf_core/src/proxy_registry.cpp
Labels: bugfix

#886 Make it easier to build CAF as a CMake subproject
  CMakeLists.txt
Labels: build harness

#885 Add IPv4 and IPv6 endpoint abstraction
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/ip_endpoint.hpp
  libcaf_core/caf/ipv4_endpoint.hpp
  libcaf_core/caf/ipv6_endpoint.hpp
  libcaf_core/src/ipv4_endpoint.cpp
  libcaf_core/src/ipv6_endpoint.cpp
  libcaf_core/test/ipv4_endpoint.cpp
  libcaf_core/test/ipv6_endpoint.cpp
Labels: new feature

#890 Fix handling of CLI string arguments
  libcaf_core/caf/detail/parse.hpp
  libcaf_core/src/parse.cpp
Labels: bugfix

#887 Fix linker issue when building with Clang 7
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/default_sum_type_access.hpp
  libcaf_core/caf/sum_type_token.hpp
Labels: bugfix

#895 Fix infinite recursion in read_ini
  libcaf_core/caf/detail/parser/read_ini.hpp
  libcaf_core/test/read_ini.cpp
Labels: bugfix

#896 Add ip_endpoint forward-declaration to fwd.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_io/src/udp.cpp
Labels: refactoring

#892 Allow treating config_value as a tuple
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/detail/move_if_not_ptr.hpp
  libcaf_core/test/config_value.cpp
Labels: new feature

#900 Add public API for reading CAF config files
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/detail/ini_consumer.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/ini_consumer.cpp
Labels: new feature

#893 Add unit tests for settings
  libcaf_core/caf/settings.hpp
  libcaf_core/test/settings.cpp
Labels: testing
