Repository actor-framework/actor-framework, pull requests merged in 2019-07, with the labels that each got.

#852 Fix integer overflow check in number parser
  libcaf_core/caf/detail/parser/add_ascii.hpp
  libcaf_core/caf/detail/parser/sub_ascii.hpp
  libcaf_core/test/ipv4_address.cpp
  libcaf_core/test/read_number.cpp
Labels: bugfix

#854 Parallelize deserialization of incoming BASP messages
  CONTRIBUTING.md
  examples/caf-application.ini
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/atom.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/defaults.hpp
  libcaf_core/caf/message.hpp
  libcaf_core/caf/proxy_registry.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/src/abstract_actor.cpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/blocking_actor.cpp
  libcaf_core/src/defaults.cpp
  libcaf_core/src/forwarding_actor_proxy.cpp
  libcaf_core/src/message.cpp
  libcaf_core/src/proxy_registry.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/io/basp/fwd.hpp
  libcaf_io/caf/io/basp/instance.hpp
  libcaf_io/caf/io/basp/message_queue.hpp
  libcaf_io/caf/io/basp/remote_message_handler.hpp
  libcaf_io/caf/io/basp/routing_table.hpp
  libcaf_io/caf/io/basp/worker.hpp
  libcaf_io/caf/io/basp/worker_hub.hpp
  libcaf_io/caf/io/basp_broker.hpp
  libcaf_io/caf/io/hook.hpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_io/src/basp_broker.cpp
  libcaf_io/src/hook.cpp
  libcaf_io/src/instance.cpp
  libcaf_io/src/message_queue.cpp
  libcaf_io/src/middleman.cpp
  libcaf_io/src/routing_table.cpp
  libcaf_io/src/worker.cpp
  libcaf_io/src/worker_hub.cpp
  libcaf_io/test/basp.cpp
  libcaf_io/test/message_queue.cpp
  libcaf_io/test/worker.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: performance

#858 Don't consider uint8_t and bool as same
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/test/variant.cpp
Labels: bugfix

#862 Allow using meta::hex_formatted for integer types
  libcaf_core/caf/detail/append_hex.hpp
  libcaf_core/caf/detail/stringification_inspector.hpp
Labels: new feature
