Repository actor-framework/actor-framework, pull requests merged in 2019-09, with the labels that each got.

#899 Improve stringification_inspector implementation
  libcaf_core/caf/deep_to_string.hpp
  libcaf_core/caf/detail/parser/read_timespan.hpp
  libcaf_core/caf/detail/stringification_inspector.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/stringification_inspector.cpp
  libcaf_core/test/deep_to_string.cpp
  libcaf_core/test/message.cpp
  libcaf_core/test/serialization.cpp
  libcaf_core/test/serializer_impl.cpp
Labels: refactoring

#904 Add scheduled_send for sending with absolute timeout
  libcaf_core/caf/group.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/send.hpp
  libcaf_core/caf/typed_actor_pointer.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/test/composable_behavior.cpp
  libcaf_core/test/sender.cpp
  libcaf_core/test/simple_timeout.cpp
Labels: new feature

#913 Reduce stack usage and indirections in serializers
  libcaf_core/caf/data_processor.hpp
  libcaf_core/caf/deep_to_string.hpp
  libcaf_core/caf/error.hpp
  libcaf_core/src/error.cpp
Labels: bugfix

#915 Fix several warnings on GCC and Clang
  libcaf_core/caf/data_processor.hpp
  libcaf_core/caf/detail/ini_consumer.hpp
  libcaf_core/caf/detail/parser/add_ascii.hpp
  libcaf_core/caf/detail/parser/sub_ascii.hpp
  libcaf_core/caf/typed_behavior.hpp
  libcaf_core/src/fnv_hash.cpp
  libcaf_core/src/node_id.cpp
  libcaf_core/test/inspector.cpp
  libcaf_core/test/match.cpp
  libcaf_core/test/serialization.cpp
  libcaf_core/test/thread_hook.cpp
  libcaf_io/caf/io/network/event_handler.hpp
  libcaf_io/caf/io/receive_policy.hpp
  libcaf_io/src/event_handler.cpp
  libcaf_io/src/stream.cpp
  libcaf_io/test/typed_broker.cpp
  libcaf_openssl/src/session.cpp
Labels: diagnostic

#917 Use CMAKE_INSTALL_* vars for install paths
  CMakeLists.txt
  cmake/FindCAF.cmake
  examples/CMakeLists.txt
  libcaf_core/CMakeLists.txt
  libcaf_io/CMakeLists.txt
  libcaf_opencl/CMakeLists.txt
  libcaf_openssl/CMakeLists.txt
  libcaf_python/CMakeLists.txt
  tools/CMakeLists.txt
Labels: build harness

#909 Support streaming in composable behaviors
  doc/tex/Streaming.tex
  examples/streaming/integer_stream.cpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/attach_continuous_stream_source.hpp
  libcaf_core/caf/attach_continuous_stream_stage.hpp
  libcaf_core/caf/attach_stream_sink.hpp
  libcaf_core/caf/attach_stream_source.hpp
  libcaf_core/caf/attach_stream_stage.hpp
  libcaf_core/caf/composable_behavior.hpp
  libcaf_core/caf/composed_type.hpp
  libcaf_core/caf/deduce_mpi.hpp
  libcaf_core/caf/detail/invoke_result_visitor.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/make_sink_result.hpp
  libcaf_core/caf/make_source_result.hpp
  libcaf_core/caf/make_stage_result.hpp
  libcaf_core/caf/output_stream.hpp
  libcaf_core/caf/param.hpp
  libcaf_core/caf/replies_to.hpp
  libcaf_core/caf/result.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/stream_manager.hpp
  libcaf_core/caf/stream_slot.hpp
  libcaf_core/caf/typed_actor_pointer.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/test/composable_behavior.cpp
  libcaf_core/test/continuous_streaming.cpp
  libcaf_core/test/fused_downstream_manager.cpp
  libcaf_core/test/metaprogramming.cpp
  libcaf_core/test/pipeline_streaming.cpp
  libcaf_core/test/selective_streaming.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: bugfix, new feature

#920 Fix holds_alternative and get_if for settings
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/settings.hpp
  libcaf_core/test/settings.cpp
Labels: bugfix
