Repository actor-framework/actor-framework, pull requests merged in 2019-04, with the labels that each got.

#829 Fix thread-safe multitimeout
  libcaf_core/caf/detail/thread_safe_actor_clock.hpp
  libcaf_core/src/thread_safe_actor_clock.cpp
Labels: needs review

#831 Fix nested categories in config options
  libcaf_core/src/config_option_set.cpp
  libcaf_core/test/config_option.cpp
  libcaf_core/test/config_option_set.cpp
Labels: bugfix, needs review

#834 Fix a couple of typos
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/config.hpp
Labels: needs review

#835 add timeout for transport-policies
  libcaf_io/caf/io/network/newb_base.hpp
  libcaf_io/caf/io/newb.hpp
  libcaf_io/caf/policy/transport.hpp
Labels: needs review

#833 docs - add a chapter on Testing
  doc/CMakeLists.txt
  doc/tex/Testing.tex
  doc/tex/index.rst
  doc/tex/manual.tex
Labels: documentation, improvement, needs review
