Repository actor-framework/actor-framework, pull requests merged in 2019-03, with the labels that each got.

#824 Allow IPO on gcc/clang
  CMakeLists.txt
  examples/CMakeLists.txt
  libcaf_core/CMakeLists.txt
  libcaf_io/CMakeLists.txt
  libcaf_opencl/CMakeLists.txt
  libcaf_openssl/CMakeLists.txt
  tools/CMakeLists.txt
Labels: needs review, new feature

#825 fix a couple of typos
  doc/tex/MessageHandlers.tex
  libcaf_core/src/scheduled_actor.cpp
Labels: documentation, needs review

#826 Fix a typo in contributing guidelines
  CONTRIBUTING.md
Labels: documentation, needs review

#827 Add marker to make categories optional on the CLI
  libcaf_core/caf/config_option.hpp
  libcaf_core/src/config_option.cpp
  libcaf_core/src/config_option_set.cpp
  libcaf_core/src/make_config_option.cpp
  libcaf_core/test/config_option.cpp
  libcaf_core/test/config_option_set.cpp
Labels: improvement, needs review

#821 Parallelize deserialization of incoming BASP messages
  examples/caf-application.ini
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/atom.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/defaults.hpp
  libcaf_core/caf/message.hpp
  libcaf_core/caf/proxy_registry.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/src/abstract_actor.cpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/blocking_actor.cpp
  libcaf_core/src/defaults.cpp
  libcaf_core/src/forwarding_actor_proxy.cpp
  libcaf_core/src/message.cpp
  libcaf_core/src/proxy_registry.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/io/basp/fwd.hpp
  libcaf_io/caf/io/basp/instance.hpp
  libcaf_io/caf/io/basp/message_queue.hpp
  libcaf_io/caf/io/basp/remote_message_handler.hpp
  libcaf_io/caf/io/basp/routing_table.hpp
  libcaf_io/caf/io/basp/worker.hpp
  libcaf_io/caf/io/basp/worker_hub.hpp
  libcaf_io/caf/io/basp_broker.hpp
  libcaf_io/caf/io/hook.hpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_io/src/basp_broker.cpp
  libcaf_io/src/hook.cpp
  libcaf_io/src/instance.cpp
  libcaf_io/src/message_queue.cpp
  libcaf_io/src/middleman.cpp
  libcaf_io/src/routing_table.cpp
  libcaf_io/src/worker.cpp
  libcaf_io/src/worker_hub.cpp
  libcaf_io/test/basp.cpp
  libcaf_io/test/message_queue.cpp
  libcaf_io/test/worker.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: needs review, performance
