Repository actor-framework/actor-framework, pull requests merged in 2020-07, with the labels that each got.

#1120 Close socket if SSL session initialization fails
  libcaf_openssl/src/openssl/middleman_actor.cpp
Labels: bugfix

#1126 Update README build, CMake sections
  README.md
Labels: documentation

#1127 Change Conan reference to Conan Center
  README.md
Labels: documentation

#1131 Fix missing header file in install directory
  libcaf_core/CMakeLists.txt
Labels: build harness
