Repository actor-framework/actor-framework, pull requests merged in 2020-02, with the labels that each got.

#1037 Remove doc target an properly handle OPENSSL_INCLUDE_DIR in submodule mode
  CMakeLists.txt
  libcaf_core/caf/detail/parser/read_uri.hpp
Labels: bugfix

#1034 Add typed view types for messages
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/const_typed_message_view.hpp
  libcaf_core/caf/typed_message_view.hpp
  libcaf_core/test/const_typed_message_view.cpp
  libcaf_core/test/typed_message_view.cpp
Labels: new feature

#1038 Add -pthread flag when looking for libc++
  CMakeLists.txt
Labels: build harness

#1039 Add missing operator== for exit_msg
  libcaf_core/caf/system_messages.hpp
Labels: bugfix

#1043 Avoid producing unexpected log files
  libcaf_core/caf/logger.hpp
  libcaf_core/src/defaults.cpp
Labels: bugfix

#1044 Add vcpkg installation instructions
  README.md
Labels: documentation

#1045 Remove extra semicolon to quiet -Wpedantic
  libcaf_core/caf/fwd.hpp
Labels: diagnostic

#1050 Various fixes, mostly related to typed_actor_view
  libcaf_core/caf/composed_behavior.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/caf/typed_actor_pointer.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_io/caf/io/middleman.hpp
Labels: bugfix

#1056 Add make_typed_behavior convenience function
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/typed_behavior.hpp
  libcaf_core/test/typed_behavior.cpp
Labels: new feature

#1055 Deliver errors if requests fail with exceptions
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/test/mixin/requester.cpp
Labels: bugfix
