Repository actor-framework/actor-framework, pull requests merged in 2020-03, with the labels that each got.

#1059 Add CAF_CORE_EXPORT to tracing_data_factory
  libcaf_core/caf/all.hpp
  libcaf_core/caf/tracing_data_factory.hpp
Labels: bugfix

#1058 Add parse function for node_id
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/node_id.hpp
  libcaf_core/caf/parser_state.hpp
  libcaf_core/caf/uri.hpp
  libcaf_core/src/node_id.cpp
  libcaf_core/src/uri.cpp
  libcaf_core/test/node_id.cpp
  libcaf_core/test/uri.cpp
Labels: new feature

#1068 Add missing map include
  libcaf_core/caf/proxy_registry.hpp
Labels: bugfix

#1062 Send client handshake immediately
  libcaf_io/src/io/basp/instance.cpp
  libcaf_io/src/io/basp_broker.cpp
Labels: bugfix

#1063 Add a changelog, remove (outdated) migration guide
  CHANGELOG.md
  manual/MigrationGuides.rst
  manual/index.rst
Labels: documentation

#1071 Allow actors to monitor CAF nodes
  CHANGELOG.md
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/system_messages.hpp
  libcaf_core/src/actor_system.cpp
  libcaf_core/src/local_actor.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/io/basp_broker.hpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_io/src/io/basp_broker.cpp
  libcaf_io/src/io/middleman.cpp
  libcaf_io/test/io/monitor.cpp
  libcaf_test/caf/test/io_dsl.hpp
Labels: new feature

#1069 Fix handling of spawn requests to the local node
  libcaf_io/src/io/middleman_actor_impl.cpp
Labels: bugfix

#1067 Fix unexpected responses to anon_send, close #1046
  libcaf_core/caf/detail/profiled_send.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/test/mixin/sender.cpp
Labels: bugfix

#1072 Fix several issues with typed actor views
  CHANGELOG.md
  CMakeLists.txt
  libcaf_core/caf/actor_profiler.hpp
  libcaf_core/caf/attach_continuous_stream_source.hpp
  libcaf_core/caf/attach_stream_source.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/caf/typed_actor_pointer.hpp
  libcaf_core/caf/typed_actor_view.hpp
Labels: bugfix

#1073 Enable states with non-default constructor
  CHANGELOG.md
  examples/message_passing/fan_out_request.cpp
  libcaf_core/caf/composable_behavior_based_actor.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/infer_handle.hpp
  libcaf_core/caf/stateful_actor.hpp
  libcaf_core/caf/type_nr.hpp
  libcaf_core/caf/typed_actor_pointer.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/src/actor_registry.cpp
  libcaf_core/src/actor_system.cpp
  libcaf_core/test/stateful_actor.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: refactoring

#1074 Add new UUID class
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/all.hpp
  libcaf_core/caf/detail/append_hex.hpp
  libcaf_core/caf/detail/append_percent_encoded.hpp
  libcaf_core/caf/detail/config_value_field_base.hpp
  libcaf_core/caf/detail/parser/add_ascii.hpp
  libcaf_core/caf/detail/parser/read_string.hpp
  libcaf_core/caf/detail/stringification_inspector.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/intrusive_ptr.hpp
  libcaf_core/caf/pec.hpp
  libcaf_core/caf/uuid.hpp
  libcaf_core/src/config_option_set.cpp
  libcaf_core/src/detail/append_hex.cpp
  libcaf_core/src/detail/append_percent_encoded.cpp
  libcaf_core/src/ipv6_address.cpp
  libcaf_core/src/node_id.cpp
  libcaf_core/src/pec_strings.cpp
  libcaf_core/src/uuid.cpp
  libcaf_core/test/uuid.cpp
Labels: new feature
