Repository actor-framework/actor-framework, pull requests merged in 2020-01, with the labels that each got.

#999 Enable compact list notation in config files
  libcaf_core/caf/detail/parser/chars.hpp
  libcaf_core/caf/detail/parser/fsm.hpp
  libcaf_core/caf/detail/parser/read_floating_point.hpp
  libcaf_core/caf/detail/parser/read_ini.hpp
  libcaf_core/caf/detail/parser/read_number.hpp
  libcaf_core/caf/detail/parser/read_number_or_timespan.hpp
  libcaf_core/caf/pec.hpp
  libcaf_core/test/detail/parser/read_ini.cpp
  libcaf_core/test/detail/parser/read_number.cpp
Labels: new feature

#1005 netinet/ip.h needs sys/types.h on FreeBSD gcc architectures
  libcaf_io/src/io/network/default_multiplexer.cpp
  libcaf_io/src/io/network/ip_endpoint.cpp
  libcaf_io/src/io/network/native_socket.cpp
Labels: bugfix

#1015 Allow config keys to start with numbers
  libcaf_core/caf/detail/parser/read_ini.hpp
  libcaf_core/test/detail/parser/read_ini.cpp
Labels: bugfix

#1017 Fix inline_all_enqueues, add trace logging
  libcaf_core/src/scheduler/test_coordinator.cpp
Labels: bugfix

#1019 Implement workaround for stream shutdown issue
  libcaf_core/src/scheduled_actor.cpp
Labels: bugfix

#1020 Fix compiler error caused by function hiding
  libcaf_core/caf/fused_downstream_manager.hpp
Labels: bug

#1021 Improve to_string output for caf::error
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/error.cpp
Labels: improvement

#1022 Fix URI edge cases for paths and curly braces
  libcaf_core/caf/detail/parser/read_uri.hpp
  libcaf_core/src/detail/append_percent_encoded.cpp
  libcaf_core/test/uri.cpp
Labels: bugfix

#1012 Add new choose_response policy
  doc/tex/MessagePassing.tex
  examples/message_passing/fan_out_request.cpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/policy/select_all.hpp
  libcaf_core/caf/policy/select_any.hpp
  libcaf_core/caf/sec.hpp
  libcaf_core/test/mixin/requester.cpp
  libcaf_core/test/policy/select_all.cpp
  libcaf_core/test/policy/select_any.cpp
Labels: new feature

#1023 Report errors while connecting two CAF nodes
  libcaf_core/caf/sec.hpp
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/io/basp/connection_state.hpp
  libcaf_io/caf/io/basp/instance.hpp
  libcaf_io/caf/io/basp_broker.hpp
  libcaf_io/src/io/basp/instance.cpp
  libcaf_io/src/io/basp_broker.cpp
Labels: refactoring

#1026 Add to_strings for enum back to the repository
  CMakeLists.txt
  cmake/caf-generate-enum-strings.cpp
  cmake/check-consistency.cmake
  libcaf_core/CMakeLists.txt
  libcaf_core/src/exit_reason_strings.cpp
  libcaf_core/src/intrusive/inbox_result_strings.cpp
  libcaf_core/src/intrusive/task_result_strings.cpp
  libcaf_core/src/invoke_msg_result_strings.cpp
  libcaf_core/src/message_priority_strings.cpp
  libcaf_core/src/pec_strings.cpp
  libcaf_core/src/sec_strings.cpp
  libcaf_core/src/stream_priority_strings.cpp
  libcaf_io/CMakeLists.txt
  libcaf_io/src/io/basp/message_type_strings.cpp
  libcaf_io/src/io/network/operation_strings.cpp
Labels: build harness

#1027 Add to_strings for enum back to the repository (Part 2)
  CMakeLists.txt
  Jenkinsfile
  cmake/caf-generate-enum-strings.cpp
  cmake/check-consistency.cmake
  libcaf_core/CMakeLists.txt
  libcaf_core/src/exit_reason_strings.cpp
  libcaf_core/src/intrusive/inbox_result_strings.cpp
  libcaf_core/src/intrusive/task_result_strings.cpp
  libcaf_core/src/invoke_msg_result_strings.cpp
  libcaf_core/src/message_priority_strings.cpp
  libcaf_core/src/pec_strings.cpp
  libcaf_core/src/sec_strings.cpp
  libcaf_core/src/stream_priority_strings.cpp
  libcaf_io/CMakeLists.txt
  libcaf_io/src/io/basp/message_type_strings.cpp
  libcaf_io/src/io/network/operation_strings.cpp
Labels: build harness

#1032 Suppress flag and compiler setup in subdir mode
  CMakeLists.txt
  examples/CMakeLists.txt
  libcaf_opencl/examples/CMakeLists.txt
  tools/CMakeLists.txt
Labels: build harness

#1031 Fix tables, lists, and nested commands in manual
  doc/cmake/caf-generate-rst.cpp
  doc/tex/Actors.tex
  doc/tex/ConfiguringActorApplications.tex
  doc/tex/Introduction.tex
Labels: bugfix, documentation

#1029 Add scaffold for new type_id API
  .clang-format
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/make_meta_object.hpp
  libcaf_core/caf/detail/meta_object.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/init_global_meta_objects.hpp
  libcaf_core/caf/type_id.hpp
  libcaf_core/caf/type_id_list.hpp
  libcaf_core/src/detail/meta_object.cpp
  libcaf_core/src/type_id_list.cpp
  libcaf_core/test/detail/meta_object.cpp
  libcaf_core/test/type_id_list.cpp
Labels: new feature

#1035 profiled_coordinator.hpp: check for RUSAGE_THREAD
  libcaf_core/caf/scheduler/profiled_coordinator.hpp
Labels: bugfix
