Repository actor-framework/actor-framework, pull requests merged in 2020-12, with the labels that each got.

#1179 Add new capabilities for BDD-style unit tests
  libcaf_core/test/broadcast_downstream_manager.cpp
  libcaf_core/test/core-test.hpp
  libcaf_core/test/detail/group_tunnel.cpp
  libcaf_core/test/expected.cpp
  libcaf_test/caf/test/bdd_dsl.hpp
Labels: refactoring

#1187 Use CMAKE_INSTALL_FULL_LIBDIR to install CMake files
  CMakeLists.txt
Labels: bugfix, build harness

#1192 Add new get_as and get_or utility functions
  libcaf_core/caf/binary_deserializer.hpp
  libcaf_core/caf/binary_serializer.hpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/config_value_reader.hpp
  libcaf_core/caf/config_value_writer.hpp
  libcaf_core/caf/deserializer.hpp
  libcaf_core/caf/detail/bounds_checker.hpp
  libcaf_core/caf/detail/parse.hpp
  libcaf_core/caf/detail/print.hpp
  libcaf_core/caf/detail/serialized_size.hpp
  libcaf_core/caf/detail/stringification_inspector.hpp
  libcaf_core/caf/dictionary.hpp
  libcaf_core/caf/hash/fnv.hpp
  libcaf_core/caf/hash/sha1.hpp
  libcaf_core/caf/load_inspector.hpp
  libcaf_core/caf/load_inspector_base.hpp
  libcaf_core/caf/save_inspector.hpp
  libcaf_core/caf/save_inspector_base.hpp
  libcaf_core/caf/sec.hpp
  libcaf_core/caf/serializer.hpp
  libcaf_core/caf/settings.hpp
  libcaf_core/caf/type_id.hpp
  libcaf_core/caf/type_id_list.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/src/binary_deserializer.cpp
  libcaf_core/src/binary_serializer.cpp
  libcaf_core/src/config_value.cpp
  libcaf_core/src/config_value_reader.cpp
  libcaf_core/src/config_value_writer.cpp
  libcaf_core/src/detail/serialized_size.cpp
  libcaf_core/src/detail/stringification_inspector.cpp
  libcaf_core/src/message.cpp
  libcaf_core/src/sec_strings.cpp
  libcaf_core/src/settings.cpp
  libcaf_core/src/tracing_data.cpp
  libcaf_core/src/type_id_list.cpp
  libcaf_core/test/config_value.cpp
  libcaf_core/test/core-test.hpp
  libcaf_core/test/detail/parser/read_config.cpp
  libcaf_core/test/load_inspector.cpp
  libcaf_core/test/save_inspector.cpp
Labels: new feature
