Repository actor-framework/actor-framework, pull requests merged in 2020-08, with the labels that each got.

#1132 Remove obsolete files, fix serial_reply unit test suite
  libcaf_core/CMakeLists.txt
  libcaf_core/src/decorator/splitter.cpp
  libcaf_core/src/type_id.cpp
  libcaf_core/test/core-test.hpp
  libcaf_core/test/detail/message_builder_element.cpp
  libcaf_core/test/serial_reply.cpp
Labels: refactoring

#1125 Store hosts as IP address when parsing URIs
  CHANGELOG.md
  libcaf_core/src/uri_builder.cpp
  libcaf_core/test/uri.cpp
Labels: bugfix

#1118 Capture message text of exceptions if actors die
  CHANGELOG.md
  cmake/caf-generate-enum-strings.cpp
  libcaf_core/caf/exit_reason.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/src/blocking_actor.cpp
  libcaf_core/src/exit_reason_strings.cpp
  libcaf_core/src/intrusive/inbox_result_strings.cpp
  libcaf_core/src/intrusive/task_result_strings.cpp
  libcaf_core/src/invoke_msg_result_strings.cpp
  libcaf_core/src/message_priority_strings.cpp
  libcaf_core/src/pec_strings.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/src/sec_strings.cpp
  libcaf_core/src/stream_priority_strings.cpp
  libcaf_core/test/custom_exception_handler.cpp
  libcaf_io/src/io/basp/message_type_strings.cpp
  libcaf_io/src/io/network/operation_strings.cpp
Labels: improvement

#1133 Fix datagram servant shutdown
  libcaf_io/src/io/abstract_broker.cpp
Labels: bugfix

#1137 Add telemetry for streams
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/broadcast_downstream_manager.hpp
  libcaf_core/caf/buffered_downstream_manager.hpp
  libcaf_core/caf/detail/stream_source_impl.hpp
  libcaf_core/caf/detail/stream_stage_impl.hpp
  libcaf_core/caf/downstream_manager_base.hpp
  libcaf_core/caf/downstream_msg.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/inbound_path.hpp
  libcaf_core/caf/intrusive/wdrr_dynamic_multiplexed_queue.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/policy/downstream_messages.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/src/actor_system.cpp
  libcaf_core/src/downstream_manager_base.cpp
  libcaf_core/src/inbound_path.cpp
  libcaf_core/src/local_actor.cpp
  libcaf_core/src/policy/downstream_messages.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/test/intrusive/wdrr_dynamic_multiplexed_queue.cpp
  libcaf_core/test/mock_streaming_classes.cpp
  manual/Metrics.rst
Labels: new feature
