Repository actor-framework/actor-framework, pull requests merged in 2020-04, with the labels that each got.

#1079 Add missing cast
  libcaf_test/caf/test/dsl.hpp
Labels: bugfix

#1082 Make FNV hash available as inspector
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/all.hpp
  libcaf_core/caf/detail/fnv_hash.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/hash/fnv.hpp
  libcaf_core/caf/meta/load_callback.hpp
  libcaf_core/caf/read_inspector.hpp
  libcaf_core/src/detail/type_id_list_builder.cpp
  libcaf_core/src/ipv4_endpoint.cpp
  libcaf_core/src/ipv6_endpoint.cpp
  libcaf_core/src/uri.cpp
  libcaf_core/test/hash/fnv.cpp
  libcaf_io/src/io/network/ip_endpoint.cpp
Labels: new feature

#1083 Make getter/setter of thread-local variable static
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/make_actor.hpp
Labels: refactoring

#1084 Add missing property getters to typed actor view
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/src/abstract_actor.cpp
Labels: refactoring

#1087 Modernize CMake setup
  CMakeLists.txt
  Jenkinsfile
  cmake/build_config.hpp.in
  configure
  examples/CMakeLists.txt
  examples/aout.cpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/raise_error.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/src/blocking_actor.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/test/custom_exception_handler.cpp
  libcaf_io/CMakeLists.txt
  libcaf_openssl/CMakeLists.txt
  tools/CMakeLists.txt
Labels: build harness, refactoring

#1089 Fix build on Clang 10
  libcaf_test/caf/test/dsl.hpp
Labels: bugfix

#1085 Re-implement the message builder
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/type_id_list_builder.hpp
  libcaf_core/caf/message_builder.hpp
  libcaf_core/caf/type_id_list.hpp
  libcaf_core/src/detail/type_id_list_builder.cpp
  libcaf_core/src/message_builder.cpp
  libcaf_core/test/message_builder.cpp
Labels: refactoring

#1090 Use only constexpr values as defaults
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/defaults.hpp
  libcaf_core/caf/scheduler/abstract_coordinator.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/defaults.cpp
  libcaf_core/src/scheduler/abstract_coordinator.cpp
  libcaf_core/test/thread_hook.cpp
  libcaf_io/src/io/basp/instance.cpp
  libcaf_io/test/io/basp_broker.cpp
Labels: refactoring

#1093 Fix build with C++17 enabled
  Jenkinsfile
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_opencl/examples/proper_matrix.cpp
  libcaf_opencl/examples/scan.cpp
  libcaf_opencl/test/opencl.cpp
Labels: bugfix

#1099 Fix build with exceptions disabled, close #1086
  Jenkinsfile
  libcaf_core/caf/message.hpp
  libcaf_core/caf/raise_error.hpp
  libcaf_core/src/detail/message_data.cpp
  libcaf_core/src/detail/type_id_list_builder.cpp
  libcaf_core/src/message_builder.cpp
  libcaf_core/test/byte.cpp
  libcaf_core/test/detail/unordered_flat_map.cpp
  libcaf_core/test/mixin/requester.cpp
Labels: bugfix

#1096 Disconnect BASP nodes when reaching connection timeouts
  examples/caf-application.ini
  libcaf_core/caf/defaults.hpp
  libcaf_core/caf/sec.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/defaults.cpp
  libcaf_core/src/sec_strings.cpp
  libcaf_io/caf/io/basp/endpoint_context.hpp
  libcaf_io/caf/io/basp/instance.hpp
  libcaf_io/caf/io/basp_broker.hpp
  libcaf_io/src/io/basp/instance.cpp
  libcaf_io/src/io/basp_broker.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: bugfix
