Repository actor-framework/actor-framework, pull requests merged in 2021-01, with the labels that each got.

#1194 Re-implement config_option using get_as
  CHANGELOG.md
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/config_option.hpp
  libcaf_core/caf/config_option_adder.hpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/detail/config_consumer.hpp
  libcaf_core/caf/detail/dispatch_parse_cli.hpp
  libcaf_core/caf/detail/parse.hpp
  libcaf_core/caf/detail/parser/read_config.hpp
  libcaf_core/caf/detail/stringification_inspector.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/make_config_option.hpp
  libcaf_core/caf/parser_state.hpp
  libcaf_core/caf/sec.hpp
  libcaf_core/caf/settings.hpp
  libcaf_core/caf/telemetry/histogram.hpp
  libcaf_core/caf/telemetry/metric_registry.hpp
  libcaf_core/src/actor_system.cpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/config_option.cpp
  libcaf_core/src/config_option_adder.cpp
  libcaf_core/src/config_option_set.cpp
  libcaf_core/src/config_value.cpp
  libcaf_core/src/config_value_reader.cpp
  libcaf_core/src/config_value_writer.cpp
  libcaf_core/src/detail/config_consumer.cpp
  libcaf_core/src/detail/parse.cpp
  libcaf_core/src/logger.cpp
  libcaf_core/src/make_config_option.cpp
  libcaf_core/src/scheduler/abstract_coordinator.cpp
  libcaf_core/src/sec_strings.cpp
  libcaf_core/src/settings.cpp
  libcaf_core/test/actor_system_config.cpp
  libcaf_core/test/config_option.cpp
  libcaf_core/test/config_option_set.cpp
  libcaf_core/test/config_value.cpp
  libcaf_core/test/config_value_writer.cpp
  libcaf_core/test/core-test.cpp
  libcaf_core/test/core-test.hpp
  libcaf_core/test/detail/config_consumer.cpp
  libcaf_core/test/detail/parse.cpp
  libcaf_core/test/detail/parser/read_bool.cpp
  libcaf_core/test/load_inspector.cpp
  libcaf_core/test/message.cpp
  libcaf_core/test/message_lifetime.cpp
  libcaf_core/test/mixin/requester.cpp
  libcaf_core/test/settings.cpp
  libcaf_core/test/span.cpp
  libcaf_core/test/variant.cpp
  libcaf_io/src/io/basp/instance.cpp
  libcaf_io/src/io/middleman.cpp
  libcaf_test/caf/test/bdd_dsl.hpp
  libcaf_test/caf/test/unit_test.hpp
  libcaf_test/caf/test/unit_test_impl.hpp
Labels: refactoring

#1165 Fix qt and protobuf examples
  .ci/centos-7/Dockerfile
  .ci/centos-8/Dockerfile
  .ci/debian-10/Dockerfile
  .ci/debian-9/Dockerfile
  .ci/fedora-31/Dockerfile
  .ci/fedora-32/Dockerfile
  .ci/ubuntu-16.04/Dockerfile
  .ci/ubuntu-18.04/Dockerfile
  .ci/ubuntu-20.04/Dockerfile
  .clang-format
  Jenkinsfile
  configure
  examples/CMakeLists.txt
  examples/broker/protobuf_broker.cpp
  examples/broker/simple_broker.cpp
  examples/qtsupport/chatwidget.cpp
  examples/qtsupport/chatwidget.hpp
  examples/qtsupport/qt_group_chat.cpp
  examples/remoting/distributed_calculator.cpp
  examples/remoting/group_chat.cpp
  examples/remoting/group_server.cpp
  examples/remoting/pingpong.proto
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/test/actor_system_config.cpp
Labels: bugfix

#1191 Add message::concat function
  libcaf_core/caf/byte.hpp
  libcaf_core/caf/detail/message_data.hpp
  libcaf_core/caf/detail/type_list.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/message.hpp
  libcaf_core/caf/type_id_list.hpp
  libcaf_core/src/detail/message_data.cpp
  libcaf_core/src/type_id_list.cpp
  libcaf_core/test/message.cpp
  libcaf_core/test/type_id_list.cpp
Labels: new feature

#1199 Avoid collisions with user types in CAF_ADD_ATOM
  CHANGELOG.md
  libcaf_core/caf/type_id.hpp
  libcaf_core/test/type_id_list.cpp
Labels: bugfix

#1200 Detect and report broken response promises
  CHANGELOG.md
  examples/message_passing/fixed_stack.cpp
  examples/message_passing/promises.cpp
  libcaf_core/caf/detail/default_invoke_result_visitor.hpp
  libcaf_core/caf/detail/typed_actor_util.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/response_promise.hpp
  libcaf_core/caf/sec.hpp
  libcaf_core/caf/typed_response_promise.hpp
  libcaf_core/src/response_promise.cpp
  libcaf_core/src/sec_strings.cpp
  libcaf_core/src/stream_manager.cpp
  libcaf_core/test/response_promise.cpp
  libcaf_core/test/typed_response_promise.cpp
Labels: improvement

#1205 Fix LGTM warnings
  .lgtm.yml
  libcaf_core/caf/unit.hpp
  libcaf_core/src/blocking_actor.cpp
Labels: diagnostic

#1202 Fix shutdown issue with detached actors
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/detail/private_thread.hpp
  libcaf_core/caf/detail/private_thread_pool.hpp
  libcaf_core/caf/scheduler/worker.hpp
  libcaf_core/src/actor_system.cpp
  libcaf_core/src/blocking_actor.cpp
  libcaf_core/src/detail/private_thread.cpp
  libcaf_core/src/detail/private_thread_pool.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/test/detail/private_thread_pool.cpp
Labels: bugfix

#1203 Improve to_string output of errors
  cmake/caf-generate-enum-strings.cpp
  libcaf_core/src/error.cpp
  libcaf_core/src/exit_reason_strings.cpp
  libcaf_core/src/intrusive/inbox_result_strings.cpp
  libcaf_core/src/intrusive/task_result_strings.cpp
  libcaf_core/src/invoke_message_result_strings.cpp
  libcaf_core/src/message_priority_strings.cpp
  libcaf_core/src/pec_strings.cpp
  libcaf_core/src/sec_strings.cpp
  libcaf_core/src/stream_priority_strings.cpp
  libcaf_core/test/actor_profiler.cpp
  libcaf_core/test/error.cpp
  libcaf_io/src/io/basp/message_type_strings.cpp
  libcaf_io/src/io/network/operation_strings.cpp
Labels: refactoring
