Repository actor-framework/actor-framework, pull requests merged in 2021-06, with the labels that each got.

#1267 Fix CMakeLists.txt for installing caf-tools
  tools/CMakeLists.txt
Labels: build harness

#1269 Fixed typo
  manual/Actors.rst
  manual/Error.rst
Labels: documentation

#1273 Fix sign-compare warnings on GCC
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/defaults.hpp
  libcaf_core/caf/detail/print.hpp
  libcaf_core/caf/type_id_list.hpp
Labels: diagnostic

#1274 Fix shutdown issue when using blocking actors
  CHANGELOG.md
  libcaf_core/src/blocking_actor.cpp
  libcaf_core/src/detail/private_thread_pool.cpp
Labels: bugfix

#1275 Fix some typos
  libcaf_core/caf/detail/meta_object.hpp
  libcaf_core/caf/detail/monotonic_buffer_resource.hpp
  libcaf_core/caf/intrusive_cow_ptr.hpp
  libcaf_core/test/detail/unique_function.cpp
  libcaf_core/test/dictionary.cpp
  libcaf_core/test/variant.cpp
  libcaf_io/caf/io/basp/connection_state.hpp
  libcaf_io/caf/io/basp/instance.hpp
  libcaf_openssl/test/openssl/authentication.cpp
  manual/TypeInspection.rst
Labels: documentation, refactoring

#1272 Modernize functor_attachable and allow non-const default handlers
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/functor_attachable.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/test/scheduled_actor.cpp
Labels: bugfix, refactoring

#1278 Add process metrics importer
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/telemetry/importer/process.hpp
  libcaf_core/src/telemetry/importer/process.cpp
  libcaf_io/caf/detail/prometheus_broker.hpp
  libcaf_io/src/detail/prometheus_broker.cpp
Labels: new feature
