Repository actor-framework/actor-framework, pull requests merged in 2022-05, with the labels that each got.

#1335 Load modules before parsing CLI / config file
  CHANGELOG.md
  libcaf_core/caf/exec_main.hpp
Labels: bugfix

#1337 Fix actor_widget exit
  libcaf_core/caf/mixin/actor_widget.hpp
Labels: bugfix

#1339 Assign type ID to UUID
  libcaf_core/caf/type_id.hpp
  libcaf_core/src/init_global_meta_objects.cpp
  libcaf_io/caf/io/basp/version.hpp
Labels: bugfix

#1342 Use launch_thread API in the new middleman
  libcaf_net/src/net/middleman.cpp
Labels: refactoring

#1334 Implement new promises and futures
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/action.hpp
  libcaf_core/caf/async/execution_context.hpp
  libcaf_core/caf/async/future.hpp
  libcaf_core/caf/async/fwd.hpp
  libcaf_core/caf/async/promise.hpp
  libcaf_core/caf/async/spsc_buffer.hpp
  libcaf_core/caf/detail/async_cell.hpp
  libcaf_core/caf/flow/coordinator.hpp
  libcaf_core/caf/flow/op/from_resource.hpp
  libcaf_core/caf/flow/scoped_coordinator.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/src/async/execution_context.cpp
  libcaf_core/src/flow/scoped_coordinator.cpp
  libcaf_core/src/scheduled_actor.cpp
  libcaf_core/test/async/promise.cpp
Labels: new feature

#1348 Fix instance getters on the metric registry
  CHANGELOG.md
  libcaf_core/caf/telemetry/metric_registry.hpp
  libcaf_core/src/telemetry/metric_registry.cpp
  libcaf_core/test/telemetry/metric_registry.cpp
Labels: bugfix

#1338 Generate valid config syntax from --dump-config
  CHANGELOG.md
  libcaf_core/src/actor_system_config.cpp
Labels: improvement

#1332 Fix bookkeeping of the field name
  libcaf_core/caf/json_reader.hpp
  libcaf_core/src/json_reader.cpp
  libcaf_core/test/json_reader.cpp
Labels: bugfix
