Repository actor-framework/actor-framework, pull requests merged in 2023-10, with the labels that each got.

#1570 Fix unused-lambda-capture warnings on clang
  examples/message_passing/fixed_stack.cpp
  libcaf_core/tests/legacy/dynamic_spawn.cpp
  libcaf_core/tests/legacy/message_lifetime.cpp
  libcaf_core/tests/legacy/typed_spawn.cpp
Labels: diagnostic

#1561 Add test for message_builder based on new framework
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/make_meta_object.hpp
  libcaf_core/caf/detail/meta_object.hpp
  libcaf_core/caf/message_builder.cpp
  libcaf_core/caf/message_builder.test.cpp
  libcaf_core/tests/legacy/message_builder.cpp
Labels: testing

#1563 Add tests for on_error_complete
  libcaf_core/caf/flow/observable.test.cpp
Labels: testing

#1574 Overload dump_content for examples
  examples/flow/iota.cpp
  examples/flow/observe-on.cpp
  examples/flow/spsc-buffer-resource.cpp
  examples/http/rest.cpp
  examples/http/time-server.cpp
  examples/length_prefix_framing/chat-client.cpp
  examples/length_prefix_framing/chat-server.cpp
  examples/remoting/remote_spawn.cpp
  examples/web_socket/echo.cpp
  examples/web_socket/quote-server.cpp
  examples/web_socket/stock-ticker.cpp
Labels: improvement

#1576 Fix clang-tidy related if statements with branch clone
  .clang-tidy
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/detail/glob_match.cpp
  libcaf_core/caf/detail/stringification_inspector.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/tests/legacy/settings.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: diagnostic

#1578 Fix clang-tidy related conversion warnings
  examples/qtsupport/chatwidget.cpp
  libcaf_core/caf/chrono.cpp
  libcaf_core/caf/detail/monotonic_buffer_resource.cpp
  libcaf_core/caf/hash/sha1.cpp
  libcaf_core/caf/json_reader.cpp
  libcaf_core/caf/string_algorithms.cpp
  libcaf_core/caf/telemetry/importer/process.cpp
  libcaf_io/caf/detail/prometheus_broker.cpp
  libcaf_net/caf/net/lp/framing.cpp
  libcaf_net/caf/net/octet_stream/transport.cpp
  libcaf_net/caf/net/octet_stream/transport.hpp
  libcaf_net/caf/net/web_socket/server.cpp
Labels: diagnostic

#1579 Fix clang-tidy related use after move warnings
  libcaf_core/caf/async/future.hpp
  libcaf_core/caf/detail/sync_ring_buffer.test.cpp
  libcaf_core/caf/intrusive/linked_list.test.cpp
  libcaf_core/tests/legacy/async/spsc_buffer.cpp
  libcaf_core/tests/legacy/cow_string.cpp
  libcaf_core/tests/legacy/cow_tuple.cpp
  libcaf_core/tests/legacy/detail/unique_function.cpp
  libcaf_core/tests/legacy/expected.cpp
  libcaf_core/tests/legacy/function_view.cpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_net/caf/net/http/server_factory.hpp
  libcaf_test/caf/test/block.cpp
Labels: diagnostic

#1580 Fix clang-tidy unchecked optional access
  libcaf_core/caf/detail/format.cpp
  libcaf_core/caf/expected.hpp
  libcaf_core/caf/inspector_access.hpp
  libcaf_net/caf/net/dsl/arg.hpp
Labels: diagnostic

#1577 Make to_stream available on observable
  CHANGELOG.md
  codecov.yml
  libcaf_core/caf/async/batch.hpp
  libcaf_core/caf/flow/coordinator.cpp
  libcaf_core/caf/flow/coordinator.hpp
  libcaf_core/caf/flow/fwd.hpp
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/scheduled_actor/flow.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/tests/legacy/stream.cpp
  libcaf_core/tests/legacy/typed_actor_view.cpp
  libcaf_core/tests/legacy/typed_stream.cpp
  robot/stream/driver.cpp
Labels: refactoring

#1581 Fix clang-tidy implicit move constructor
  libcaf_core/caf/catch_all.hpp
  libcaf_core/caf/others.hpp
  libcaf_core/caf/unit.hpp
  libcaf_core/tests/legacy/detail/parser/read_number.cpp
  libcaf_core/tests/legacy/detail/parser/read_number_or_timespan.cpp
Labels: diagnostic

#1582 Fix clang-tidy nits
  examples/remoting/remote_spawn.cpp
  libcaf_core/caf/async/promise.hpp
  libcaf_io/caf/io/abstract_broker.cpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: diagnostic

#1569 Add new header class for HTTP requests
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/http/header.cpp
  libcaf_net/caf/net/http/header.hpp
  libcaf_net/caf/net/http/header.test.cpp
  libcaf_net/caf/net/http/request_header.cpp
  libcaf_net/caf/net/http/request_header.hpp
  libcaf_net/caf/net/http/request_header.test.cpp
  libcaf_net/caf/net/http/response_header.cpp
  libcaf_net/caf/net/http/response_header.hpp
  libcaf_net/caf/net/http/response_header.test.cpp
Labels: refactoring

#1585 Add customization point for custom loggers
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/fwd.hpp
Labels: new feature

#1591 Fix heap-use-after-free with the testing mailbox
  CHANGELOG.md
  libcaf_core/caf/actor_control_block.hpp
  libcaf_core/caf/event_based_actor.test.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_test/caf/test/fixture/deterministic.cpp
Labels: bugfix, testing

#1592 Fix handling of system messages when using await
  CHANGELOG.md
  libcaf_core/caf/event_based_actor.test.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
Labels: bugfix

#1594 Fix compiler complaints on GCC 13 with C++23
  CHANGELOG.md
  CMakeLists.txt
  Jenkinsfile
  libcaf_core/caf/config_value_reader.cpp
  libcaf_core/caf/config_value_reader.hpp
  libcaf_core/caf/ipv6_address.cpp
  libcaf_core/caf/json_writer.cpp
  libcaf_core/tests/legacy/detail/format.cpp
  libcaf_core/tests/legacy/detail/meta_object.cpp
  libcaf_test/caf/test/runner.cpp
Labels: bugfix, diagnostic

#1595 Fix encoding of chunk size in HTTP response
  CHANGELOG.md
  libcaf_net/caf/net/http/server.cpp
  libcaf_net/tests/legacy/net/http/server.cpp
Labels: bugfix

#1604 Remove obsolete files
  libcaf_core/tests/legacy/intrusive/drr_cached_queue.cpp
  libcaf_core/tests/legacy/intrusive/drr_queue.cpp
  libcaf_core/tests/legacy/intrusive/fifo_inbox.cpp
  libcaf_core/tests/legacy/intrusive/lifo_inbox.cpp
  libcaf_core/tests/legacy/intrusive/task_queue.cpp
  libcaf_core/tests/legacy/intrusive/wdrr_dynamic_multiplexed_queue.cpp
  libcaf_core/tests/legacy/intrusive/wdrr_fixed_multiplexed_queue.cpp
Labels: refactoring

#1598 Fix leak when using spawn_inactive
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system.test.cpp
Labels: bugfix

#1606 Move logging driver to the Robot test folder
  libcaf_core/CMakeLists.txt
  robot/CMakeLists.txt
  robot/logging/driver.cpp
Labels: refactoring

#1586 Implement basic file I/O source interface
  CHANGELOG.md
  CMakeLists.txt
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/async/file.hpp
  libcaf_core/caf/async/file.test.cpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/flow/string.hpp
  libcaf_core/caf/flow/string.test.cpp
  libcaf_core/tests/data/quotes.txt
Labels: new feature

#1603 Modernize async and sha1 unit tests
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/async/blocking_consumer.test.cpp
  libcaf_core/caf/async/blocking_for_each.test.cpp
  libcaf_core/caf/async/blocking_producer.test.cpp
  libcaf_core/caf/async/consumer_adapter.test.cpp
  libcaf_core/caf/async/producer_adapter.test.cpp
  libcaf_core/caf/async/promise.test.cpp
  libcaf_core/caf/async/publisher.test.cpp
  libcaf_core/caf/async/spsc_buffer.hpp
  libcaf_core/caf/async/spsc_buffer.test.cpp
  libcaf_core/caf/detail/meta_object.test.cpp
  libcaf_core/caf/hash/sha1.test.cpp
  libcaf_core/tests/legacy/hash/sha1.cpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
  libcaf_test/caf/test/fixture/flow.hpp
  libcaf_test/caf/test/outline.hpp
  libcaf_test/caf/test/runnable.hpp
Labels: testing

#1608 Modernize telemetry unit tests
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/telemetry/collector/prometheus.test.cpp
  libcaf_core/caf/telemetry/counter.hpp
  libcaf_core/caf/telemetry/counter.test.cpp
  libcaf_core/caf/telemetry/gauge.test.cpp
  libcaf_core/caf/telemetry/histogram.test.cpp
  libcaf_core/caf/telemetry/int_gauge.hpp
  libcaf_core/caf/telemetry/label.test.cpp
  libcaf_core/caf/telemetry/metric_registry.test.cpp
  libcaf_core/caf/telemetry/timer.test.cpp
  libcaf_core/tests/legacy/telemetry/counter.cpp
  libcaf_core/tests/legacy/telemetry/gauge.cpp
  libcaf_core/tests/legacy/telemetry/histogram.cpp
  libcaf_core/tests/legacy/telemetry/label.cpp
  libcaf_core/tests/legacy/telemetry/timer.cpp
Labels: testing

#1612 Refactor the logger interface
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/exec_main.hpp
  libcaf_core/caf/logger.cpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/scheduler/test_coordinator.cpp
  libcaf_core/tests/legacy/logger.cpp
  libcaf_io/caf/io/network/default_multiplexer.cpp
  libcaf_net/caf/net/tcp_stream_socket.cpp
  robot/logging/driver.cpp
  robot/logging/output.robot
Labels: refactoring

#1614 Fix type-ids check in load_data for Message
  libcaf_core/caf/detail/type_id_list_builder.cpp
  libcaf_core/caf/detail/type_id_list_builder.hpp
  libcaf_core/caf/message.cpp
Labels: bugfix

#1615 Clean up type ID list builder capacity management
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/type_id_list_builder.cpp
  libcaf_core/caf/detail/type_id_list_builder.hpp
  libcaf_core/caf/detail/type_id_list_builder.test.cpp
  libcaf_core/caf/message.cpp
  libcaf_core/caf/type_id_list.cpp
Labels: refactoring

#1617 Add .readthedocs.yaml config file
  .readthedocs.yaml
Labels: documentation

#1607 Add new flow on_error_return with tests
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable.test.cpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/step/all.hpp
  libcaf_core/caf/flow/step/fwd.hpp
  libcaf_core/caf/flow/step/on_error_return.hpp
Labels: new feature

#1618 Add missing const to publisher<T>::observe_on
  CHANGELOG.md
  libcaf_core/caf/async/publisher.hpp
Labels: bugfix

#1621 Use short names for CAF enums
  CHANGELOG.md
  cmake/caf-generate-enum-strings.cmake
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/sec.test.cpp
  libcaf_core/tests/legacy/error.cpp
Labels: refactoring

#1622 Improve test coverage and remove dead code
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/io/basp/connection_state.hpp
  libcaf_io/caf/io/basp/connection_state.test.cpp
  libcaf_io/caf/io/basp/header.cpp
  libcaf_io/caf/io/basp/header.hpp
  libcaf_io/caf/io/basp/header.test.cpp
  libcaf_io/caf/io/basp/message_queue.test.cpp
  libcaf_io/caf/io/system_messages.test.cpp
  libcaf_io/tests/legacy/io/basp/message_queue.cpp
Labels: testing

#1619 Add scan flow and tests for reduce
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable.test.cpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/step/all.hpp
  libcaf_core/caf/flow/step/fwd.hpp
  libcaf_core/caf/flow/step/scan.hpp
Labels: new feature

#1572 Improve performance of the mcast operator
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/flow/gen/from_callable.hpp
  libcaf_core/caf/flow/multicaster.hpp
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_builder.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/op/from_generator.hpp
  libcaf_core/caf/flow/op/from_steps.hpp
  libcaf_core/caf/flow/op/mcast.hpp
  libcaf_core/caf/flow/op/mcast.test.cpp
  libcaf_core/caf/flow/op/merge.hpp
  libcaf_core/caf/flow/op/prefix_and_tail.hpp
  libcaf_core/caf/flow/op/publish.hpp
  libcaf_core/caf/flow/op/pullable.cpp
  libcaf_core/caf/flow/op/pullable.hpp
  libcaf_core/caf/flow/op/ucast.hpp
  libcaf_core/caf/flow/scoped_coordinator.cpp
  libcaf_core/tests/legacy/flow/multicaster.cpp
  libcaf_core/tests/legacy/flow/op/buffer.cpp
  libcaf_core/tests/legacy/flow/op/merge.cpp
  libcaf_test/caf/test/fixture/flow.cpp
  libcaf_test/caf/test/fixture/flow.hpp
  robot/CMakeLists.txt
  robot/flow/merge/driver.cpp
  robot/flow/merge/merge.robot
Labels: performance

#1627 Fix observable tests
  libcaf_core/caf/flow/observable.test.cpp
Labels: testing

#1623 Fix parameter name in Doxygen documentation
  libcaf_core/caf/flow/observable_decl.hpp
Labels: documentation

#1628 Fix subscribe implementations that emit errors
  CHANGELOG.md
  libcaf_core/caf/detail/stream_bridge.cpp
  libcaf_core/caf/flow/observable.test.cpp
  libcaf_core/caf/flow/observer.hpp
  libcaf_core/caf/flow/op/buffer.hpp
  libcaf_core/caf/flow/op/concat.hpp
  libcaf_core/caf/flow/op/empty.hpp
  libcaf_core/caf/flow/op/fail.hpp
  libcaf_core/caf/flow/op/from_resource.hpp
  libcaf_core/caf/flow/op/from_steps.hpp
  libcaf_core/caf/flow/op/mcast.hpp
  libcaf_core/caf/flow/op/prefix_and_tail.hpp
  libcaf_core/caf/flow/op/ucast.hpp
  libcaf_core/caf/flow/subscription.cpp
  libcaf_core/caf/flow/subscription.hpp
  libcaf_core/tests/legacy/flow/op/concat.cpp
  libcaf_test/caf/test/fixture/flow.hpp
Labels: bugfix

#1633 Add tests for do_finally
  libcaf_core/caf/flow/observable.test.cpp
Labels: testing

#1630 Avoid using scope guards for parser results
  libcaf_core/caf/detail/parser/fsm.hpp
  libcaf_core/caf/detail/parser/read_bool.hpp
  libcaf_core/caf/detail/parser/read_config.hpp
  libcaf_core/caf/detail/parser/read_floating_point.hpp
  libcaf_core/caf/detail/parser/read_ipv4_address.hpp
  libcaf_core/caf/detail/parser/read_ipv6_address.hpp
  libcaf_core/caf/detail/parser/read_number.hpp
  libcaf_core/caf/detail/parser/read_number_or_timespan.hpp
  libcaf_core/caf/detail/parser/read_signed_integer.hpp
  libcaf_core/caf/detail/parser/read_string.hpp
  libcaf_core/caf/detail/parser/read_timespan.hpp
  libcaf_core/caf/detail/parser/read_timestamp.hpp
  libcaf_core/caf/detail/parser/read_unsigned_integer.hpp
  libcaf_core/caf/detail/parser/read_uri.hpp
Labels: refactoring
