Repository actor-framework/actor-framework, pull requests merged in 2023-09, with the labels that each got.

#1525 Fail early on invalid UTF-8 WebSocket text frames
  libcaf_net/caf/detail/rfc6455.cpp
  libcaf_net/caf/detail/rfc6455.hpp
  libcaf_net/caf/detail/rfc6455.test.cpp
  libcaf_net/caf/net/web_socket/framing.cpp
  libcaf_net/caf/net/web_socket/framing.hpp
  libcaf_net/tests/legacy/net/web_socket/framing.cpp
Labels: improvement

#1529 Add autobahn-testsuite docker image to Jenkins
  .ci/autobahn-testsuite/Dockerfile
  .ci/autobahn-testsuite/run.sh
  Jenkinsfile
Labels: testing, pipeline

#1552 Integrate ostream output into deterministic tests
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_ostream.cpp
  libcaf_core/caf/actor_ostream.hpp
  libcaf_core/caf/detail/actor_local_printer.cpp
  libcaf_core/caf/detail/actor_local_printer.hpp
  libcaf_core/caf/event_based_actor.test.cpp
  libcaf_core/caf/scheduler/abstract_coordinator.cpp
  libcaf_core/caf/scheduler/abstract_coordinator.hpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/reporter.hpp
Labels: testing

#1547 Add delegate tests with deterministic fixture
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/delegate.test.cpp
Labels: testing

#1553 Add additional tests for event_based_actor
  libcaf_core/caf/event_based_actor.test.cpp
Labels: testing

#1558 Bring back coverage batch
  README.md
Labels: improvement

#1559 Allow passing catch-all handlers to behaviors
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/behavior.test.cpp
  libcaf_core/caf/detail/behavior_impl.hpp
  libcaf_core/tests/legacy/behavior.cpp
Labels: new feature

#1548 Fix function object lifetimes in actions
  CHANGELOG.md
  libcaf_core/caf/action.hpp
  libcaf_core/caf/action.test.cpp
  libcaf_core/tests/legacy/mixin/requester.cpp
Labels: bugfix

#1560 Add case insensitive compare to request header
  CHANGELOG.md
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/http/request_header.cpp
  libcaf_net/caf/net/http/request_header.hpp
  libcaf_net/caf/net/http/request_header.test.cpp
Labels: bugfix

#1564 Verify type IDs when creating messages
  CHANGELOG.md
  libcaf_core/caf/detail/message_data.cpp
Labels: diagnostic

#1549 Refactor logger to be an interface
  .ci/windows/build.cmd
  .github/workflows/codecov.yml
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/logger.cpp
  libcaf_core/caf/logger.hpp
  libcaf_core/tests/integration/logging.cpp
  libcaf_core/tests/legacy/logger.cpp
  robot/CMakeLists.txt
  robot/logging/base.cfg
  robot/logging/output.robot
Labels: refactoring

#1562 Add tests for actor_companion
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_companion.test.cpp
Labels: testing
