Repository actor-framework/actor-framework, pull requests merged in 2023-12, with the labels that each got.

#1678 Properly terminate test drivers on SIGTERM
  CHANGELOG.md
  examples/http/rest.cpp
  examples/web_socket/echo.cpp
  examples/web_socket/quote-server.cpp
  libcaf_net/caf/detail/accept_handler.hpp
  robot/http/client-driver.cpp
  robot/middleman/driver.cpp
  robot/stream/driver.cpp
Labels: bugfix, pipeline

#1679 Relax assertion in telemetry::counter::inc
  CHANGELOG.md
  libcaf_core/caf/telemetry/counter.hpp
Labels: refactoring

#1670 Add HTTP Client DSL
  CHANGELOG.md
  examples/CMakeLists.txt
  examples/http/client.cpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/byte_span.cpp
  libcaf_core/caf/byte_span.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/expected.hpp
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/dsl/client_config.hpp
  libcaf_net/caf/net/dsl/client_factory_base.hpp
  libcaf_net/caf/net/dsl/config_base.hpp
  libcaf_net/caf/net/dsl/generic_config.hpp
  libcaf_net/caf/net/dsl/has_accept.hpp
  libcaf_net/caf/net/dsl/has_context.hpp
  libcaf_net/caf/net/dsl/has_ctx.hpp
  libcaf_net/caf/net/dsl/has_lazy_context.hpp
  libcaf_net/caf/net/dsl/has_make_ctx.hpp
  libcaf_net/caf/net/dsl/has_uri_connect.hpp
  libcaf_net/caf/net/dsl/server_config.hpp
  libcaf_net/caf/net/dsl/server_factory_base.hpp
  libcaf_net/caf/net/http/async_client.cpp
  libcaf_net/caf/net/http/async_client.hpp
  libcaf_net/caf/net/http/client_factory.cpp
  libcaf_net/caf/net/http/client_factory.hpp
  libcaf_net/caf/net/http/config.hpp
  libcaf_net/caf/net/http/server_factory.hpp
  libcaf_net/caf/net/http/with.hpp
  libcaf_net/caf/net/lp/client_factory.hpp
  libcaf_net/caf/net/lp/config.hpp
  libcaf_net/caf/net/lp/server_factory.hpp
  libcaf_net/caf/net/ssl/context.hpp
  libcaf_net/caf/net/ssl/tcp_acceptor.hpp
  libcaf_net/caf/net/tcp_stream_socket.cpp
  libcaf_net/caf/net/tcp_stream_socket.hpp
  libcaf_net/caf/net/web_socket/client_factory.hpp
  libcaf_net/caf/net/web_socket/config.hpp
  libcaf_net/caf/net/web_socket/server_factory.hpp
  libcaf_net/caf/net/web_socket/with.hpp
  robot/CMakeLists.txt
  robot/http/client-driver.cpp
  robot/http/client.robot
Labels: new feature

#1680 Fix memory leaks in prefix_and_tail suite
  libcaf_core/tests/legacy/flow/op/prefix_and_tail.cpp
Labels: testing

#1677 Implement caf::chunk
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/chunk.cpp
  libcaf_core/caf/chunk.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/lp/frame.cpp
  libcaf_net/caf/net/lp/frame.hpp
  libcaf_net/caf/net/web_socket/frame.cpp
  libcaf_net/caf/net/web_socket/frame.hpp
Labels: new feature

#1686 Implement asynchronous, binary file I/O
  CHANGELOG.md
  libcaf_core/caf/async/file.hpp
  libcaf_core/caf/async/file.test.cpp
  libcaf_core/caf/flow/byte.hpp
  libcaf_core/caf/flow/string.hpp
  libcaf_core/tests/data/range.bin
Labels: new feature

#1687 Fix UB in actor clock action decorator
  libcaf_core/caf/actor_clock.cpp
Labels: bugfix

#1688 Add new chunked_string type
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/chunked_string.cpp
  libcaf_core/caf/chunked_string.hpp
  libcaf_core/caf/chunked_string.test.cpp
  libcaf_core/caf/detail/format.cpp
  libcaf_core/caf/detail/format.hpp
  libcaf_core/caf/detail/print.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/fwd.hpp
Labels: new feature

#1691 Fix copy-paste error
  libcaf_net/caf/net/web_socket/config.hpp
Labels: documentation

#1693 Simplify implementation of chunked_string
  libcaf_core/caf/chunked_string.cpp
  libcaf_core/caf/chunked_string.hpp
  libcaf_core/caf/chunked_string.test.cpp
  libcaf_core/caf/detail/json.hpp
  libcaf_core/caf/fwd.hpp
Labels: refactoring

#1689 Increase Prometheus coverage
  robot/http/rest.robot
Labels: testing

#1694 Implement new log event type for logging
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/chunked_string.cpp
  libcaf_core/caf/chunked_string.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/log_event.cpp
  libcaf_core/caf/log_event.hpp
  libcaf_core/caf/log_event.test.cpp
Labels: new feature

#1695 Add new logging API for events with custom fields
  libcaf_core/caf/chunked_string.cpp
  libcaf_core/caf/chunked_string.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/log_event.cpp
  libcaf_core/caf/log_event.hpp
  libcaf_core/caf/log_event.test.cpp
  libcaf_core/caf/logger.cpp
  libcaf_core/caf/logger.hpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/reporter.hpp
  libcaf_test/caf/test/runner.cpp
  robot/logging/driver.cpp
  robot/logging/output.robot
Labels: new feature

#1697 Allow passing inspectable types to detail::format
  libcaf_core/caf/detail/format.hpp
  robot/logging/driver.cpp
  robot/logging/output.robot
Labels: new feature

#1676 Port flow tests to the updated tests framework
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/flow/concat_map.test.cpp
  libcaf_core/caf/flow/flat_map.test.cpp
  libcaf_core/caf/flow/for_each.test.cpp
  libcaf_core/caf/flow/generation.test.cpp
  libcaf_core/caf/flow/mixed.test.cpp
  libcaf_core/caf/flow/multicaster.test.cpp
  libcaf_core/caf/flow/observe_on.test.cpp
  libcaf_core/caf/flow/op/publish.test.cpp
  libcaf_core/caf/flow/scoped_coordinator.cpp
  libcaf_core/caf/flow/scoped_coordinator.hpp
  libcaf_core/caf/flow/single.test.cpp
  libcaf_core/tests/legacy/flow/multicaster.cpp
  libcaf_core/tests/legacy/flow/publish.cpp
  libcaf_core/tests/legacy/flow/single.cpp
  libcaf_test/caf/test/fixture/flow.cpp
  libcaf_test/caf/test/fixture/flow.hpp
Labels: testing

#1698 Restructure the logging API
  CHANGELOG.md
  CMakeLists.txt
  cmake/log.hpp.in
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/chrono.test.cpp
  libcaf_core/caf/config_option.test.cpp
  libcaf_core/caf/detail/config_consumer.test.cpp
  libcaf_core/caf/detail/log_level_map.cpp
  libcaf_core/caf/detail/log_level_map.test.cpp
  libcaf_core/caf/detail/meta_object.test.cpp
  libcaf_core/caf/detail/monotonic_buffer_resource.test.cpp
  libcaf_core/caf/detail/parser/read_config.test.cpp
  libcaf_core/caf/detail/ring_buffer.test.cpp
  libcaf_core/caf/detail/stream_bridge.cpp
  libcaf_core/caf/flow/op/buffer.test.cpp
  libcaf_core/caf/flow/op/from_resource.hpp
  libcaf_core/caf/flow/op/mcast.test.cpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/log/event.cpp
  libcaf_core/caf/log/event.hpp
  libcaf_core/caf/log/event.test.cpp
  libcaf_core/caf/log/level.hpp
  libcaf_core/caf/logger.cpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/message.cpp
  libcaf_core/caf/message.hpp
  libcaf_core/caf/message_builder.test.cpp
  libcaf_core/caf/node_id.cpp
  libcaf_core/caf/raise_error.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scoped_actor.cpp
  libcaf_core/caf/stream.test.cpp
  libcaf_core/caf/telemetry/collector/prometheus.test.cpp
  libcaf_core/caf/telemetry/importer/process.cpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/network/default_multiplexer.cpp
  libcaf_io/caf/io/network/ip_endpoint.cpp
  libcaf_net/caf/net/lp/default_trait.cpp
  libcaf_net/caf/net/middleman.cpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_net/caf/net/web_socket/default_trait.cpp
  libcaf_openssl/caf/openssl/middleman_actor.cpp
  libcaf_openssl/caf/openssl/session.cpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/outline.test.cpp
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/reporter.hpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/runner.cpp
  libcaf_test/caf/test/test.test.cpp
  robot/logging/base.cfg
  robot/logging/driver.cpp
Labels: refactoring

#1700 Small cleanup of transport layer
  libcaf_net/caf/net/octet_stream/transport.cpp
  libcaf_net/caf/net/octet_stream/transport.hpp
Labels: refactoring

#1696 Port remaining op flow tests to new framework
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/flow/op/cell.test.cpp
  libcaf_core/caf/flow/op/defer.test.cpp
  libcaf_core/caf/flow/op/empty.test.cpp
  libcaf_core/caf/flow/op/fail.test.cpp
  libcaf_core/caf/flow/op/interval.test.cpp
  libcaf_core/caf/flow/op/merge.test.cpp
  libcaf_core/caf/flow/op/never.test.cpp
  libcaf_core/caf/flow/op/prefix_and_tail.test.cpp
  libcaf_core/caf/flow/op/ucast.test.cpp
  libcaf_core/caf/flow/op/zip_with.test.cpp
  libcaf_core/tests/legacy/flow/op/buffer.cpp
  libcaf_core/tests/legacy/flow/op/concat.cpp
  libcaf_core/tests/legacy/flow/op/defer.cpp
  libcaf_core/tests/legacy/flow/op/empty.cpp
  libcaf_core/tests/legacy/flow/op/fail.cpp
  libcaf_core/tests/legacy/flow/op/merge.cpp
  libcaf_core/tests/legacy/flow/op/never.cpp
  libcaf_core/tests/legacy/flow/op/zip_with.cpp
  libcaf_test/caf/test/fixture/flow.hpp
Labels: testing
