Repository actor-framework/actor-framework, pull requests merged in 2023-11, with the labels that each got.

#1624 Replace caf_io unit tests with Robot tests
  .github/workflows/codecov.yml
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/io/all.hpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman_actor_impl.cpp
  libcaf_io/caf/io/network/default_multiplexer.cpp
  libcaf_io/caf/io/network/ip_endpoint.cpp
  libcaf_io/caf/io/network/ip_endpoint.hpp
  libcaf_io/caf/io/network/ip_endpoint.test.cpp
  libcaf_io/caf/io/network/protocol.hpp
  libcaf_io/caf/io/network/protocol.test.cpp
  libcaf_io/caf/io/network/test_multiplexer.cpp
  libcaf_io/caf/io/network/test_multiplexer.hpp
  libcaf_io/tests/legacy/detail/prometheus_broker.cpp
  libcaf_io/tests/legacy/io-test.cpp
  libcaf_io/tests/legacy/io-test.hpp
  libcaf_io/tests/legacy/io/basp_broker.cpp
  libcaf_io/tests/legacy/io/broker.cpp
  libcaf_io/tests/legacy/io/http_broker.cpp
  libcaf_io/tests/legacy/io/middleman.cpp
  libcaf_io/tests/legacy/io/monitor.cpp
  libcaf_io/tests/legacy/io/network/default_multiplexer.cpp
  libcaf_io/tests/legacy/io/network/ip_endpoint.cpp
  libcaf_io/tests/legacy/io/remote_actor.cpp
  libcaf_io/tests/legacy/io/remote_group.cpp
  libcaf_io/tests/legacy/io/remote_spawn.cpp
  libcaf_io/tests/legacy/io/unpublish.cpp
  libcaf_io/tests/legacy/io/worker.cpp
  libcaf_test/caf/test/io_dsl.hpp
  robot/CMakeLists.txt
  robot/middleman/driver.cpp
  robot/middleman/middleman.robot
Labels: testing

#1637 Allow checking for custom logger factories
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/actor_system_config.hpp
Labels: new feature

#1636 Simplify interface of detail::sync_ring_buffer
  libcaf_core/caf/detail/sync_ring_buffer.hpp
  libcaf_core/caf/detail/sync_ring_buffer.test.cpp
  libcaf_core/caf/detail/thread_safe_actor_clock.cpp
  libcaf_core/caf/detail/thread_safe_actor_clock.hpp
  libcaf_core/caf/logger.cpp
Labels: refactoring

#1638 Make exec_main utils more generic
  libcaf_core/caf/exec_main.hpp
Labels: refactoring

#1639 Fix handling of whitespaces in config_value::parse
  CHANGELOG.md
  libcaf_core/caf/config_value.cpp
  libcaf_core/tests/legacy/config_value.cpp
Labels: bugfix

#1625 Restrict scope guard to noexcept functions
  examples/qtsupport/chatwidget.cpp
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/config_value.cpp
  libcaf_core/caf/detail/config_consumer.cpp
  libcaf_core/caf/detail/format.cpp
  libcaf_core/caf/detail/json.cpp
  libcaf_core/caf/detail/scope_guard.hpp
  libcaf_core/caf/execution_unit.hpp
  libcaf_core/caf/flow/op/from_resource.hpp
  libcaf_core/caf/flow/op/from_steps.hpp
  libcaf_core/caf/logger.cpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/tests/legacy/dsl.cpp
  libcaf_io/caf/io/basp/remote_message_handler.hpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/broker_servant.hpp
  libcaf_io/caf/io/network/native_socket.cpp
  libcaf_net/caf/net/dsl/arg.hpp
  libcaf_net/caf/net/dsl/config_base.hpp
  libcaf_net/caf/net/pipe_socket.cpp
  libcaf_net/caf/net/stream_socket.cpp
  libcaf_net/tests/legacy/net/ssl/transport.cpp
  libcaf_openssl/caf/openssl/session.cpp
  libcaf_test/caf/test/outline.cpp
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/reporter.hpp
  libcaf_test/caf/test/runnable.cpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/unit_test.hpp
Labels: diagnostic

#1635 Fix unordered_flat_map equals, add missing methods
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/unordered_flat_map.hpp
  libcaf_core/caf/unordered_flat_map.test.cpp
  libcaf_core/tests/legacy/unordered_flat_map.cpp
Labels: bugfix, new feature

#1641 Get rid of make_scope_guard
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/config_value.cpp
  libcaf_core/caf/detail/scope_guard.hpp
  libcaf_core/caf/flow/op/from_steps.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/tests/legacy/dsl.cpp
  libcaf_io/caf/io/basp/remote_message_handler.hpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/broker_servant.hpp
  libcaf_io/caf/io/network/native_socket.cpp
  libcaf_net/caf/net/pipe_socket.cpp
  libcaf_net/caf/net/stream_socket.cpp
  libcaf_net/tests/legacy/net/ssl/transport.cpp
  libcaf_openssl/caf/openssl/session.cpp
  libcaf_test/caf/test/outline.cpp
  libcaf_test/caf/test/runnable.cpp
Labels: refactoring

#1640 Move legacy test code out of the core module
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/detail/mailbox_factory.test.cpp
  libcaf_core/caf/detail/test_actor_clock.cpp
  libcaf_core/caf/detail/test_actor_clock.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/scheduler/test_coordinator.cpp
  libcaf_core/caf/scheduler/test_coordinator.hpp
  libcaf_core/tests/legacy/actor_clock.cpp
  libcaf_core/tests/legacy/actor_lifetime.cpp
  libcaf_core/tests/legacy/actor_profiler.cpp
  libcaf_core/tests/legacy/tracing_data.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: testing

#1642 Remove caf.middleman.manual-multiplexing option
  examples/caf-application.conf
  libcaf_io/caf/io/middleman.cpp
  libcaf_net/caf/net/middleman.cpp
  libcaf_openssl/CMakeLists.txt
  libcaf_openssl/tests/legacy/ca.pem
  libcaf_openssl/tests/legacy/cert.1.pem
  libcaf_openssl/tests/legacy/cert.2.pem
  libcaf_openssl/tests/legacy/key.1.enc.pem
  libcaf_openssl/tests/legacy/key.1.pem
  libcaf_openssl/tests/legacy/key.2.pem
  libcaf_openssl/tests/legacy/openssl-test.cpp
  libcaf_openssl/tests/legacy/openssl-test.hpp
  libcaf_openssl/tests/legacy/openssl/authentication.cpp
  libcaf_openssl/tests/legacy/openssl/remote_actor.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: testing

#1645 Remove dead code
  libcaf_core/caf/detail/serialized_size.cpp
  libcaf_core/caf/detail/serialized_size.test.cpp
  libcaf_core/tests/legacy/byte.cpp
Labels: refactoring

#1643 Support config via environment variable
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/config_option.cpp
  libcaf_core/caf/config_option.hpp
  libcaf_core/caf/config_option.test.cpp
  libcaf_core/caf/config_value_writer.cpp
  libcaf_core/caf/make_config_option.hpp
  libcaf_core/tests/legacy/config_option.cpp
  libcaf_core/tests/legacy/config_value.cpp
  robot/CMakeLists.txt
  robot/config/options-driver.cpp
  robot/config/options-test1.cfg
  robot/config/options-test2.cfg
  robot/config/options-test3.cfg
  robot/config/options-test4.cfg
  robot/config/options.robot
Labels: bugfix, new feature

#1648 Fix parsing of configs with dot-separated keys
  CHANGELOG.md
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/detail/parser/read_config.hpp
  robot/config/options-test5.cfg
  robot/config/options.robot
Labels: bugfix

#1650 Make term inspectable and usable with FILE handles
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/term.cpp
  libcaf_core/caf/term.hpp
Labels: refactoring

#1649 Run robot tests in pipeline
  .ci/almalinux-8/Dockerfile
  .ci/almalinux-9/Dockerfile
  .ci/alpinelinux-3.18/Dockerfile
  .ci/centos-7/Dockerfile
  .ci/debian-10/Dockerfile
  .ci/debian-11/Dockerfile
  .ci/debug-flags.cmake
  .ci/fedora-37/Dockerfile
  .ci/fedora-38/Dockerfile
  .ci/freebsd-12/prepare.sh
  .ci/freebsd-13/prepare.sh
  .ci/ubuntu-20.04/Dockerfile
  .ci/ubuntu-22.04/Dockerfile
  .ci/windows/Dockerfile
  .github/workflows/check-windows.yml
  Jenkinsfile
Labels: pipeline

#1647 Add HTTP client robot tests
  .github/workflows/codecov.yml
  robot/CMakeLists.txt
  robot/dependencies.txt
  robot/http/client-driver.cpp
  robot/http/client.robot
Labels: testing

#1653 Stop using '%C' in logs; document current behavior
  CHANGELOG.md
  examples/caf-application.conf
  libcaf_core/caf/defaults.hpp
  manual/ConfiguringActorApplications.rst
Labels: refactoring, documentation

#1651 Streamline logging and reporting APIs
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/format.hpp
  libcaf_core/caf/detail/log_level_map.cpp
  libcaf_core/caf/detail/log_level_map.hpp
  libcaf_core/caf/detail/log_level_map.test.cpp
  libcaf_core/caf/format_string_with_location.hpp
  libcaf_core/caf/logger.cpp
  libcaf_core/caf/logger.hpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/reporter.hpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/runner.cpp
Labels: refactoring

#1658 Fix shutdown for actors with open streams
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_clock.cpp
  libcaf_core/caf/detail/stream_bridge.cpp
  libcaf_core/caf/flow/op/interval.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/sec.hpp
  libcaf_core/caf/send.hpp
  libcaf_core/caf/stream.test.cpp
  libcaf_core/tests/legacy/stream.cpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
Labels: bugfix

#1655 Limit request size in HTTP high level API
  examples/http/rest.cpp
  libcaf_core/caf/defaults.hpp
  libcaf_net/caf/net/http/config.hpp
  libcaf_net/caf/net/http/server.hpp
  libcaf_net/caf/net/http/server_factory.hpp
  robot/http/rest.robot
Labels: new feature

#1662 Tweak Codecov configuration
  .github/workflows/codecov.yml
  codecov.yml
Labels: pipeline

#1661 Minor tweaks
  libcaf_net/caf/net/web_socket/server_factory.hpp
  robot/http/client.robot
Labels: refactoring

#1659 Add fix to dispose subscription on error for merge
  libcaf_core/caf/flow/op/merge.hpp
  libcaf_core/tests/legacy/flow/op/merge.cpp
Labels: bugfix

#1664 Bump versions in GH action for clang-format
  .github/workflows/check-formatting.yml
  libcaf_core/caf/expected.hpp
  libcaf_core/caf/optional.hpp
Labels: pipeline

#1656 Make precision of chrono formatters configurable
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/chrono.cpp
  libcaf_core/caf/chrono.hpp
  libcaf_core/caf/chrono.test.cpp
  libcaf_core/caf/detail/print.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/logger.cpp
  libcaf_core/tests/legacy/chrono.cpp
Labels: new feature

#1666 Re-implement the concat operator
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_builder.hpp
  libcaf_core/caf/flow/op/concat.hpp
  libcaf_core/caf/flow/op/concat.test.cpp
  libcaf_core/caf/flow/op/from_steps.hpp
  libcaf_core/caf/flow/op/merge.hpp
  libcaf_core/caf/flow/op/prefix_and_tail.hpp
  libcaf_core/tests/legacy/flow/op/concat.cpp
  libcaf_core/tests/legacy/flow/op/prefix_and_tail.cpp
  libcaf_test/caf/test/fixture/flow.hpp
Labels: bugfix

#1668 Fix Robot merge driver; remove obsolete code
  robot/flow/merge/driver.cpp
Labels: testing

#1634 Add start_with step for observables
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable.test.cpp
  libcaf_core/caf/flow/observable_decl.hpp
Labels: new feature
