Repository actor-framework/actor-framework, pull requests merged in 2023-08, with the labels that each got.

#1503 Add check for all binary predicates
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/test.test.cpp
Labels: testing

#1512 Some clang tidy fixes
  .clang-tidy
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/flow/op/concat.hpp
  libcaf_core/caf/policy/select_all.hpp
Labels: diagnostic

#1511 Make actor mailboxes configurable
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/abstract_mailbox.cpp
  libcaf_core/caf/abstract_mailbox.hpp
  libcaf_core/caf/actor_config.hpp
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/detail/default_mailbox.cpp
  libcaf_core/caf/detail/default_mailbox.hpp
  libcaf_core/caf/detail/default_mailbox.test.cpp
  libcaf_core/caf/detail/mailbox_factory.cpp
  libcaf_core/caf/detail/mailbox_factory.hpp
  libcaf_core/caf/detail/mailbox_factory.test.cpp
  libcaf_core/caf/detail/sync_request_bouncer.cpp
  libcaf_core/caf/detail/sync_request_bouncer.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/detail/unique_function.hpp
  libcaf_core/caf/flow/op/zip_with.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/intrusive/drr_cached_queue.hpp
  libcaf_core/caf/intrusive/drr_queue.hpp
  libcaf_core/caf/intrusive/fifo_inbox.hpp
  libcaf_core/caf/intrusive/lifo_inbox.hpp
  libcaf_core/caf/intrusive/lifo_inbox.test.cpp
  libcaf_core/caf/intrusive/linked_list.hpp
  libcaf_core/caf/intrusive/linked_list.test.cpp
  libcaf_core/caf/intrusive/new_round_result.hpp
  libcaf_core/caf/intrusive/singly_linked.hpp
  libcaf_core/caf/intrusive/stack.hpp
  libcaf_core/caf/intrusive/stack.test.cpp
  libcaf_core/caf/intrusive/task_queue.hpp
  libcaf_core/caf/intrusive/task_result.hpp
  libcaf_core/caf/intrusive/wdrr_dynamic_multiplexed_queue.hpp
  libcaf_core/caf/intrusive/wdrr_fixed_multiplexed_queue.hpp
  libcaf_core/caf/logger.cpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/policy/categorized.hpp
  libcaf_core/caf/policy/normal_messages.hpp
  libcaf_core/caf/policy/urgent_messages.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/scheduler/test_coordinator.hpp
  libcaf_core/test/intrusive/drr_cached_queue.cpp
  libcaf_core/test/intrusive/drr_queue.cpp
  libcaf_core/test/intrusive/fifo_inbox.cpp
  libcaf_core/test/intrusive/lifo_inbox.cpp
  libcaf_core/test/intrusive/task_queue.cpp
  libcaf_core/test/intrusive/wdrr_dynamic_multiplexed_queue.cpp
  libcaf_core/test/intrusive/wdrr_fixed_multiplexed_queue.cpp
  libcaf_core/test/policy/categorized.cpp
  libcaf_net/caf/net/abstract_actor_shell.cpp
  libcaf_net/caf/net/abstract_actor_shell.hpp
Labels: new feature

#1504 Add take last flow for observables
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/ring_buffer.hpp
  libcaf_core/caf/detail/ring_buffer.test.cpp
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/step/all.hpp
  libcaf_core/caf/flow/step/fwd.hpp
  libcaf_core/caf/flow/step/take_last.hpp
  libcaf_core/caf/flow/step/take_last.test.cpp
Labels: new feature

#1516 Add skip_last step for observables
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/step/all.hpp
  libcaf_core/caf/flow/step/fwd.hpp
  libcaf_core/caf/flow/step/skip_last.hpp
  libcaf_core/caf/flow/step/skip_last.test.cpp
Labels: new feature

#1513 Update the README of the test framework
  libcaf_test/README.md
Labels: documentation

#1517 Add example for caf::after
  examples/CMakeLists.txt
  examples/message_passing/after.cpp
Labels: documentation

#1520 Implement new fixture for flow tests
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/flow/observable.test.cpp
  libcaf_core/caf/flow/step/take.hpp
  libcaf_test/CMakeLists.txt
  libcaf_test/caf/test/fixture/flow.cpp
  libcaf_test/caf/test/fixture/flow.hpp
  libcaf_test/caf/test/fixture/flow.test.cpp
  libcaf_test/caf/test/nil.hpp
Labels: bugfix, testing

#1518 Implement new fixture for deterministic testing
  CHANGELOG.md
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/intrusive_ptr.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_test/CMakeLists.txt
  libcaf_test/caf/test/context.cpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
  libcaf_test/caf/test/fixture/deterministic.test.cpp
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/reporter.hpp
  libcaf_test/caf/test/runnable.cpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/runner.cpp
  libcaf_test/caf/test/test.test.cpp
Labels: bugfix, testing

#1524 Add autobahn driver
  CMakeLists.txt
  codecov.yml
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/web_socket/server_factory.hpp
  libcaf_net/tests/drivers/autobahn.cpp
Labels: testing

#1521 refactor $pred::value to $pred_v
  libcaf_core/caf/actor_cast.hpp
  libcaf_core/caf/actor_factory.hpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_traits.hpp
  libcaf_core/caf/binary_deserializer.hpp
  libcaf_core/caf/binary_serializer.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/byte.hpp
  libcaf_core/caf/catch_all.hpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/config_value_reader.cpp
  libcaf_core/caf/deduce_mpi.hpp
  libcaf_core/caf/deserializer.hpp
  libcaf_core/caf/detail/implicit_conversions.hpp
  libcaf_core/caf/detail/init_fun_factory.hpp
  libcaf_core/caf/detail/parse.hpp
  libcaf_core/caf/detail/parser/read_signed_integer.hpp
  libcaf_core/caf/detail/parser/read_unsigned_integer.hpp
  libcaf_core/caf/detail/print.hpp
  libcaf_core/caf/detail/spawn_fwd.hpp
  libcaf_core/caf/detail/squashed_int.hpp
  libcaf_core/caf/detail/stringification_inspector.hpp
  libcaf_core/caf/detail/type_list.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/detail/typed_actor_util.hpp
  libcaf_core/caf/detail/unique_function.hpp
  libcaf_core/caf/exec_main.hpp
  libcaf_core/caf/expected.hpp
  libcaf_core/caf/hash/fnv.hpp
  libcaf_core/caf/hash/sha1.hpp
  libcaf_core/caf/infer_handle.hpp
  libcaf_core/caf/inspector_access.hpp
  libcaf_core/caf/intrusive/forward_iterator.hpp
  libcaf_core/caf/intrusive_ptr.hpp
  libcaf_core/caf/load_inspector.hpp
  libcaf_core/caf/load_inspector_base.hpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/mailbox_element.hpp
  libcaf_core/caf/message.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/mtl.hpp
  libcaf_core/caf/node_id.cpp
  libcaf_core/caf/optional.hpp
  libcaf_core/caf/save_inspector.hpp
  libcaf_core/caf/save_inspector_base.hpp
  libcaf_core/caf/serializer.hpp
  libcaf_core/caf/stateful_actor.hpp
  libcaf_core/caf/string_view.hpp
  libcaf_core/caf/telemetry/collector/prometheus.cpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/caf/typed_response_promise.hpp
  libcaf_core/caf/weak_intrusive_ptr.hpp
  libcaf_core/tests/legacy/config_option.cpp
  libcaf_core/tests/legacy/detail/parser/read_number.cpp
  libcaf_core/tests/legacy/detail/parser/read_number_or_timespan.cpp
  libcaf_core/tests/legacy/metaprogramming.cpp
  libcaf_core/tests/legacy/typed_spawn.cpp
  libcaf_io/caf/io/typed_broker.hpp
  libcaf_test/caf/test/dsl.hpp
  libcaf_test/caf/test/unit_test.hpp
Labels: refactoring

#1515 Turn warnings into errors in CI
  .ci/debug-flags.cmake
  .ci/windows/build.cmd
  Jenkinsfile
  examples/custom_type/custom_types_4.cpp
  libcaf_core/caf/async/blocking_consumer.hpp
  libcaf_core/caf/chrono.cpp
  libcaf_core/caf/config.hpp
  libcaf_core/caf/config_value.cpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/detail/config_consumer.hpp
  libcaf_core/caf/detail/functor_attachable.hpp
  libcaf_core/caf/detail/make_meta_object.hpp
  libcaf_core/caf/detail/parser/read_number.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/expected.hpp
  libcaf_core/caf/flow/step/take_last.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/tests/legacy/scheduled_actor.cpp
  libcaf_net/caf/net/http/arg_parser.hpp
  libcaf_net/caf/net/http/request_header.hpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_net/tests/legacy/net/web_socket/framing.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
  libcaf_test/caf/test/runner.cpp
  libcaf_test/caf/test/test.test.cpp
Labels: diagnostic, pipeline

#1526 Refactor remaining calls to $pred<>::value
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_traits.hpp
  libcaf_core/caf/config_value.cpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/config_value_reader.cpp
  libcaf_core/caf/detail/type_list.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/inspector_access_type.hpp
  libcaf_core/caf/is_typed_actor.hpp
  libcaf_core/caf/response_promise.hpp
  libcaf_core/caf/span.hpp
  libcaf_core/caf/typed_behavior.hpp
  libcaf_core/tests/legacy/metaprogramming.cpp
Labels: refactoring

#1527 Fix failing build on master
  libcaf_net/tests/drivers/autobahn.cpp
Labels: diagnostic

#1528 Implement requirement_failed exception
  libcaf_test/CMakeLists.txt
  libcaf_test/caf/test/requirement_error.cpp
  libcaf_test/caf/test/requirement_error.hpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/runner.cpp
Labels: testing

#1531 Re-enable FixNamespaceComments in clang-format
  .clang-format
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
Labels: refactoring, pipeline

#1532 Re-implement inject in the deterministic fixture
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/action.hpp
  libcaf_core/caf/action.test.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
Labels: refactoring, testing

#1530 Add require function for all predicates
  libcaf_test/CMakeLists.txt
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/reporter.hpp
  libcaf_test/caf/test/requirement_failed.cpp
  libcaf_test/caf/test/requirement_failed.hpp
  libcaf_test/caf/test/runnable.cpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/runner.cpp
  libcaf_test/caf/test/test.test.cpp
Labels: testing

#1535 Cover expect/allow/inject in the new test readme
  libcaf_test/README.md
Labels: documentation

#1536 Remove obsolete type traits
  libcaf_core/caf/actor.hpp
  libcaf_core/caf/actor_factory.hpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/detail/parse.hpp
  libcaf_core/caf/detail/parser/add_ascii.hpp
  libcaf_core/caf/detail/parser/sub_ascii.hpp
  libcaf_core/caf/detail/spawnable.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/intrusive_ptr.hpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/may_have_timeout.hpp
  libcaf_core/caf/message_handler.hpp
  libcaf_core/caf/mixin/requester.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/policy/select_all.hpp
  libcaf_core/caf/policy/select_any.hpp
  libcaf_core/caf/response_handle.hpp
  libcaf_core/caf/send.hpp
  libcaf_core/caf/span.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/caf/typed_actor_pointer.hpp
  libcaf_test/caf/test/dsl.hpp
  libcaf_test/caf/test/io_dsl.hpp
  libcaf_test/caf/test/unit_test.hpp
Labels: refactoring

#1533 Add print for debug, warning and trace severities
  libcaf_core/caf/detail/ring_buffer.test.cpp
  libcaf_core/caf/detail/sync_ring_buffer.test.cpp
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/reporter.hpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/test.test.cpp
Labels: testing

#1539 Refactor remaining type predicates
  libcaf_core/caf/actor_cast.hpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/detail/behavior_impl.hpp
  libcaf_core/caf/detail/implicit_conversions.hpp
  libcaf_core/caf/detail/int_list.hpp
  libcaf_core/caf/detail/typed_actor_util.hpp
  libcaf_core/caf/detail/unique_function.hpp
  libcaf_core/caf/exec_main.hpp
  libcaf_core/caf/expected.hpp
  libcaf_core/caf/infer_handle.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/mixin/behavior_changer.hpp
  libcaf_core/caf/optional.hpp
  libcaf_core/caf/resumable.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/string_view.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_io/caf/io/broker_servant.hpp
Labels: refactoring

#1540 Add first and last flow with tests
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable.test.cpp
  libcaf_core/caf/flow/observable_decl.hpp
Labels: new feature

#1543 Flush delta buffer after consuming input
  CHANGELOG.md
  libcaf_net/caf/net/octet_stream/transport.cpp
  libcaf_net/tests/legacy/net-test.cpp
  libcaf_net/tests/legacy/net/octet_stream/transport.cpp
Labels: refactoring, bugfix

#1544 Refactor lambda functions with explicit capture
  examples/dynamic_behavior/dining_philosophers.cpp
  examples/message_passing/fixed_stack.cpp
  examples/message_passing/request.cpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/detail/split_join.hpp
  libcaf_core/caf/scheduler/test_coordinator.cpp
  libcaf_core/tests/legacy/constructor_attach.cpp
  libcaf_core/tests/legacy/dynamic_spawn.cpp
  libcaf_core/tests/legacy/message_lifetime.cpp
  libcaf_core/tests/legacy/mixin/requester.cpp
  libcaf_core/tests/legacy/policy/select_all.cpp
  libcaf_core/tests/legacy/policy/select_any.cpp
  libcaf_core/tests/legacy/stateful_actor.cpp
  libcaf_core/tests/legacy/typed_spawn.cpp
  libcaf_io/caf/detail/prometheus_broker.cpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman_actor_impl.cpp
  libcaf_test/caf/test/dsl.hpp
  libcaf_test/caf/test/io_dsl.hpp
  libcaf_test/caf/test/runner.cpp
  libcaf_test/caf/test/unit_test_impl.hpp
Labels: refactoring
