Repository actor-framework/actor-framework, pull requests merged in 2023-06, with the labels that each got.

#1422 Fix handling of fragmented WebSocket frames
  CHANGELOG.md
  libcaf_net/caf/detail/rfc6455.hpp
  libcaf_net/src/detail/rfc6455.cpp
  libcaf_net/src/net/web_socket/framing.cpp
  libcaf_net/test/net/web_socket/server.cpp
Labels: bugfix

#1430 Update to Fedora 38 and add FreeBSD 13.2 in the CI
  .ci/fedora-37/Dockerfile
  .ci/fedora-38/Dockerfile
  .ci/freebsd-13/prepare.sh
  .cirrus.yml
Labels: maintenance

#1431 Bring back Jenkins for Linux builds
  .ci/ubuntu-18.04/Dockerfile
  .cirrus.yml
  .github/workflows/check-formatting.yml
  .github/workflows/check-typos.yml
  .typos-config.toml
  CHANGELOG.md
  Jenkinsfile
  examples/length_prefix_framing/chat-client.cpp
  libcaf_core/test/core-test.hpp
Labels: maintenance

#1433 Tag debug builds on Jenkins with more context
  Jenkinsfile
Labels: pipeline

#1434 Remove windows from Cirrus. Add Github Action for Windows CI
  .ci/windows/build.cmd
  .ci/windows/test.cmd
  .cirrus.yml
  .github/workflows/check-windows.yml
Labels: pipeline

#1439 Clean up clang-tidy config file
  .clang-tidy
Labels: diagnostic

#1441 Add new linux distros to the CI
  .ci/almalinux-9/Dockerfile
  .ci/alpinelinux-3.18/Dockerfile
  Jenkinsfile
  libcaf_core/caf/config.hpp
Labels: pipeline

#1443 Use load_file instead of reading file manually
  examples/config/read-json.cpp
Labels: refactoring

#1445 Add missing compare overload
  CHANGELOG.md
  libcaf_core/caf/telemetry/label.hpp
  libcaf_core/caf/telemetry/label_view.hpp
  libcaf_core/src/telemetry/label.cpp
  libcaf_core/src/telemetry/label_view.cpp
Labels: new feature

#1447 Fix regression in --dump-config output
  CHANGELOG.md
  libcaf_core/caf/dictionary.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_io/src/io/middleman.cpp
  libcaf_net/src/net/middleman.cpp
  libcaf_openssl/src/openssl/manager.cpp
  robot/CMakeLists.txt
  robot/config/dump-config.robot
Labels: bugfix

#1451 Enable --foo bar syntax
  CHANGELOG.md
  libcaf_core/caf/config_option.hpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/config_option.cpp
  libcaf_core/src/config_option_set.cpp
  libcaf_core/test/actor_system_config.cpp
  libcaf_core/test/config_option.cpp
  libcaf_core/test/config_option_set.cpp
  robot/CMakeLists.txt
  robot/config/read-config-file.robot
Labels: new feature

#1455 Fix typos
  CHANGELOG.md
  libcaf_net/caf/net/generic_lower_layer.hpp
Labels: documentation

#1457 Remove unstable sequencer tests
  libcaf_core/CMakeLists.txt
  libcaf_core/test/decorator/sequencer.cpp
Labels: refactoring

#1460 Add utility for UTF-8 validation
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/rfc3629.hpp
  libcaf_core/src/detail/rfc3629.cpp
  libcaf_core/test/detail/rfc3629.cpp
Labels: new feature

#1462 Support string_view in make_message and make_error
  CHANGELOG.md
  libcaf_core/caf/detail/implicit_conversions.hpp
  libcaf_core/test/error.cpp
  libcaf_core/test/message.cpp
Labels: new feature

#1463 Add GitHub action for code coverage via codecov
  .github/workflows/codecov.yml
  codecov.yml
Labels: pipeline

#1459 Refactor test cases and unify mock socket app
  libcaf_net/test/detail/rfc6455.cpp
  libcaf_net/test/net-test.cpp
  libcaf_net/test/net-test.hpp
  libcaf_net/test/net/web_socket/client.cpp
  libcaf_net/test/net/web_socket/framing.cpp
  libcaf_net/test/net/web_socket/server.cpp
Labels: refactoring

#1461 Isolate closing handshake
  libcaf_net/caf/net/web_socket/framing.hpp
  libcaf_net/src/net/web_socket/framing.cpp
  libcaf_net/src/net/web_socket/lower_layer.cpp
  libcaf_net/test/net/web_socket/framing.cpp
Labels: bugfix

#1464 Tweak codecov config
  .github/workflows/codecov.yml
Labels: pipeline
