Repository actor-framework/actor-framework, pull requests merged in 2023-07, with the labels that each got.

#1465 Remove the logger.inline-output parameter
  libcaf_core/caf/logger.hpp
  libcaf_core/src/actor_system.cpp
  libcaf_core/src/actor_system_config.cpp
  libcaf_core/src/logger.cpp
  libcaf_core/test/settings.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: refactoring

#1468 Add Mastodon link to readme
  README.md
Labels: documentation

#1469 Add a new abstraction: publishers
  CHANGELOG.md
  examples/length_prefix_framing/chat-server.cpp
  examples/qtsupport/chatwidget.hpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/async/fwd.hpp
  libcaf_core/caf/async/publisher.hpp
  libcaf_core/caf/disposable.hpp
  libcaf_core/caf/flow/fwd.hpp
  libcaf_core/caf/flow/item_publisher.hpp
  libcaf_core/caf/flow/multicaster.hpp
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/op/cold.hpp
  libcaf_core/caf/flow/op/hot.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/src/disposable.cpp
  libcaf_core/test/async/publisher.cpp
  libcaf_core/test/flow/multicaster.cpp
  libcaf_core/test/flow/op/buffer.cpp
  libcaf_core/test/flow/op/merge.cpp
Labels: new feature

#1471 Relax codecov threshold
  codecov.yml
Labels: pipeline

#1470 Separate WebSocket control frames
  libcaf_net/caf/net/web_socket/framing.hpp
  libcaf_net/src/detail/rfc6455.cpp
  libcaf_net/src/net/web_socket/framing.cpp
  libcaf_net/test/detail/rfc6455.cpp
  libcaf_net/test/net-test.cpp
  libcaf_net/test/net/web_socket/framing.cpp
Labels: bugfix

#1478 Add initial version for the new testing framework
  .clang-format
  .github/workflows/check-formatting.yml
  CMakeLists.txt
  Jenkinsfile
  libcaf_core/caf/detail/format.hpp
  libcaf_core/caf/detail/source_location.hpp
  libcaf_core/caf/node_id.hpp
  libcaf_core/caf/type_id.hpp
  libcaf_core/test/nasty.hpp
  libcaf_test/CMakeLists.txt
  libcaf_test/caf/test/and_given.hpp
  libcaf_test/caf/test/and_then.hpp
  libcaf_test/caf/test/and_when.hpp
  libcaf_test/caf/test/binary_predicate.hpp
  libcaf_test/caf/test/block.hpp
  libcaf_test/caf/test/block_type.hpp
  libcaf_test/caf/test/caf_test_main.hpp
  libcaf_test/caf/test/context.hpp
  libcaf_test/caf/test/factory.hpp
  libcaf_test/caf/test/fwd.hpp
  libcaf_test/caf/test/given.hpp
  libcaf_test/caf/test/nesting_error.hpp
  libcaf_test/caf/test/registry.hpp
  libcaf_test/caf/test/reporter.hpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/runner.hpp
  libcaf_test/caf/test/scenario.hpp
  libcaf_test/caf/test/scope.hpp
  libcaf_test/caf/test/section.hpp
  libcaf_test/caf/test/suite.hpp
  libcaf_test/caf/test/test.hpp
  libcaf_test/caf/test/then.hpp
  libcaf_test/caf/test/when.hpp
  libcaf_test/src/test/and_given.cpp
  libcaf_test/src/test/and_then.cpp
  libcaf_test/src/test/and_when.cpp
  libcaf_test/src/test/block.cpp
  libcaf_test/src/test/context.cpp
  libcaf_test/src/test/factory.cpp
  libcaf_test/src/test/given.cpp
  libcaf_test/src/test/nesting_error.cpp
  libcaf_test/src/test/registry.cpp
  libcaf_test/src/test/reporter.cpp
  libcaf_test/src/test/runnable.cpp
  libcaf_test/src/test/runner.cpp
  libcaf_test/src/test/scenario.cpp
  libcaf_test/src/test/scope.cpp
  libcaf_test/src/test/section.cpp
  libcaf_test/src/test/test.cpp
  libcaf_test/src/test/then.cpp
  libcaf_test/src/test/when.cpp
  libcaf_test/test/test-test.cpp
  libcaf_test/test/test/block_type.cpp
  libcaf_test/test/test/scenario.cpp
  libcaf_test/test/test/test.cpp
Labels: new feature, testing

#1477 Validate UTF-8 on WebSocket text payloads
  libcaf_core/caf/sec.hpp
  libcaf_core/src/detail/rfc3629.cpp
  libcaf_core/src/sec_strings.cpp
  libcaf_core/test/detail/rfc3629.cpp
  libcaf_io/caf/io/basp/connection_state.hpp
  libcaf_io/src/io/basp/instance.cpp
  libcaf_net/src/net/web_socket/framing.cpp
  libcaf_net/src/net/web_socket/lower_layer.cpp
Labels: bugfix

#1480 Integrate the new unit testing framework
  CMakeLists.txt
  libcaf_core/CMakeLists.txt
  libcaf_core/test/core-legacy-test.cpp
  libcaf_core/test/core-test.cpp
  libcaf_core/test/hash/fnv.cpp
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/io/network/receive_buffer.hpp
  libcaf_io/test/io-legacy-test.cpp
  libcaf_io/test/io-test.cpp
  libcaf_io/test/io/network/receive_buffer.cpp
  libcaf_io/test/io/receive_buffer.cpp
  libcaf_net/CMakeLists.txt
  libcaf_net/test/detail/rfc6455.cpp
  libcaf_net/test/net-legacy-test.cpp
  libcaf_net/test/net-test.cpp
  libcaf_test/caf/test/and_given.hpp
  libcaf_test/caf/test/and_then.hpp
  libcaf_test/caf/test/and_when.hpp
  libcaf_test/caf/test/factory.hpp
  libcaf_test/caf/test/given.hpp
  libcaf_test/caf/test/registry.hpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/runner.hpp
  libcaf_test/caf/test/scenario.hpp
  libcaf_test/caf/test/section.hpp
  libcaf_test/caf/test/test.hpp
  libcaf_test/caf/test/then.hpp
  libcaf_test/caf/test/unit_test.hpp
  libcaf_test/caf/test/unit_test_impl.hpp
  libcaf_test/caf/test/when.hpp
  libcaf_test/src/test/registry.cpp
Labels: refactoring

#1482 Use the Canonical Project Structure for caf_test
  CMakeLists.txt
  libcaf_test/CMakeLists.txt
  libcaf_test/caf/test/and_given.cpp
  libcaf_test/caf/test/and_then.cpp
  libcaf_test/caf/test/and_when.cpp
  libcaf_test/caf/test/block.cpp
  libcaf_test/caf/test/block_type.test.cpp
  libcaf_test/caf/test/context.cpp
  libcaf_test/caf/test/factory.cpp
  libcaf_test/caf/test/given.cpp
  libcaf_test/caf/test/nesting_error.cpp
  libcaf_test/caf/test/registry.cpp
  libcaf_test/caf/test/registry.hpp
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/runnable.cpp
  libcaf_test/caf/test/runner.cpp
  libcaf_test/caf/test/scenario.cpp
  libcaf_test/caf/test/scenario.hpp
  libcaf_test/caf/test/scenario.test.cpp
  libcaf_test/caf/test/scope.cpp
  libcaf_test/caf/test/section.cpp
  libcaf_test/caf/test/suite.hpp
  libcaf_test/caf/test/test.cpp
  libcaf_test/caf/test/test.hpp
  libcaf_test/caf/test/test.test.cpp
  libcaf_test/caf/test/then.cpp
  libcaf_test/caf/test/when.cpp
  libcaf_test/test/test-test.cpp
Labels: refactoring

#1487 Use the Canonical Project Structure for caf_io
  CMakeLists.txt
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/detail/prometheus_broker.cpp
  libcaf_io/caf/detail/remote_group_module.cpp
  libcaf_io/caf/detail/socket_guard.cpp
  libcaf_io/caf/io/abstract_broker.cpp
  libcaf_io/caf/io/basp/header.cpp
  libcaf_io/caf/io/basp/instance.cpp
  libcaf_io/caf/io/basp/message_queue.cpp
  libcaf_io/caf/io/basp/routing_table.cpp
  libcaf_io/caf/io/basp/worker.cpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/broker.cpp
  libcaf_io/caf/io/connection_helper.cpp
  libcaf_io/caf/io/datagram_servant.cpp
  libcaf_io/caf/io/doorman.cpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman_actor.cpp
  libcaf_io/caf/io/middleman_actor_impl.cpp
  libcaf_io/caf/io/network/acceptor.cpp
  libcaf_io/caf/io/network/acceptor_manager.cpp
  libcaf_io/caf/io/network/datagram_handler.cpp
  libcaf_io/caf/io/network/datagram_manager.cpp
  libcaf_io/caf/io/network/datagram_servant_impl.cpp
  libcaf_io/caf/io/network/default_multiplexer.cpp
  libcaf_io/caf/io/network/doorman_impl.cpp
  libcaf_io/caf/io/network/event_handler.cpp
  libcaf_io/caf/io/network/interfaces.cpp
  libcaf_io/caf/io/network/ip_endpoint.cpp
  libcaf_io/caf/io/network/manager.cpp
  libcaf_io/caf/io/network/multiplexer.cpp
  libcaf_io/caf/io/network/native_socket.cpp
  libcaf_io/caf/io/network/pipe_reader.cpp
  libcaf_io/caf/io/network/protocol.cpp
  libcaf_io/caf/io/network/receive_buffer.cpp
  libcaf_io/caf/io/network/receive_buffer.test.cpp
  libcaf_io/caf/io/network/scribe_impl.cpp
  libcaf_io/caf/io/network/stream.cpp
  libcaf_io/caf/io/network/stream_manager.cpp
  libcaf_io/caf/io/network/test_multiplexer.cpp
  libcaf_io/caf/io/scribe.cpp
  libcaf_io/caf/policy/tcp.cpp
  libcaf_io/caf/policy/udp.cpp
Labels: refactoring

#1491 Use the new project structure for caf_openssl
  libcaf_openssl/CMakeLists.txt
  libcaf_openssl/caf/openssl/manager.cpp
  libcaf_openssl/caf/openssl/middleman_actor.cpp
  libcaf_openssl/caf/openssl/publish.cpp
  libcaf_openssl/caf/openssl/remote_actor.cpp
  libcaf_openssl/caf/openssl/session.cpp
Labels: refactoring

#1488 Drop unnecessary arguments in octet_stream::policy
  libcaf_net/caf/net/http/server_factory.hpp
  libcaf_net/caf/net/lp/client_factory.hpp
  libcaf_net/caf/net/lp/server_factory.hpp
  libcaf_net/caf/net/octet_stream/policy.hpp
  libcaf_net/caf/net/octet_stream/transport.hpp
  libcaf_net/caf/net/ssl/transport.hpp
  libcaf_net/caf/net/web_socket/client_factory.hpp
  libcaf_net/caf/net/web_socket/server_factory.hpp
  libcaf_net/src/net/octet_stream/policy.cpp
  libcaf_net/src/net/octet_stream/transport.cpp
  libcaf_net/src/net/ssl/transport.cpp
Labels: refactoring

#1481 Implement fragmented UTF-8 validation
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/rfc3629.hpp
  libcaf_core/src/detail/rfc3629.cpp
  libcaf_core/test/detail/rfc3629.cpp
  libcaf_net/caf/net/web_socket/framing.hpp
  libcaf_net/src/net/web_socket/framing.cpp
  libcaf_net/test/net/web_socket/framing.cpp
Labels: new feature

#1490 Added filtering for suites based on regex
  libcaf_test/caf/test/runner.cpp
  libcaf_test/caf/test/runner.hpp
Labels: testing

#1495 Refactor all calls to is_same::value to is_same_v
  examples/custom_type/custom_types_4.cpp
  examples/remoting/distributed_calculator.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/config_value_reader.cpp
  libcaf_core/caf/config_value_writer.cpp
  libcaf_core/caf/detail/behavior_impl.hpp
  libcaf_core/caf/detail/config_consumer.cpp
  libcaf_core/caf/detail/mtl_util.hpp
  libcaf_core/caf/detail/parser/fsm.hpp
  libcaf_core/caf/detail/parser/read_string.hpp
  libcaf_core/caf/detail/profiled_send.hpp
  libcaf_core/caf/detail/set_thread_name.cpp
  libcaf_core/caf/detail/stringification_inspector.hpp
  libcaf_core/caf/detail/type_list.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/detail/typed_actor_util.hpp
  libcaf_core/caf/error_code.hpp
  libcaf_core/caf/exec_main.hpp
  libcaf_core/caf/inspector_access.hpp
  libcaf_core/caf/load_inspector.hpp
  libcaf_core/caf/load_inspector_base.hpp
  libcaf_core/caf/message.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/mtl.hpp
  libcaf_core/caf/node_id.cpp
  libcaf_core/caf/response_handle.hpp
  libcaf_core/caf/response_promise.hpp
  libcaf_core/caf/resumable.hpp
  libcaf_core/caf/save_inspector.hpp
  libcaf_core/caf/save_inspector_base.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/send.hpp
  libcaf_core/caf/settings.hpp
  libcaf_core/caf/string_view.hpp
  libcaf_core/caf/telemetry/counter.hpp
  libcaf_core/caf/telemetry/histogram.hpp
  libcaf_core/caf/telemetry/metric_family_impl.hpp
  libcaf_core/caf/typed_behavior.hpp
  libcaf_core/caf/typed_response_promise.hpp
  libcaf_core/test/actor_lifetime.cpp
  libcaf_core/test/config_value.cpp
  libcaf_core/test/json_reader.cpp
  libcaf_core/test/metaprogramming.cpp
  libcaf_core/test/typed_behavior.cpp
  libcaf_io/caf/io/broker_servant.hpp
  libcaf_test/caf/test/dsl.hpp
  libcaf_test/caf/test/unit_test.hpp
Labels: refactoring

#1497 Stop handling continuation frames as control frames
  libcaf_net/caf/detail/rfc6455.hpp
  libcaf_net/caf/net/web_socket/framing.cpp
Labels: bugfix

#1499 Remove ripemd160
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/get_mac_addresses.cpp
  libcaf_core/caf/detail/get_mac_addresses.hpp
  libcaf_core/caf/detail/get_root_uuid.cpp
  libcaf_core/caf/detail/get_root_uuid.hpp
  libcaf_core/caf/detail/ripemd_160.cpp
  libcaf_core/caf/detail/ripemd_160.hpp
  libcaf_core/caf/node_id.cpp
  libcaf_core/test/detail/ripemd_160.cpp
  libcaf_core/test/serialization.cpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/network/interfaces.cpp
Labels: refactoring

#1498 Decode and validate WebSocket closing payload
  libcaf_net/caf/net/web_socket/framing.cpp
  libcaf_net/caf/net/web_socket/framing.hpp
  libcaf_net/test/net/web_socket/framing.cpp
Labels: bugfix

#1506 Send error if a request fails to deserialize
  CHANGELOG.md
  libcaf_core/caf/detail/sync_request_bouncer.cpp
  libcaf_io/caf/io/basp/remote_message_handler.hpp
  libcaf_io/test/io-test.hpp
  libcaf_io/test/io/middleman.cpp
Labels: new feature

#1505 Refactor multiplexer to be an interface
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/detail/pollset_updater.cpp
  libcaf_net/caf/detail/pollset_updater.hpp
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_net/caf/net/multiplexer.hpp
Labels: refactoring

#1508 Rename detail::{ringbuffer => sync_ring_buffer}
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/sync_ring_buffer.hpp
  libcaf_core/caf/detail/sync_ring_buffer.test.cpp
  libcaf_core/caf/detail/thread_safe_actor_clock.hpp
  libcaf_core/caf/logger.hpp
  libcaf_core/test/detail/ringbuffer.cpp
Labels: refactoring

#1502 Add watchdog and option to abort application when test exceeds maximum runtime
  libcaf_test/caf/test/runner.cpp
Labels: testing

#1509 Test build without specific openssl path
  .ci/windows/build.cmd
Labels: pipeline

#1510 Return the result from check functions
  libcaf_test/caf/test/runnable.cpp
  libcaf_test/caf/test/runnable.hpp
Labels: refactoring

#1493 Add option to disable colored output
  libcaf_test/caf/test/reporter.cpp
  libcaf_test/caf/test/reporter.hpp
  libcaf_test/caf/test/runner.cpp
Labels: testing
