Repository actor-framework/actor-framework, pull requests merged in 2023-01, with the labels that each got.

#1370 address unsafe sprintf usage
  libcaf_io/src/io/network/interfaces.cpp
Labels: diagnostic

#1373 Handle void results in fan_out_request
  CHANGELOG.md
  libcaf_core/caf/policy/select_all.hpp
  libcaf_core/test/mixin/requester.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: bugfix

#1368 Provide `*_weak` variants of `scheduled_actor::run_{delayed,scheduled}`
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/src/scheduled_actor.cpp
Labels: new feature
