Repository actor-framework/actor-framework, pull requests merged in 2024-11, with the labels that each got.

#1956 Add tests for json to increase coverage
  libcaf_core/caf/json_value.test.cpp
Labels: testing

#1958 Add tests for parsing json files
  libcaf_core/caf/json_value.test.cpp
  libcaf_core/tests/data/values.json
Labels: testing

#1941 Add retry flow operator
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/op/retry.hpp
  libcaf_core/caf/flow/op/retry.test.cpp
Labels: new feature

#1959 Add regression test for #1953
  libcaf_core/caf/serialization.test.cpp
Labels: testing

#1960 Add tests for stringification_inspector
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/stringification_inspector.test.cpp
Labels: testing

#1964 Avoid clang-tidy false positives for intrusive_ptr
  CHANGELOG.md
  libcaf_core/caf/intrusive_ptr.hpp
Labels: diagnostic
