Repository actor-framework/actor-framework, pull requests merged in 2024-05, with the labels that each got.

#1849 add_actor_type cleanup
  Jenkinsfile
  libcaf_core/caf/actor_system_config.hpp
Labels: refactoring

#1852 Better encapsulate purely internal code in caf-net
  CMakeLists.txt
  CONTRIBUTING.md
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/detail/accept_handler.hpp
  libcaf_net/caf/detail/convert_ip_endpoint.cpp
  libcaf_net/caf/detail/convert_ip_endpoint.hpp
  libcaf_net/caf/detail/convert_ip_endpoint.test.cpp
  libcaf_net/caf/detail/message_flow_bridge.hpp
  libcaf_net/caf/detail/octet_stream_flow_bridge.test.cpp
  libcaf_net/caf/detail/ws_conn_acceptor.hpp
  libcaf_net/caf/internal/accept_handler.cpp
  libcaf_net/caf/internal/accept_handler.hpp
  libcaf_net/caf/internal/flow_bridge_base.hpp
  libcaf_net/caf/internal/get_fd.hpp
  libcaf_net/caf/internal/lp_flow_bridge.cpp
  libcaf_net/caf/internal/lp_flow_bridge.hpp
  libcaf_net/caf/internal/make_transport.hpp
  libcaf_net/caf/internal/net_syscall.hpp
  libcaf_net/caf/internal/octet_stream_flow_bridge.cpp
  libcaf_net/caf/internal/octet_stream_flow_bridge.hpp
  libcaf_net/caf/internal/sockaddr_members.hpp
  libcaf_net/caf/internal/socket_sys_includes.hpp
  libcaf_net/caf/internal/ws_flow_bridge.cpp
  libcaf_net/caf/internal/ws_flow_bridge.hpp
  libcaf_net/caf/net/datagram_socket.cpp
  libcaf_net/caf/net/http/client.cpp
  libcaf_net/caf/net/http/server_factory.cpp
  libcaf_net/caf/net/http/server_factory.hpp
  libcaf_net/caf/net/ip.cpp
  libcaf_net/caf/net/lp/client_factory.cpp
  libcaf_net/caf/net/lp/server_factory.cpp
  libcaf_net/caf/net/lp/server_factory.hpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_net/caf/net/network_socket.cpp
  libcaf_net/caf/net/octet_stream/client_factory.cpp
  libcaf_net/caf/net/octet_stream/server_factory.cpp
  libcaf_net/caf/net/octet_stream/server_factory.hpp
  libcaf_net/caf/net/pipe_socket.cpp
  libcaf_net/caf/net/socket.cpp
  libcaf_net/caf/net/stream_socket.cpp
  libcaf_net/caf/net/tcp_accept_socket.cpp
  libcaf_net/caf/net/tcp_stream_socket.cpp
  libcaf_net/caf/net/this_host.cpp
  libcaf_net/caf/net/udp_datagram_socket.cpp
  libcaf_net/caf/net/web_socket/client_factory.cpp
  libcaf_net/caf/net/web_socket/server_factory.cpp
  libcaf_net/caf/net/web_socket/server_factory.hpp
  libcaf_net/caf/net/web_socket/switch_protocol.cpp
  libcaf_net/caf/net/web_socket/switch_protocol.hpp
  libcaf_net/tests/drivers/autobahn.cpp
Labels: refactoring

#1855 Document the removal of the logger factory
  CHANGELOG.md
Labels: documentation

#1854 Drop the last remaining legacy test scaffolding
  CMakeLists.txt
  libcaf_net/CMakeLists.txt
  libcaf_net/tests/legacy/net-test.cpp
  libcaf_net/tests/legacy/net-test.hpp
  libcaf_net/tests/legacy/net/ssl/ca.pem
  libcaf_net/tests/legacy/net/ssl/cert_1.pem
  libcaf_net/tests/legacy/net/ssl/cert_2.pem
  libcaf_net/tests/legacy/net/ssl/key_1.pem
  libcaf_net/tests/legacy/net/ssl/key_1_enc.pem
  libcaf_net/tests/legacy/net/ssl/key_2.pem
  libcaf_net/tests/legacy/net/ssl/transport.cpp
  libcaf_net/tests/legacy/pem.cpp.in
  libcaf_net/tests/legacy/pem.hpp
Labels: testing

#1853 Fix parsing of Windows-style line endings
  CHANGELOG.md
  libcaf_core/caf/detail/json.cpp
  libcaf_core/caf/detail/parser/chars.cpp
  libcaf_core/caf/detail/parser/chars.hpp
  libcaf_core/caf/detail/parser/read_config.hpp
  libcaf_core/caf/detail/parser/read_config.test.cpp
  libcaf_core/caf/detail/parser/read_string.hpp
  libcaf_core/caf/json_reader.test.cpp
Labels: bugfix

#1857 Remove obsolete config_option_adder::add_neg
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/config_option.test.cpp
  libcaf_core/caf/config_option_adder.cpp
  libcaf_core/caf/config_option_adder.hpp
  libcaf_core/caf/make_config_option.cpp
  libcaf_core/caf/make_config_option.hpp
Labels: refactoring

#1856 Add missing tests to improve coverage
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/beacon.test.cpp
  libcaf_core/caf/ipv4_subnet.test.cpp
  libcaf_core/caf/ipv6_subnet.test.cpp
  libcaf_core/caf/settings.cpp
  libcaf_core/caf/unit.test.cpp
Labels: testing

#1858 Remove dead code
  libcaf_core/caf/attachable.cpp
  libcaf_core/caf/attachable.hpp
Labels: refactoring

#1861 Fix math in chrono::datetime::force_utc
  CHANGELOG.md
  libcaf_core/caf/chrono.cpp
  libcaf_core/caf/chrono.test.cpp
Labels: bugfix

#1865 Temporarily disable caf-robot-lp-communication
  robot/CMakeLists.txt
Labels: testing

#1862 Move former CAFcademy gems to the manual
  manual/CopyOnWriteTypes.rst
  manual/Hashing.rst
  manual/MessagePassing.rst
  manual/Metrics.rst
  manual/TypedMessageView.rst
  manual/index.rst
  manual/net/LengthPrefixFraming.rst
Labels: documentation

#1867 Apply the pimpl idiom to http::request
  libcaf_net/caf/net/http/request.cpp
  libcaf_net/caf/net/http/request.hpp
  libcaf_net/caf/net/http/router.cpp
Labels: refactoring

#1868 Fix regression in the work-stealing implementation
  CHANGELOG.md
  libcaf_core/caf/scheduler.cpp
Labels: bugfix

#1871 Change values for log levels
  libcaf_core/caf/detail/log_level.hpp
  libcaf_core/caf/logger.cpp
Labels: refactoring

#1870 Update monitor API, usage and documentation
  CHANGELOG.md
  examples/hello_world.cpp
  examples/message_passing/idle_timeout_repeat.cpp
  examples/remoting/distributed_calculator.cpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_ostream.hpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/delegate.test.cpp
  libcaf_core/caf/detail/monitor_action.cpp
  libcaf_core/caf/detail/monitor_action.hpp
  libcaf_core/caf/local_actor.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/message_lifetime.test.cpp
  libcaf_core/caf/monitor.test.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/scheduled_actor.test.cpp
  libcaf_core/caf/scheduler.hpp
  libcaf_core/caf/spawn_options.hpp
  libcaf_core/caf/typed_event_based_actor.test.cpp
  libcaf_core/caf/typed_spawn.test.cpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/basp_broker.hpp
  libcaf_io/caf/io/connection_helper.cpp
  libcaf_io/caf/io/middleman_actor_impl.cpp
  manual/Actors.rst
  manual/Introduction.rst
  manual/UsingAout.rst
  manual/index.rst
  robot/middleman/driver.cpp
Labels: refactoring, documentation

#1863 Add tests to improve code coverage
  CHANGELOG.md
  libcaf_core/caf/blocking_actor.test.cpp
  libcaf_core/caf/json_builder.cpp
  libcaf_core/caf/json_builder.test.cpp
  libcaf_core/caf/serialization.test.cpp
Labels: bugfix, testing

#1872 Deprecate `after(...)` for event-based actors
  CHANGELOG.md
  libcaf_core/caf/behavior.hpp
  libcaf_core/caf/detached_actors.test.cpp
  libcaf_core/caf/request_timeout.test.cpp
  libcaf_core/caf/timeout_definition.hpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/connection_helper.cpp
Labels: refactoring

#1874 Add section on idle timeouts to the manual
  doc/graffle/mailbox_element.graffle
  manual/MessageHandlers.rst
  manual/MessagePassing.rst
  manual/mailbox_element.png
Labels: documentation

#1876 Mention auto-move of values into message handlers
  examples/curl/curl_fuse.cpp
  examples/http/rest.cpp
  manual/MessagePassing.rst
Labels: refactoring, documentation

#1878 Deprecate the function view
  CHANGELOG.md
  CMakeLists.txt
  examples/message_passing/fan_out_request.cpp
  libcaf_core/caf/actor_factory.test.cpp
  libcaf_core/caf/actor_lifetime.test.cpp
  libcaf_core/caf/actor_pool.test.cpp
  libcaf_core/caf/detached_actors.test.cpp
  libcaf_core/caf/dynamic_spawn.test.cpp
  libcaf_core/caf/function_view.hpp
  libcaf_core/caf/function_view.test.cpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/monitor.test.cpp
  libcaf_core/caf/scheduled_actor.test.cpp
  libcaf_core/caf/stateful_actor.test.cpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_openssl/caf/openssl/publish.cpp
  libcaf_openssl/caf/openssl/remote_actor.cpp
Labels: refactoring

#1880 Change handling of special messages
  CHANGELOG.md
  examples/dynamic_behavior/skip_messages.cpp
  libcaf_core/caf/detail/type_list.hpp
  libcaf_core/caf/dynamic_spawn.test.cpp
  libcaf_core/caf/interface_mismatch.hpp
  libcaf_core/caf/mixin/sender.test.cpp
  libcaf_core/caf/monitor.test.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/typed_event_based_actor.test.cpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/middleman_actor_impl.cpp
Labels: refactoring

#1881 Fix image reference for the buffer operator
  manual/DataFlows.rst
Labels: documentation

#1877 Refactor floating point comparisons with approx
  CHANGELOG.md
  libcaf_core/caf/actor_system_config.test.cpp
  libcaf_core/caf/config_option_set.test.cpp
  libcaf_core/caf/detail/ieee_754.test.cpp
  libcaf_core/caf/json_array.test.cpp
  libcaf_core/caf/json_builder.test.cpp
  libcaf_core/caf/json_reader.test.cpp
  libcaf_core/caf/json_value.test.cpp
  libcaf_core/caf/message.test.cpp
  libcaf_core/caf/serialization.test.cpp
  libcaf_core/caf/telemetry/counter.test.cpp
  libcaf_core/caf/telemetry/gauge.test.cpp
  libcaf_core/caf/telemetry/histogram.test.cpp
  libcaf_core/caf/typed_event_based_actor.test.cpp
  libcaf_core/caf/typed_spawn.test.cpp
  libcaf_test/caf/test/approx.hpp
  libcaf_test/caf/test/outline.test.cpp
  libcaf_test/caf/test/runnable.hpp
  manual/Testing.rst
Labels: testing

#1882 Improve convenience for typed actors
  libcaf_core/caf/type_list.hpp
  libcaf_core/caf/typed_actor_view.hpp
Labels: new feature
