Repository actor-framework/actor-framework, pull requests merged in 2024-06, with the labels that each got.

#1885 Exclude system messages from fallback handlers
  libcaf_core/caf/behavior.test.cpp
  libcaf_core/caf/detail/behavior_impl.hpp
  libcaf_core/caf/type_id.cpp
  libcaf_core/caf/type_id.hpp
  libcaf_core/caf/typed_behavior.hpp
Labels: bugfix

#1887 Remove unused network socket functions
  libcaf_net/caf/net/network_socket.cpp
  libcaf_net/caf/net/network_socket.hpp
Labels: refactoring

#1892 Various fixes for 1.0
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/chrono.cpp
  libcaf_core/caf/detail/test_coordinator.cpp
  libcaf_core/caf/detail/test_coordinator.hpp
  libcaf_core/caf/flow/op/merge.hpp
  libcaf_net/caf/detail/ws_conn_acceptor.hpp
  libcaf_net/caf/internal/accept_handler.cpp
  libcaf_net/caf/internal/accept_handler.hpp
  libcaf_net/caf/internal/flow_bridge_base.hpp
  libcaf_net/caf/internal/ws_flow_bridge.cpp
  libcaf_net/caf/net/dsl/has_accept.hpp
  libcaf_net/caf/net/dsl/server_config.hpp
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/lp/framing.cpp
  libcaf_net/caf/net/lp/framing.hpp
  libcaf_net/caf/net/multiplexer.test.cpp
  libcaf_net/caf/net/octet_stream/transport.cpp
  libcaf_net/caf/net/socket.hpp
  libcaf_net/caf/net/socket_manager.hpp
  libcaf_net/caf/net/ssl/connection.cpp
  libcaf_net/caf/net/ssl/connection.hpp
  libcaf_net/caf/net/ssl/context.hpp
  libcaf_net/caf/net/ssl/transport.cpp
  libcaf_net/caf/net/web_socket/acceptor.hpp
  libcaf_net/caf/net/web_socket/has_on_request.hpp
  libcaf_net/caf/net/web_socket/server.cpp
  libcaf_net/caf/net/web_socket/switch_protocol.hpp
  libcaf_net/caf/net/web_socket/upper_layer.cpp
  libcaf_net/caf/net/web_socket/upper_layer.hpp
  libcaf_test/caf/test/dsl.hpp
Labels: refactoring, bugfix

#1895 Polish the readme file to better introduce CAF
  README.md
Labels: documentation

#1893 Remove outdated distros, update existing versions
  .ci/centos-7/Dockerfile
  .ci/debian-12/Dockerfile
  .ci/fedora-40/Dockerfile
  .ci/ubuntu-24.04/Dockerfile
  Jenkinsfile
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_lifetime.test.cpp
Labels: testing, pipeline

#1897 Fix heap use after free in blocking actor
  libcaf_core/caf/blocking_actor.cpp
Labels: bugfix

#1898 Polish examples
  Jenkinsfile
  examples/curl/curl_fuse.cpp
  examples/custom_type/custom_types_2.cpp
  examples/custom_type/custom_types_3.cpp
  examples/custom_type/custom_types_4.cpp
  examples/dynamic_behavior/dining_philosophers.cpp
  examples/flow/observe-on.cpp
  examples/hello_world.cpp
  examples/http/client.cpp
  examples/length_prefix_framing/chat-client.cpp
  examples/length_prefix_framing/chat-server.cpp
  examples/message_passing/calculator.cpp
  examples/message_passing/fan_out_request.cpp
  examples/message_passing/request.cpp
  examples/octet_stream/key-value-store.cpp
  examples/println.cpp
  examples/web_socket/stock-ticker.cpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/string_algorithms.cpp
  libcaf_core/caf/string_algorithms.hpp
  robot/http/client.robot
Labels: refactoring, documentation
