Repository actor-framework/actor-framework, pull requests merged in 2024-02, with the labels that each got.

#1742 Refactor the scheduler interface
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/abstract_actor.cpp
  libcaf_core/caf/actor_ostream.cpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/policy/scheduler_policy.hpp
  libcaf_core/caf/policy/unprofiled.cpp
  libcaf_core/caf/policy/unprofiled.hpp
  libcaf_core/caf/policy/work_sharing.cpp
  libcaf_core/caf/policy/work_sharing.hpp
  libcaf_core/caf/policy/work_stealing.cpp
  libcaf_core/caf/policy/work_stealing.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduler.cpp
  libcaf_core/caf/scheduler.hpp
  libcaf_core/caf/scheduler/abstract_coordinator.cpp
  libcaf_core/caf/scheduler/abstract_coordinator.hpp
  libcaf_core/caf/scheduler/coordinator.hpp
  libcaf_core/caf/scheduler/profiled_coordinator.hpp
  libcaf_core/caf/scheduler/worker.hpp
  libcaf_core/caf/scoped_execution_unit.cpp
  libcaf_core/tests/legacy/thread_hook.cpp
  libcaf_io/caf/io/abstract_broker.cpp
  libcaf_io/caf/io/basp/worker.cpp
  libcaf_io/caf/io/basp/worker.hpp
  libcaf_io/caf/io/network/default_multiplexer.cpp
  libcaf_test/caf/test/dsl.hpp
  libcaf_test/caf/test/fixture/deterministic.cpp
Labels: refactoring

#1739 Re-implement actor_from_state using stateful_actor
  libcaf_core/caf/actor_factory.hpp
  libcaf_core/caf/actor_from_state.hpp
  libcaf_core/caf/actor_from_state.test.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/infer_handle.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_io/caf/io/broker.hpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_io/caf/io/typed_broker.hpp
Labels: refactoring

#1724 Allow actors to send messages during cleanup
  CHANGELOG.md
  libcaf_core/caf/abstract_actor.cpp
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/actor_control_block.cpp
  libcaf_core/caf/actor_from_state.test.cpp
  libcaf_core/caf/actor_pool.cpp
  libcaf_core/caf/actor_pool.hpp
  libcaf_core/caf/actor_storage.hpp
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/forwarding_actor_proxy.cpp
  libcaf_core/caf/forwarding_actor_proxy.hpp
  libcaf_core/caf/local_actor.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/tests/legacy/actor_profiler.cpp
  libcaf_io/caf/io/abstract_broker.cpp
  libcaf_io/caf/io/abstract_broker.hpp
  libcaf_net/caf/net/abstract_actor_shell.cpp
  libcaf_net/caf/net/abstract_actor_shell.hpp
  libcaf_test/caf/test/dsl.hpp
Labels: new feature

#1744 Consolidate serializer tests
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/serialization.test.cpp
  libcaf_core/tests/legacy/binary_deserializer.cpp
  libcaf_core/tests/legacy/binary_serializer.cpp
  libcaf_core/tests/legacy/config_option_set.cpp
  libcaf_core/tests/legacy/config_value.cpp
  libcaf_core/tests/legacy/config_value_reader.cpp
  libcaf_core/tests/legacy/config_value_writer.cpp
  libcaf_core/tests/legacy/core-test.cpp
  libcaf_core/tests/legacy/core-test.hpp
  libcaf_core/tests/legacy/inspector-tests.hpp
  libcaf_core/tests/legacy/load_inspector.cpp
  libcaf_core/tests/legacy/nasty.cpp
  libcaf_core/tests/legacy/nasty.hpp
  libcaf_core/tests/legacy/save_inspector.cpp
  libcaf_core/tests/legacy/serialization.cpp
Labels: testing

#1748 Implement new mail DSL for anonymous messages
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_cast.hpp
  libcaf_core/caf/actor_clock.cpp
  libcaf_core/caf/actor_clock.hpp
  libcaf_core/caf/anon_mail.hpp
  libcaf_core/caf/anon_mail.test.cpp
  libcaf_core/caf/message.hpp
  libcaf_core/caf/message_id.hpp
  libcaf_core/caf/ref.hpp
  libcaf_test/caf/test/fixture/deterministic.hpp
Labels: new feature

#1751 Auto-move values from messages whenever possible
  libcaf_core/caf/behavior.test.cpp
  libcaf_core/caf/const_typed_message_view.hpp
  libcaf_core/caf/cow_string.hpp
  libcaf_core/caf/detail/apply_args.hpp
  libcaf_core/caf/detail/behavior_impl.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/message.hpp
  libcaf_core/caf/typed_message_view.hpp
Labels: new feature

#1754 Deprecate others utility
  libcaf_core/caf/blocking_actor.test.cpp
  libcaf_core/caf/others.hpp
  libcaf_io/caf/io/middleman.cpp
Labels: refactoring

#1753 Implement new event_based_mail DSL
  Jenkinsfile
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/actor_companion.hpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/async_mail.hpp
  libcaf_core/caf/async_mail.test.cpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/event_based_actor.hpp
  libcaf_core/caf/event_based_mail.hpp
  libcaf_core/caf/event_based_mail.test.cpp
  libcaf_core/caf/event_based_response_handle.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/sec.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/caf/typed_event_based_actor.hpp
  libcaf_test/caf/test/fixture/deterministic.cpp
Labels: new feature

#1757 Lift type_list from detail to general namespace
  libcaf_core/caf/actor_factory.hpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/behavior.hpp
  libcaf_core/caf/config_value.hpp
  libcaf_core/caf/const_typed_message_view.hpp
  libcaf_core/caf/detail/functor_attachable.hpp
  libcaf_core/caf/detail/int_list.hpp
  libcaf_core/caf/detail/mtl_util.hpp
  libcaf_core/caf/detail/send_type_check.hpp
  libcaf_core/caf/detail/type_list.hpp
  libcaf_core/caf/event_based_response_handle.hpp
  libcaf_core/caf/exec_main.hpp
  libcaf_core/caf/flow/op/from_generator.hpp
  libcaf_core/caf/flow/op/from_steps.hpp
  libcaf_core/caf/inspector_access.hpp
  libcaf_core/caf/interface_mismatch.hpp
  libcaf_core/caf/policy/select_all.hpp
  libcaf_core/caf/policy/select_all.test.cpp
  libcaf_core/caf/policy/select_any.hpp
  libcaf_core/caf/policy/select_any.test.cpp
  libcaf_core/caf/policy/single_response.hpp
  libcaf_core/caf/response_handle.hpp
  libcaf_core/caf/response_promise.hpp
  libcaf_core/caf/response_type.hpp
  libcaf_core/caf/result.hpp
  libcaf_core/caf/type_list.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/caf/typed_actor_pointer.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/caf/typed_behavior.hpp
  libcaf_core/caf/typed_event_based_actor.hpp
  libcaf_core/caf/typed_message_view.hpp
  libcaf_core/caf/typed_response_promise.hpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_io/caf/io/typed_broker.hpp
  libcaf_net/caf/net/http/route.hpp
  libcaf_net/caf/net/http/router.hpp
  libcaf_net/caf/net/middleman.cpp
  libcaf_net/caf/net/middleman.hpp
  libcaf_net/caf/net/typed_actor_shell.hpp
  libcaf_net/caf/net/web_socket/switch_protocol.hpp
  libcaf_openssl/caf/openssl/manager.cpp
  libcaf_openssl/caf/openssl/manager.hpp
  libcaf_openssl/caf/openssl/remote_actor.hpp
  libcaf_test/caf/test/caf_test_main.hpp
  scripts/demystify.py
Labels: refactoring

#1758 Fix request timeout handling for the new mail API
  libcaf_core/caf/event_based_mail.hpp
  libcaf_core/caf/event_based_mail.test.cpp
  libcaf_core/caf/event_based_response_handle.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
Labels: bugfix

#1764 Remove obsolete experimental features
  CHANGELOG.md
  CMakeLists.txt
  configure
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_profiler.cpp
  libcaf_core/caf/actor_profiler.hpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/defaults.hpp
  libcaf_core/caf/detail/profiled_send.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/local_actor.cpp
  libcaf_core/caf/mailbox_element.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/tracing_data.cpp
  libcaf_core/caf/tracing_data.hpp
  libcaf_core/caf/tracing_data_factory.cpp
  libcaf_core/caf/tracing_data_factory.hpp
  libcaf_core/tests/legacy/actor_profiler.cpp
  libcaf_core/tests/legacy/tracing_data.cpp
  libcaf_net/caf/net/abstract_actor_shell.cpp
Labels: refactoring

#1738 Remove macro based logging from libcaf_core
  libcaf_core/caf/abstract_actor.cpp
  libcaf_core/caf/actor_control_block.cpp
  libcaf_core/caf/actor_registry.cpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/event_based_actor.cpp
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observer.hpp
  libcaf_core/caf/flow/op/from_resource.hpp
  libcaf_core/caf/response_promise.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/typed_event_based_actor.hpp
  robot/logging/base.cfg
Labels: refactoring

#1741 Refactor macro based logs for io
  libcaf_io/caf/detail/prometheus_broker.cpp
  libcaf_io/caf/detail/socket_guard.cpp
  libcaf_io/caf/io/abstract_broker.cpp
  libcaf_io/caf/io/basp/instance.cpp
  libcaf_io/caf/io/basp/remote_message_handler.hpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/broker.cpp
  libcaf_io/caf/io/connection_helper.cpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman_actor_impl.cpp
  libcaf_io/caf/io/network/datagram_handler.cpp
  libcaf_io/caf/io/network/default_multiplexer.cpp
  libcaf_io/caf/io/network/default_multiplexer.hpp
  libcaf_io/caf/io/network/event_handler.cpp
  libcaf_io/caf/io/network/manager.cpp
  libcaf_io/caf/io/network/operation.hpp
  libcaf_io/caf/io/typed_broker.hpp
  libcaf_io/caf/policy/tcp.cpp
  libcaf_io/caf/policy/udp.cpp
Labels: refactoring

#1749 Refactor macro based logging
  libcaf_net/caf/detail/accept_handler.hpp
  libcaf_net/caf/net/abstract_actor_shell.cpp
  libcaf_net/caf/net/http/async_client.cpp
  libcaf_net/caf/net/http/client.cpp
  libcaf_net/caf/net/http/request_header.cpp
  libcaf_net/caf/net/http/response_header.cpp
  libcaf_net/caf/net/http/server.cpp
  libcaf_net/caf/net/ip.cpp
  libcaf_net/caf/net/lp/framing.cpp
  libcaf_net/caf/net/middleman.cpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_net/caf/net/octet_stream/transport.cpp
  libcaf_net/caf/net/socket.cpp
  libcaf_net/caf/net/socket_manager.cpp
  libcaf_net/caf/net/tcp_accept_socket.cpp
  libcaf_net/caf/net/tcp_stream_socket.cpp
  libcaf_net/caf/net/udp_datagram_socket.cpp
  libcaf_net/caf/net/web_socket/client.cpp
  libcaf_net/caf/net/web_socket/framing.cpp
  libcaf_net/caf/net/web_socket/server.cpp
  libcaf_net/tests/drivers/autobahn.cpp
  libcaf_openssl/caf/openssl/middleman_actor.cpp
  libcaf_openssl/caf/openssl/session.cpp
  libcaf_test/caf/test/dsl.hpp
Labels: refactoring

#1762 High-level caf-net primitive for custom binary protocols
  libcaf_core/caf/async/publisher.hpp
  libcaf_core/caf/defaults.hpp
  libcaf_core/caf/detail/flow_source.hpp
  libcaf_core/caf/flow/op/ucast.hpp
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/dsl/client_factory_base.hpp
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_net/caf/net/multiplexer.hpp
  libcaf_net/caf/net/octet_stream/client_factory.hpp
  libcaf_net/caf/net/octet_stream/flow_bridge.cpp
  libcaf_net/caf/net/octet_stream/flow_bridge.hpp
  libcaf_net/caf/net/octet_stream/flow_bridge.test.cpp
  libcaf_net/caf/net/octet_stream/transport.cpp
  libcaf_net/caf/net/octet_stream/upper_layer.cpp
  libcaf_net/caf/net/octet_stream/upper_layer.hpp
  libcaf_net/caf/net/octet_stream/with.hpp
  libcaf_net/caf/net/octet_stream/with.test.cpp
  libcaf_net/caf/net/socket_manager.cpp
  libcaf_net/caf/net/socket_manager.hpp
Labels: new feature

#1763 Add blocking member functions to futures
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/async/execution_context.hpp
  libcaf_core/caf/async/future.hpp
  libcaf_core/caf/async/promise.hpp
  libcaf_core/caf/async/promise.test.cpp
  libcaf_core/caf/detail/async_cell.hpp
  libcaf_core/caf/detail/beacon.cpp
  libcaf_core/caf/detail/beacon.hpp
  libcaf_core/caf/sec.hpp
Labels: new feature

#1765 Implement as_observable for event_based_mail
  libcaf_core/caf/event_based_mail.hpp
  libcaf_core/caf/event_based_mail.test.cpp
  libcaf_core/caf/event_based_response_handle.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/scheduled_actor/flow.hpp
Labels: new feature

#1767 Remove the OpenSSL special members from the config
  CHANGELOG.md
  libcaf_core/caf/actor_system_config.hpp
  libcaf_openssl/caf/openssl/manager.cpp
  libcaf_openssl/caf/openssl/session.cpp
Labels: refactoring

#1766 Use the new mail syntax for asynchronous messages
  examples/aout.cpp
  examples/curl/curl_fuse.cpp
  examples/custom_type/custom_types_1.cpp
  examples/custom_type/custom_types_2.cpp
  examples/custom_type/custom_types_3.cpp
  examples/dynamic_behavior/dining_philosophers.cpp
  examples/dynamic_behavior/skip_messages.cpp
  examples/message_passing/after.cpp
  examples/message_passing/dancing_kirby.cpp
  examples/remoting/distributed_calculator.cpp
  examples/remoting/remote_spawn.cpp
  examples/testing/ping_pong.cpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_from_state.test.cpp
  libcaf_core/caf/actor_pool.cpp
  libcaf_core/caf/actor_pool.test.cpp
  libcaf_core/caf/actor_registry.test.cpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/anon_mail.hpp
  libcaf_core/caf/async/blocking_producer.test.cpp
  libcaf_core/caf/async/producer_adapter.test.cpp
  libcaf_core/caf/async_mail.hpp
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/blocking_actor.test.cpp
  libcaf_core/caf/blocking_mail.hpp
  libcaf_core/caf/delegate.test.cpp
  libcaf_core/caf/detached_actors.test.cpp
  libcaf_core/caf/detail/mtl_util.hpp
  libcaf_core/caf/event_based_actor.test.cpp
  libcaf_core/caf/event_based_mail.hpp
  libcaf_core/caf/forwarding_actor_proxy.cpp
  libcaf_core/caf/message_lifetime.test.cpp
  libcaf_core/caf/messaging.test.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/simple_timeout.test.cpp
  libcaf_core/caf/stream.test.cpp
  libcaf_core/tests/legacy/actor_lifetime.cpp
  libcaf_core/tests/legacy/constructor_attach.cpp
  libcaf_core/tests/legacy/custom_exception_handler.cpp
  libcaf_core/tests/legacy/dsl.cpp
  libcaf_core/tests/legacy/dynamic_spawn.cpp
  libcaf_core/tests/legacy/mixin/requester.cpp
  libcaf_core/tests/legacy/request_timeout.cpp
  libcaf_core/tests/legacy/response_promise.cpp
  libcaf_core/tests/legacy/typed_spawn.cpp
  libcaf_core/tests/legacy/typed_stream.cpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/broker.hpp
  libcaf_io/caf/io/connection_helper.cpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman_actor_impl.cpp
  libcaf_net/tests/legacy/net/actor_shell.cpp
  libcaf_net/tests/legacy/net/typed_actor_shell.cpp
  libcaf_test/caf/test/dsl.hpp
  libcaf_test/caf/test/fixture/deterministic.test.cpp
  robot/middleman/driver.cpp
  tools/caf-run.cpp
Labels: refactoring

#1768 Remove caf-run from the repository
  CHANGELOG.md
  CMakeLists.txt
  configure
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/exec_main.hpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman.hpp
  tools/CMakeLists.txt
  tools/caf-run.cpp
Labels: refactoring

#1774 Fix spawn option handling for actor_from_state
  CHANGELOG.md
  libcaf_core/caf/actor_from_state.hpp
  libcaf_core/caf/actor_from_state.test.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/local_actor.hpp
Labels: bugfix

#1773 Simplify function chaining on delayed requests
  libcaf_core/caf/blocking_mail.hpp
  libcaf_core/caf/blocking_mail.test.cpp
  libcaf_core/caf/blocking_response_handle.hpp
  libcaf_core/caf/event_based_mail.hpp
  libcaf_core/caf/event_based_mail.test.cpp
  libcaf_core/caf/event_based_response_handle.hpp
Labels: new feature

#1761 Implement trait based type interfaces for actors
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_cast.hpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/detail/to_statically_typed_trait.hpp
  libcaf_core/caf/detail/typed_actor_util.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/statically_typed.hpp
  libcaf_core/caf/type_id_list.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/caf/typed_actor.test.cpp
  libcaf_core/caf/typed_actor_pointer.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/caf/typed_behavior.hpp
  libcaf_core/caf/typed_event_based_actor.hpp
  libcaf_core/caf/typed_event_based_actor.test.cpp
  libcaf_core/tests/legacy/typed_spawn.cpp
Labels: new feature

#1756 Implement unit tests for scheduler implementations
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/scheduler.test.cpp
Labels: testing

#1775 Switch to the new mail(...).request(...) syntax
  examples/dynamic_behavior/skip_messages.cpp
  examples/hello_world.cpp
  examples/message_passing/calculator.cpp
  examples/message_passing/delegating.cpp
  examples/message_passing/divider.cpp
  examples/message_passing/promises.cpp
  examples/message_passing/request.cpp
  examples/remoting/distributed_calculator.cpp
  libcaf_core/caf/actor_pool.test.cpp
  libcaf_core/caf/async_mail.test.cpp
  libcaf_core/caf/blocking_response_handle.hpp
  libcaf_core/caf/detail/mtl_util.hpp
  libcaf_core/caf/event_based_actor.test.cpp
  libcaf_core/caf/event_based_mail.test.cpp
  libcaf_core/caf/event_based_response_handle.hpp
  libcaf_core/caf/flow/concat_map.test.cpp
  libcaf_core/caf/flow/flat_map.test.cpp
  libcaf_core/caf/flow/mixed.test.cpp
  libcaf_core/caf/function_view.hpp
  libcaf_core/caf/or_else.test.cpp
  libcaf_core/caf/serial_reply.test.cpp
  libcaf_core/caf/typed_event_based_actor.hpp
  libcaf_core/caf/unit.test.cpp
  libcaf_core/tests/legacy/actor_termination.cpp
  libcaf_core/tests/legacy/custom_exception_handler.cpp
  libcaf_core/tests/legacy/typed_spawn.cpp
  libcaf_io/caf/io/middleman_actor_impl.cpp
  robot/middleman/driver.cpp
  robot/stream/driver.cpp
Labels: refactoring
