Repository actor-framework/actor-framework, pull requests merged in 2024-04, with the labels that each got.

#1836 Update typos config
  .typos-config.toml
  Doxyfile
  libcaf_core/caf/flow/op/sample.hpp
Labels: pipeline

#1834 Migrate caf_core tests to new framework
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_termination.test.cpp
  libcaf_core/caf/constructor_attach.test.cpp
  libcaf_core/caf/dynamic_spawn.test.cpp
  libcaf_core/caf/request_timeout.test.cpp
  libcaf_core/caf/typed_actor_view.test.cpp
  libcaf_core/caf/typed_spawn.test.cpp
  libcaf_core/caf/typed_stream.test.cpp
  libcaf_core/tests/legacy/actor_termination.cpp
Labels: testing

#1837 Remove logger factory from the config class
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/actor_system_config.hpp
Labels: refactoring

#1838 Add version header and ABI version token
  CMakeLists.txt
  cmake/build_config.hpp.in
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/config.hpp
  libcaf_core/caf/version.cpp
  libcaf_core/caf/version.hpp
  libcaf_core/caf/version.test.cpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_net/caf/net/middleman.cpp
  libcaf_net/caf/net/middleman.hpp
  libcaf_openssl/caf/openssl/manager.cpp
  libcaf_openssl/caf/openssl/manager.hpp
Labels: refactoring, build harness

#1841 Fix sphinx build for the manual
  manual/conf.py
Labels: documentation

#1843 Update the manual for CAF 1.0 changes
  examples/message_passing/dancing_kirby.cpp
  examples/message_passing/promises.cpp
  libcaf_core/caf/config_value.test.cpp
  libcaf_core/caf/detail/private_thread_pool.test.cpp
  libcaf_core/caf/function_view.test.cpp
  libcaf_test/README.md
  manual/Introduction.rst
  manual/ManagingGroupsOfWorkers.rst
  manual/MessagePassing.rst
  manual/Testing.rst
  manual/conf.py
  manual/index.rst
Labels: documentation

#1842 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#1845 Switch to clang-format 18
  .github/workflows/check-formatting.yml
  examples/remoting/distributed_calculator.cpp
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/actor_ostream.cpp
  libcaf_core/caf/blocking_mail.test.cpp
  libcaf_core/caf/cow_vector.hpp
  libcaf_core/caf/detail/apply_args.hpp
  libcaf_core/caf/detail/init_fun_factory.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/expected.hpp
  libcaf_core/caf/function_view.test.cpp
  libcaf_core/caf/log/event.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/serialization.test.cpp
  libcaf_core/caf/settings.hpp
  libcaf_test/caf/test/unit_test.hpp
  robot/stream/driver.cpp
Labels: refactoring, pipeline

#1844 Deprecate the class-based spawn and actor pools
  CHANGELOG.md
  examples/flow/observe-on.cpp
  examples/http/rest.cpp
  examples/web_socket/stock-ticker.cpp
  libcaf_core/caf/actor_companion.test.cpp
  libcaf_core/caf/actor_from_state.test.cpp
  libcaf_core/caf/actor_pool.cpp
  libcaf_core/caf/actor_pool.hpp
  libcaf_core/caf/actor_pool.test.cpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system.test.cpp
  libcaf_core/caf/async_mail.test.cpp
  libcaf_core/caf/constructor_attach.test.cpp
  libcaf_core/caf/detail/actor_system_access.cpp
  libcaf_core/caf/detail/actor_system_access.hpp
  libcaf_core/caf/dynamic_spawn.test.cpp
  libcaf_core/caf/event_based_mail.test.cpp
  libcaf_core/caf/flow/concat_map.test.cpp
  libcaf_core/caf/flow/flat_map.test.cpp
  libcaf_core/caf/flow/observe_on.test.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/message_lifetime.test.cpp
  libcaf_core/caf/mixin/actor_widget.hpp
  libcaf_core/caf/mtl.test.cpp
  libcaf_core/caf/response_handle.test.cpp
  libcaf_core/caf/run_delayed.test.cpp
  libcaf_core/caf/stateful_actor.test.cpp
  libcaf_core/caf/telemetry/metric_registry.test.cpp
  libcaf_core/caf/typed_actor_view.test.cpp
  libcaf_core/caf/typed_event_based_actor.test.cpp
  libcaf_core/caf/typed_spawn.test.cpp
  libcaf_core/tests/legacy/actor_lifetime.cpp
  libcaf_core/tests/legacy/custom_exception_handler.cpp
  libcaf_io/caf/io/middleman_actor.cpp
  libcaf_net/caf/net/make_actor_shell.hpp
  libcaf_openssl/caf/openssl/middleman_actor.cpp
  manual/Actors.rst
  manual/RemoteSpawn.rst
  robot/flow/merge-driver.cpp
Labels: refactoring, documentation

#1839 Migrate actor lifetime test to new framework
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_lifetime.test.cpp
  libcaf_core/caf/scheduled_actor.test.cpp
  libcaf_core/tests/legacy/core-test.cpp
  libcaf_core/tests/legacy/core-test.hpp
  libcaf_core/tests/legacy/custom_exception_handler.cpp
Labels: testing

#1846 Add tests to improve coverage
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/action.test.cpp
  libcaf_core/caf/behavior.test.cpp
  libcaf_core/caf/config_option.test.cpp
  libcaf_core/caf/config_option_set.test.cpp
  libcaf_core/caf/exit_reason.test.cpp
  libcaf_core/caf/inspector_access_type.hpp
  libcaf_core/caf/inspector_access_type.test.cpp
  libcaf_core/caf/ipv6_subnet.test.cpp
  libcaf_core/caf/message_handler.test.cpp
  libcaf_core/caf/none.test.cpp
  libcaf_core/caf/pec.test.cpp
  libcaf_core/caf/serializer.test.cpp
  libcaf_core/caf/stream.test.cpp
Labels: testing

#1835 Enable remote spawn for stateful actors
  examples/CMakeLists.txt
  examples/remoting/stateful_remote_spawn.cpp
  libcaf_core/caf/actor_factory.hpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/type_list.hpp
Labels: new feature
