Repository actor-framework/actor-framework, pull requests merged in 2024-07, with the labels that each got.

#1906 Fix typos pipeline step
  .typos-config.toml
  libcaf_core/caf/scheduler.test.cpp
  robot/middleman/driver.cpp
  robot/middleman/middleman.robot
Labels: diagnostic

#1905 Disable caf-robot-stream-octet test
  robot/CMakeLists.txt
Labels: pipeline

#1903 Fix errors when using std::format
  CHANGELOG.md
  CMakeLists.txt
  Jenkinsfile
  libcaf_core/caf/chunked_string.hpp
  libcaf_core/caf/detail/format.hpp
  libcaf_core/caf/detail/format.test.cpp
  libcaf_test/caf/test/reporter.cpp
Labels: bugfix

#1912 Document the flow multicaster
  examples/CMakeLists.txt
  examples/flow/multicaster.cpp
  manual/DataFlows.rst
Labels: documentation

#1915 Fix python version in FreeBSD CI
  .ci/freebsd-13/prepare.sh
Labels: pipeline

#1913 Fix an example in the testing manual section
  manual/Testing.rst
Labels: documentation

#1914 Fix cleanup in the consumer adapter if pull fails
  CHANGELOG.md
  libcaf_core/caf/async/consumer_adapter.hpp
Labels: bugfix

#1917 Adjust severity for disposing connection acceptors
  CHANGELOG.md
  libcaf_net/caf/internal/accept_handler.cpp
Labels: improvement

#1921 Fix crash in run_actions when calling quit
  CHANGELOG.md
  libcaf_core/caf/action.hpp
  libcaf_core/caf/event_based_actor.test.cpp
  libcaf_core/caf/scheduled_actor.cpp
Labels: bugfix

#1924 Fix unused parameter warning
  libcaf_io/caf/io/basp/instance.cpp
Labels: diagnostic

#1911 Add new module for background workers
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system_module.cpp
  libcaf_core/caf/actor_system_module.hpp
  libcaf_core/caf/detail/actor_system_access.hpp
  libcaf_core/caf/detail/daemons.cpp
  libcaf_core/caf/detail/daemons.hpp
  libcaf_net/caf/net/http/client_factory.hpp
Labels: new feature

#1927 Bump version and fix documentation for doxygen
  Doxyfile
  libcaf_core/caf/all.hpp
Labels: bugfix, documentation

#1930 Minor API additions for use cases at Interance
  libcaf_core/caf/intrusive/linked_list.hpp
  libcaf_core/caf/intrusive/linked_list.test.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/sec.hpp
Labels: new feature

#1931 Generate Doxyfile from CMake
  CMakeLists.txt
  cmake/Doxyfile.in
Labels: documentation

#1932 Rename shutdown to abort_and_shutdown in http::router
  CHANGELOG.md
  libcaf_net/caf/net/http/router.cpp
  libcaf_net/caf/net/http/router.hpp
  libcaf_net/caf/net/http/server_factory.cpp
Labels: improvement

#1934 Update and restructure the manual sources
  manual/core/Actors.rst
  manual/core/ConfiguringActorApplications.rst
  manual/core/CopyOnWriteTypes.rst
  manual/core/DataFlows.rst
  manual/core/Error.rst
  manual/core/Hashing.rst
  manual/core/MessageHandlers.rst
  manual/core/MessagePassing.rst
  manual/core/Metrics.rst
  manual/core/ReferenceCounting.rst
  manual/core/Registry.rst
  manual/core/Scheduler.rst
  manual/core/TypeInspection.rst
  manual/core/TypedMessageView.rst
  manual/core/actor_types.png
  manual/core/enable_shared_from_this.png
  manual/core/flow.svg
  manual/core/mailbox_element.png
  manual/core/make_shared.png
  manual/core/op/buffer.svg
  manual/core/op/concat.svg
  manual/core/op/concat_map.svg
  manual/core/op/distinct.svg
  manual/core/op/element_at.svg
  manual/core/op/filter.svg
  manual/core/op/first.svg
  manual/core/op/flat_map.svg
  manual/core/op/head_and_tail.svg
  manual/core/op/ignore_elements.svg
  manual/core/op/last.svg
  manual/core/op/map.svg
  manual/core/op/merge.svg
  manual/core/op/observe_on.svg
  manual/core/op/prefix_and_tail.svg
  manual/core/op/reduce.svg
  manual/core/op/ref_count.svg
  manual/core/op/sample.svg
  manual/core/op/skip.svg
  manual/core/op/skip_last.svg
  manual/core/op/start_with.svg
  manual/core/op/sum.svg
  manual/core/op/take.svg
  manual/core/op/take_last.svg
  manual/core/op/take_while.svg
  manual/core/op/to_vector.svg
  manual/core/refcounting.png
  manual/core/shared_ptr.png
  manual/core/stealing.png
  manual/index.rst
  manual/intro/Concepts.rst
  manual/intro/Overview.rst
  manual/io/Brokers.rst
  manual/io/NetworkTransparency.rst
  manual/io/RemoteSpawn.rst
  manual/net/WebSocket.rst
  manual/test/UnitTesting.rst
Labels: documentation
