Repository actor-framework/actor-framework, pull requests merged in 2024-03, with the labels that each got.

#1779 Fix warnings on Clang
  libcaf_core/caf/config_value.test.cpp
  libcaf_core/caf/json_builder.test.cpp
  libcaf_core/caf/json_writer.test.cpp
  libcaf_core/caf/stateful_actor.test.cpp
Labels: diagnostic

#1784 Bump FreeBSD from 13-2 to 13-3
  .cirrus.yml
Labels: pipeline

#1780 Streamline our new response handle types
  libcaf_core/caf/abstract_blocking_actor.hpp
  libcaf_core/caf/blocking_mail.hpp
  libcaf_core/caf/blocking_mail.test.cpp
  libcaf_core/caf/blocking_response_handle.hpp
  libcaf_core/caf/detail/response_type_check.hpp
  libcaf_core/caf/event_based_mail.hpp
  libcaf_core/caf/event_based_mail.test.cpp
  libcaf_core/caf/event_based_response_handle.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/scheduled_actor.hpp
Labels: new feature

#1785 Add trait based signatures for typed actor shell
  libcaf_net/caf/net/typed_actor_shell.hpp
  libcaf_net/tests/legacy/net/typed_actor_shell.cpp
Labels: new feature

#1783 Update examples with trait based type signatures
  examples/dynamic_behavior/dining_philosophers.cpp
  examples/message_passing/calculator.cpp
  examples/message_passing/delegating.cpp
  examples/message_passing/divider.cpp
  examples/message_passing/fan_out_request.cpp
  examples/message_passing/promises.cpp
  examples/message_passing/request.cpp
  examples/remoting/remote_spawn.cpp
Labels: refactoring

#1781 Implement new monitoring member function
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/monitor_action.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/monitor.test.cpp
Labels: new feature

#1787 Bump checkout and codecov GitHub actions
  .github/workflows/check-typos.yml
  .github/workflows/check-windows.yml
  .github/workflows/codecov.yml
Labels: pipeline

#1788 Remove obsolete test for the legacy testing DSL
  libcaf_core/CMakeLists.txt
  libcaf_core/tests/legacy/dsl.cpp
Labels: testing

#1786 Modernize caf-net tests
  Jenkinsfile
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/detail/convert_ip_endpoint.test.cpp
  libcaf_net/caf/net/http/client.test.cpp
  libcaf_net/caf/net/http/router.test.cpp
  libcaf_net/caf/net/http/server.test.cpp
  libcaf_net/caf/net/lp/frame.test.cpp
  libcaf_net/caf/net/lp/framing.test.cpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_net/caf/net/multiplexer.hpp
  libcaf_net/caf/net/octet_stream/transport.test.cpp
  libcaf_net/caf/net/web_socket/frame.test.cpp
  libcaf_net/caf/net/web_socket/handshake.test.cpp
  libcaf_net/tests/legacy/net-test.cpp
  libcaf_net/tests/legacy/net-test.hpp
  libcaf_net/tests/legacy/net/http/router.cpp
  libcaf_net/tests/legacy/net/http/server.cpp
  libcaf_net/tests/legacy/net/length_prefix_framing.cpp
  libcaf_net/tests/legacy/net/lp/frame.cpp
  libcaf_net/tests/legacy/net/web_socket/client.cpp
  libcaf_net/tests/legacy/net/web_socket/framing.cpp
  libcaf_net/tests/legacy/net/web_socket/server.cpp
Labels: testing

#1792 Stabilize unit tests
  libcaf_core/caf/flow/generation.test.cpp
Labels: testing

#1793 Give actor shells access to the flow API
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/abstract_scheduled_actor.cpp
  libcaf_core/caf/abstract_scheduled_actor.hpp
  libcaf_core/caf/actor_cast.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/event_based_mail.hpp
  libcaf_core/caf/event_based_response_handle.hpp
  libcaf_core/caf/flow/op/cell.hpp
  libcaf_core/caf/policy/single_response.hpp
  libcaf_core/caf/response_handle.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/abstract_actor_shell.cpp
  libcaf_net/caf/net/abstract_actor_shell.hpp
  libcaf_net/caf/net/actor_shell.cpp
  libcaf_net/caf/net/actor_shell.hpp
  libcaf_net/caf/net/actor_shell.test.cpp
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/generic_lower_layer.cpp
  libcaf_net/caf/net/generic_lower_layer.hpp
  libcaf_net/caf/net/http/client.cpp
  libcaf_net/caf/net/http/client.hpp
  libcaf_net/caf/net/http/router.cpp
  libcaf_net/caf/net/http/server.cpp
  libcaf_net/caf/net/http/server.hpp
  libcaf_net/caf/net/lp/framing.cpp
  libcaf_net/caf/net/lp/framing.hpp
  libcaf_net/caf/net/make_actor_shell.hpp
  libcaf_net/caf/net/octet_stream/transport.cpp
  libcaf_net/caf/net/octet_stream/transport.hpp
  libcaf_net/caf/net/socket_manager.hpp
  libcaf_net/caf/net/typed_actor_shell.hpp
  libcaf_net/caf/net/typed_actor_shell.test.cpp
  libcaf_net/caf/net/web_socket/framing.cpp
  libcaf_net/caf/net/web_socket/framing.hpp
  libcaf_net/tests/legacy/net/actor_shell.cpp
  libcaf_net/tests/legacy/net/typed_actor_shell.cpp
Labels: new feature

#1802 Implement new mail cache type for manual stashing
  examples/dynamic_behavior/dining_philosophers.cpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/mail_cache.cpp
  libcaf_core/caf/mail_cache.hpp
  libcaf_core/caf/mail_cache.test.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_net/caf/net/abstract_actor_shell.cpp
  libcaf_net/caf/net/abstract_actor_shell.hpp
Labels: new feature

#1791 Port remaining caf_net tests to new framework
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/accept_socket.test.cpp
  libcaf_net/caf/net/datagram_socket.test.cpp
  libcaf_net/caf/net/ip.test.cpp
  libcaf_net/caf/net/multiplexer.test.cpp
  libcaf_net/caf/net/network_socket.test.cpp
  libcaf_net/caf/net/pipe_socket.test.cpp
  libcaf_net/caf/net/socket.test.cpp
  libcaf_net/caf/net/socket_guard.test.cpp
  libcaf_net/caf/net/stream_socket.test.cpp
  libcaf_net/caf/net/udp_datagram_socket.test.cpp
  libcaf_net/tests/legacy/net/network_socket.cpp
  libcaf_net/tests/legacy/net/stream_socket.cpp
Labels: testing

#1803 Fix parsing of <arg> syntax in scenarios
  libcaf_test/CMakeLists.txt
  libcaf_test/caf/test/block.cpp
  libcaf_test/caf/test/block_type.hpp
  libcaf_test/caf/test/block_type.test.cpp
  libcaf_test/caf/test/fwd.hpp
  libcaf_test/caf/test/outline.cpp
  libcaf_test/caf/test/outline.hpp
  libcaf_test/caf/test/runnable.cpp
  libcaf_test/caf/test/runnable.hpp
  libcaf_test/caf/test/runnable_with_examples.cpp
  libcaf_test/caf/test/runnable_with_examples.hpp
  libcaf_test/caf/test/scenario.test.cpp
Labels: testing

#1804 Streamline the scheduler interface
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/abstract_actor.cpp
  libcaf_core/caf/actor_ostream.cpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/blocking_mail.test.cpp
  libcaf_core/caf/detail/actor_system_access.cpp
  libcaf_core/caf/detail/actor_system_access.hpp
  libcaf_core/caf/detail/cleanup_and_release.cpp
  libcaf_core/caf/detail/cleanup_and_release.hpp
  libcaf_core/caf/detail/default_thread_count.cpp
  libcaf_core/caf/detail/default_thread_count.hpp
  libcaf_core/caf/detail/private_thread_pool.test.cpp
  libcaf_core/caf/detail/thread_safe_actor_clock.cpp
  libcaf_core/caf/detail/thread_safe_actor_clock.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduler.cpp
  libcaf_core/caf/scheduler.hpp
  libcaf_core/caf/scheduler.test.cpp
  libcaf_core/caf/scoped_execution_unit.cpp
  libcaf_core/caf/thread_hook.test.cpp
  libcaf_io/caf/io/basp/worker.cpp
  libcaf_io/caf/io/network/default_multiplexer.cpp
  libcaf_test/caf/test/dsl.hpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
Labels: refactoring

#1805 Scheduler unification step 1
  libcaf_core/caf/action.cpp
  libcaf_core/caf/action.hpp
  libcaf_core/caf/actor_clock.cpp
  libcaf_core/caf/actor_control_block.cpp
  libcaf_core/caf/actor_control_block.hpp
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/detail/abstract_worker.cpp
  libcaf_core/caf/detail/abstract_worker.hpp
  libcaf_core/caf/detail/abstract_worker_hub.cpp
  libcaf_core/caf/detail/beacon.cpp
  libcaf_core/caf/detail/beacon.hpp
  libcaf_core/caf/detail/monitor_action.hpp
  libcaf_core/caf/detail/private_thread_pool.test.cpp
  libcaf_core/caf/execution_unit.cpp
  libcaf_core/caf/execution_unit.hpp
  libcaf_core/caf/proxy_registry.cpp
  libcaf_core/caf/proxy_registry.hpp
  libcaf_core/caf/resumable.cpp
  libcaf_core/caf/resumable.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/scheduler.cpp
  libcaf_core/caf/scheduler.test.cpp
  libcaf_io/caf/io/abstract_broker.cpp
  libcaf_io/caf/io/abstract_broker.hpp
  libcaf_io/caf/io/basp/instance.hpp
  libcaf_io/caf/io/basp/worker.cpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/broker_servant.hpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_io/caf/io/network/multiplexer.cpp
  libcaf_io/caf/io/network/multiplexer.hpp
Labels: refactoring

#1806 Implement new `set_idle_handler`
  examples/CMakeLists.txt
  examples/message_passing/idle_timeout_once.cpp
  examples/message_passing/idle_timeout_repeat.cpp
  libcaf_core/caf/event_based_actor.test.cpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/once.hpp
  libcaf_core/caf/repeat.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/system_messages.hpp
  libcaf_core/caf/system_messages.test.cpp
  libcaf_core/caf/type_id.hpp
Labels: new feature

#1807 Add new println abstraction on the actor system
  examples/CMakeLists.txt
  examples/curl/curl_fuse.cpp
  examples/custom_type/custom_types_1.cpp
  examples/custom_type/custom_types_2.cpp
  examples/custom_type/custom_types_3.cpp
  examples/custom_type/custom_types_4.cpp
  examples/dynamic_behavior/dining_philosophers.cpp
  examples/dynamic_behavior/skip_messages.cpp
  examples/hello_world.cpp
  examples/message_passing/calculator.cpp
  examples/message_passing/delegating.cpp
  examples/message_passing/divider.cpp
  examples/message_passing/idle_timeout_once.cpp
  examples/message_passing/promises.cpp
  examples/message_passing/request.cpp
  examples/println.cpp
  examples/remoting/distributed_calculator.cpp
  examples/remoting/remote_spawn.cpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system.test.cpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/scheduled_actor.cpp
  manual/Actors.rst
Labels: new feature

#1810 Fix typed_actor_view
  libcaf_core/caf/typed_actor_view.hpp
Labels: bugfix

#1811 Fix two bugs with the new monitoring API
  libcaf_core/caf/detail/monitor_action.hpp
  libcaf_core/caf/event_based_actor.test.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/monitor.test.cpp
Labels: bugfix

#1813 Make the state member in stateful actors private
  CHANGELOG.md
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/function_view.test.cpp
  libcaf_core/caf/stateful_actor.hpp
  libcaf_core/caf/stateful_actor.test.cpp
  libcaf_core/tests/legacy/request_timeout.cpp
Labels: refactoring

#1823 Fix data races in the scheduler unit tests
  libcaf_core/caf/scheduler.test.cpp
Labels: testing

#1822 Hide most actor_system_config fields
  examples/config/read-json.cpp
  examples/http/client.cpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_factory.test.cpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/actor_system_config.test.cpp
  libcaf_core/caf/detail/actor_system_config_access.cpp
  libcaf_core/caf/detail/actor_system_config_access.hpp
  libcaf_core/caf/exec_main.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_net/caf/net/middleman.cpp
  libcaf_net/caf/net/middleman.hpp
  libcaf_openssl/caf/openssl/manager.cpp
  libcaf_openssl/caf/openssl/manager.hpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
Labels: refactoring

#1820 Add new format_to_error utility function
  examples/http/rest.cpp
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/config_value.cpp
  libcaf_core/caf/config_value_reader.cpp
  libcaf_core/caf/deserializer.cpp
  libcaf_core/caf/detail/parse.test.cpp
  libcaf_core/caf/detail/parser/read_number.test.cpp
  libcaf_core/caf/detail/parser/read_string.test.cpp
  libcaf_core/caf/detail/pretty_type_name.cpp
  libcaf_core/caf/error.cpp
  libcaf_core/caf/error.hpp
  libcaf_core/caf/format_to_error.hpp
  libcaf_core/caf/ipv4_address.cpp
  libcaf_core/caf/ipv6_address.cpp
  libcaf_core/caf/json_builder.cpp
  libcaf_core/caf/json_reader.cpp
  libcaf_core/caf/json_reader.hpp
  libcaf_core/caf/json_value.cpp
  libcaf_core/caf/json_writer.cpp
  libcaf_core/caf/parser_state.cpp
  libcaf_core/caf/parser_state.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/uri.cpp
  libcaf_core/tests/legacy/custom_exception_handler.cpp
  libcaf_io/caf/detail/call_cfun.hpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/network/default_multiplexer.cpp
  libcaf_io/caf/io/network/native_socket.cpp
  libcaf_net/caf/detail/net_syscall.hpp
  libcaf_net/caf/net/dsl/config_base.hpp
  libcaf_net/caf/net/network_socket.cpp
  libcaf_net/caf/net/pipe_socket.cpp
  libcaf_net/caf/net/ssl/tcp_acceptor.cpp
  libcaf_net/caf/net/tcp_accept_socket.cpp
Labels: new feature

#1824 Implementation hiding of `caf::net` protocol specific classes
  examples/length_prefix_framing/chat-client.cpp
  examples/length_prefix_framing/chat-server.cpp
  examples/web_socket/stock-ticker.cpp
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/http/async_client.cpp
  libcaf_net/caf/net/http/async_client.hpp
  libcaf_net/caf/net/http/client.cpp
  libcaf_net/caf/net/http/client.hpp
  libcaf_net/caf/net/http/client.test.cpp
  libcaf_net/caf/net/http/client_factory.cpp
  libcaf_net/caf/net/http/server.cpp
  libcaf_net/caf/net/http/server.hpp
  libcaf_net/caf/net/http/server.test.cpp
  libcaf_net/caf/net/lp/client_factory.hpp
  libcaf_net/caf/net/lp/framing.cpp
  libcaf_net/caf/net/lp/framing.hpp
  libcaf_net/caf/net/lp/framing.test.cpp
  libcaf_net/caf/net/lp/with.hpp
  libcaf_net/caf/net/web_socket/client.cpp
  libcaf_net/caf/net/web_socket/client.hpp
  libcaf_net/caf/net/web_socket/framing.cpp
  libcaf_net/caf/net/web_socket/framing.hpp
  libcaf_net/caf/net/web_socket/server.cpp
  libcaf_net/caf/net/web_socket/server.hpp
  libcaf_net/caf/net/web_socket/switch_protocol.hpp
Labels: refactoring

#1821 Add support for splitting and utf-8 conversions
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/chunk.cpp
  libcaf_core/caf/chunk.hpp
  libcaf_core/caf/flow/byte.hpp
  libcaf_core/caf/flow/byte.test.cpp
  libcaf_core/caf/sec.hpp
Labels: new feature

#1826 Re-implement actor_system using the PIMPL idiom
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/abstract_actor.cpp
  libcaf_core/caf/actor_control_block.cpp
  libcaf_core/caf/actor_ostream.cpp
  libcaf_core/caf/actor_pool.test.cpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/actor_system_module.cpp
  libcaf_core/caf/actor_system_module.hpp
  libcaf_core/caf/detail/actor_system_access.cpp
  libcaf_core/caf/detail/actor_system_access.hpp
  libcaf_core/caf/detail/split_join.hpp
  libcaf_core/caf/exec_main.hpp
  libcaf_core/caf/function_view.test.cpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/local_actor.cpp
  libcaf_core/caf/typed_event_based_actor.test.cpp
  libcaf_core/tests/legacy/typed_spawn.cpp
  libcaf_io/caf/io/basp/remote_message_handler.hpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_net/caf/net/middleman.cpp
  libcaf_net/caf/net/middleman.hpp
  libcaf_openssl/caf/openssl/manager.cpp
  libcaf_openssl/caf/openssl/manager.hpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  robot/middleman/driver.cpp
Labels: refactoring

#1825 Fix mailbox creation when spawning child actors
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/typed_event_based_actor.test.cpp
Labels: bugfix, testing

#1827 Hide the implementation of net::socket_manager
  libcaf_net/caf/net/http/with.hpp
  libcaf_net/caf/net/lp/with.hpp
  libcaf_net/caf/net/socket_manager.cpp
  libcaf_net/caf/net/socket_manager.hpp
  libcaf_net/caf/net/web_socket/with.hpp
Labels: refactoring

#1831 Implement on-backpressure-buffer operator
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/flow/backpressure_overflow_strategy.hpp
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/op/on_backpressure_buffer.hpp
  libcaf_core/caf/flow/op/on_backpressure_buffer.test.cpp
  libcaf_core/caf/flow/scoped_coordinator.cpp
  libcaf_core/caf/flow/scoped_coordinator.hpp
  libcaf_core/caf/sec.hpp
  libcaf_test/caf/test/fixture/flow.cpp
  libcaf_test/caf/test/fixture/flow.hpp
Labels: new feature

#1830 Simplify the socket_manager virtual interface
  libcaf_net/caf/net/make_actor_shell.hpp
  libcaf_net/caf/net/socket_manager.cpp
  libcaf_net/caf/net/socket_manager.hpp
Labels: refactoring

#1828 Hide the implementation of the transport layer
  libcaf_net/caf/net/octet_stream/transport.cpp
  libcaf_net/caf/net/octet_stream/transport.hpp
  libcaf_net/caf/net/ssl/transport.cpp
  libcaf_net/caf/net/ssl/transport.hpp
Labels: refactoring
