Repository actor-framework/actor-framework, pull requests merged in 2024-01, with the labels that each got.

#1707 CI: drop FreeBSD 12 (EOL), switch to FreeBSD 14
  .ci/freebsd-14/prepare.sh
  .cirrus.yml
Labels: pipeline

#1708 CI: drop fedora-37, switch to fedora-39
  .ci/fedora-39/Dockerfile
  Jenkinsfile
Labels: pipeline

#1706 Add utils for spawning actors from state classes
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_from_state.hpp
  libcaf_core/caf/actor_from_state.test.cpp
  libcaf_core/caf/behavior.hpp
  libcaf_core/caf/detail/init_fun_factory.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/infer_handle.hpp
  libcaf_core/caf/typed_behavior.hpp
Labels: new feature

#1705 Update legacy tests to new framework - Part 2
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/result.test.cpp
  libcaf_core/caf/run_delayed.test.cpp
  libcaf_core/caf/run_scheduled.test.cpp
  libcaf_core/caf/scheduled_actor.test.cpp
  libcaf_core/caf/serial_reply.test.cpp
  libcaf_core/caf/settings.test.cpp
  libcaf_core/caf/simple_timeout.test.cpp
  libcaf_core/caf/span.test.cpp
  libcaf_core/tests/legacy/span.cpp
Labels: testing

#1709 Update best practices on spawning actors
  examples/CMakeLists.txt
  examples/curl/curl_fuse.cpp
  examples/custom_type/custom_types_1.cpp
  examples/custom_type/custom_types_2.cpp
  examples/custom_type/custom_types_3.cpp
  examples/dynamic_behavior/dining_philosophers.cpp
  examples/dynamic_behavior/skip_messages.cpp
  examples/hello_world.cpp
  examples/message_passing/after.cpp
  examples/message_passing/calculator.cpp
  examples/message_passing/cell.cpp
  examples/message_passing/dancing_kirby.cpp
  examples/message_passing/delegating.cpp
  examples/message_passing/divider.cpp
  examples/message_passing/fan_out_request.cpp
  examples/message_passing/fixed_stack.cpp
  examples/message_passing/promises.cpp
  examples/message_passing/request.cpp
  examples/message_passing/typed_calculator.cpp
  examples/remoting/distributed_calculator.cpp
  examples/remoting/pingpong.proto
  examples/remoting/remote_spawn.cpp
  examples/testing/ping_pong.cpp
  libcaf_core/caf/actor_from_state.hpp
  libcaf_core/caf/all.hpp
  manual/Actors.rst
Labels: documentation

#1710 Add new actor_ostream::println utility function
  CHANGELOG.md
  examples/aout.cpp
  examples/custom_type/custom_types_1.cpp
  examples/custom_type/custom_types_2.cpp
  examples/custom_type/custom_types_3.cpp
  examples/custom_type/custom_types_4.cpp
  examples/dynamic_behavior/dining_philosophers.cpp
  examples/dynamic_behavior/skip_messages.cpp
  examples/flow/iota.cpp
  examples/flow/spsc-buffer-resource.cpp
  examples/hello_world.cpp
  examples/message_passing/after.cpp
  examples/message_passing/calculator.cpp
  examples/message_passing/delegating.cpp
  examples/message_passing/divider.cpp
  examples/message_passing/promises.cpp
  examples/message_passing/request.cpp
  examples/remoting/distributed_calculator.cpp
  examples/remoting/remote_spawn.cpp
  libcaf_core/caf/actor_ostream.hpp
  libcaf_core/caf/detail/format.hpp
  libcaf_core/caf/scheduled_actor.cpp
  manual/Actors.rst
Labels: new feature, documentation

#1712 Fix behavior of caf::net::make_pipe on Windows
  CHANGELOG.md
  libcaf_net/caf/net/pipe_socket.cpp
Labels: bugfix

#1713 Remove deprecated functions and classes
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor.cpp
  libcaf_core/caf/actor.hpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/byte.hpp
  libcaf_core/caf/composed_type.hpp
  libcaf_core/caf/config_option_adder.cpp
  libcaf_core/caf/decorator/sequencer.cpp
  libcaf_core/caf/decorator/sequencer.hpp
  libcaf_core/caf/expected.hpp
  libcaf_core/caf/flow/item_publisher.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/inspector_access.hpp
  libcaf_core/caf/make_message.hpp
  libcaf_core/caf/optional.hpp
  libcaf_core/caf/replies_to.cpp
  libcaf_core/caf/replies_to.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/scheduled_actor/flow.hpp
  libcaf_core/caf/sec_strings.cpp
  libcaf_core/caf/string_view.cpp
  libcaf_core/caf/string_view.hpp
  libcaf_core/caf/string_view.test.cpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/caf/typed_response_promise.hpp
  libcaf_core/tests/legacy/actor_system_config.cpp
  libcaf_core/tests/legacy/config_value.cpp
  libcaf_core/tests/legacy/config_value_writer.cpp
  libcaf_core/tests/legacy/metaprogramming.cpp
  libcaf_core/tests/legacy/mtl.cpp
  libcaf_core/tests/legacy/optional.cpp
  libcaf_core/tests/legacy/typed_actor_view.cpp
  libcaf_core/tests/legacy/typed_stream.cpp
  libcaf_io/caf/io/network/native_socket.cpp
  libcaf_net/caf/detail/rfc6455.test.cpp
  libcaf_net/caf/net/http/request_header.cpp
  libcaf_net/caf/net/http/response_header.cpp
  libcaf_net/caf/net/http/server.cpp
  libcaf_net/caf/net/http/status.hpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_net/caf/net/pipe_socket.cpp
  libcaf_net/caf/net/stream_socket.cpp
  libcaf_net/caf/net/udp_datagram_socket.cpp
  libcaf_net/caf/net/web_socket/framing.hpp
  libcaf_net/tests/legacy/net-test.hpp
  libcaf_net/tests/legacy/net/actor_shell.cpp
  libcaf_net/tests/legacy/net/datagram_transport.cpp
  libcaf_net/tests/legacy/net/length_prefix_framing.cpp
  libcaf_net/tests/legacy/net/multiplexer.cpp
  libcaf_net/tests/legacy/net/octet_stream/transport.cpp
  libcaf_net/tests/legacy/net/pipe_socket.cpp
  libcaf_net/tests/legacy/net/stream_socket.cpp
  libcaf_net/tests/legacy/net/string_application.cpp
  libcaf_net/tests/legacy/net/typed_actor_shell.cpp
Labels: refactoring

#1714 Remove the obsolete group API
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/abstract_group.cpp
  libcaf_core/caf/abstract_group.hpp
  libcaf_core/caf/actor_clock.cpp
  libcaf_core/caf/actor_clock.hpp
  libcaf_core/caf/actor_companion.hpp
  libcaf_core/caf/actor_config.cpp
  libcaf_core/caf/actor_config.hpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.hpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/detail/group_tunnel.cpp
  libcaf_core/caf/detail/group_tunnel.hpp
  libcaf_core/caf/detail/local_group_module.cpp
  libcaf_core/caf/detail/local_group_module.hpp
  libcaf_core/caf/detail/profiled_send.hpp
  libcaf_core/caf/event_based_actor.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/group.cpp
  libcaf_core/caf/group.hpp
  libcaf_core/caf/group_manager.cpp
  libcaf_core/caf/group_manager.hpp
  libcaf_core/caf/group_module.cpp
  libcaf_core/caf/group_module.hpp
  libcaf_core/caf/init_global_meta_objects.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/mixin/subscriber.hpp
  libcaf_core/caf/scheduler/abstract_coordinator.cpp
  libcaf_core/caf/send.hpp
  libcaf_core/caf/system_messages.hpp
  libcaf_core/caf/system_messages.test.cpp
  libcaf_core/caf/type_id.hpp
  libcaf_core/tests/legacy/detail/group_tunnel.cpp
  libcaf_core/tests/legacy/detail/local_group_module.cpp
  libcaf_core/tests/legacy/mixin/sender.cpp
  libcaf_io/CMakeLists.txt
  libcaf_io/caf/detail/remote_group_module.cpp
  libcaf_io/caf/detail/remote_group_module.hpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_io/caf/io/middleman_actor.hpp
  libcaf_io/caf/io/middleman_actor_impl.cpp
  libcaf_io/caf/io/remote_group.hpp
  tools/CMakeLists.txt
  tools/caf-vec.cpp
Labels: refactoring

#1718 Remove the obsolete path from mailbox elements
  libcaf_core/caf/abstract_actor.cpp
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/actor_companion.cpp
  libcaf_core/caf/actor_ostream.cpp
  libcaf_core/caf/blocking_actor.cpp
  libcaf_core/caf/detail/default_mailbox.test.cpp
  libcaf_core/caf/detail/profiled_send.hpp
  libcaf_core/caf/forwarding_actor_proxy.cpp
  libcaf_core/caf/forwarding_actor_proxy.hpp
  libcaf_core/caf/local_actor.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/mailbox_element.cpp
  libcaf_core/caf/mailbox_element.hpp
  libcaf_core/caf/mixin/requester.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/monitorable_actor.cpp
  libcaf_core/caf/no_stages.hpp
  libcaf_core/caf/response_promise.cpp
  libcaf_core/caf/response_promise.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/scheduler/abstract_coordinator.cpp
  libcaf_core/caf/send.hpp
  libcaf_core/caf/typed_response_promise.hpp
  libcaf_core/tests/legacy/mailbox_element.cpp
  libcaf_io/caf/io/abstract_broker.cpp
  libcaf_io/caf/io/basp/instance.cpp
  libcaf_io/caf/io/basp/instance.hpp
  libcaf_io/caf/io/basp/message_queue.test.cpp
  libcaf_io/caf/io/basp/remote_message_handler.hpp
  libcaf_io/caf/io/basp/version.hpp
  libcaf_io/caf/io/basp_broker.cpp
  libcaf_io/caf/io/broker_servant.hpp
  libcaf_io/caf/io/datagram_servant.cpp
  libcaf_io/caf/io/network/manager.cpp
  libcaf_io/caf/io/scribe.cpp
Labels: refactoring

#1711 Remove legacy tests and update for new test framework
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/message_lifetime.test.cpp
  libcaf_core/caf/messaging.test.cpp
  libcaf_core/caf/metaprogramming.test.cpp
  libcaf_core/caf/mtl.test.cpp
  libcaf_core/caf/node_id.test.cpp
  libcaf_core/caf/or_else.test.cpp
  libcaf_core/caf/response_handle.test.cpp
  libcaf_core/tests/legacy/core-test.hpp
  libcaf_core/tests/legacy/message_lifetime.cpp
Labels: testing

#1720 Set timeouts for Robot tests
  robot/CMakeLists.txt
  robot/flow/merge-driver.cpp
  robot/flow/merge.robot
  robot/web-socket/echo.robot
  robot/web-socket/quote-server.robot
Labels: testing, pipeline

#1719 Move linked_list from json to detail
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/chunked_string.cpp
  libcaf_core/caf/chunked_string.hpp
  libcaf_core/caf/chunked_string.test.cpp
  libcaf_core/caf/detail/json.hpp
  libcaf_core/caf/detail/mbr_list.hpp
  libcaf_core/caf/detail/mbr_list.test.cpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/intrusive/lifo_inbox.hpp
  libcaf_core/caf/intrusive/linked_list.hpp
  libcaf_core/caf/log/event.hpp
Labels: refactoring

#1717 Remove legacy tests and update for new test framework (Part 4)
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/ipv4_address.test.cpp
  libcaf_core/caf/ipv4_endpoint.test.cpp
  libcaf_core/caf/ipv4_subnet.test.cpp
  libcaf_core/caf/ipv6_address.test.cpp
  libcaf_core/caf/ipv6_endpoint.test.cpp
  libcaf_core/caf/ipv6_subnet.test.cpp
  libcaf_core/caf/mailbox_element.test.cpp
  libcaf_core/caf/message_id.test.cpp
  libcaf_core/caf/policy/select_all.test.cpp
  libcaf_core/caf/policy/select_any.test.cpp
  libcaf_core/tests/legacy/ipv4_address.cpp
  libcaf_core/tests/legacy/ipv4_subnet.cpp
  libcaf_core/tests/legacy/ipv6_address.cpp
  libcaf_core/tests/legacy/message_id.cpp
Labels: testing

#1723 Remove the class monitorable_actor
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/abstract_actor.cpp
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/actor.hpp
  libcaf_core/caf/actor_pool.cpp
  libcaf_core/caf/actor_pool.hpp
  libcaf_core/caf/actor_proxy.cpp
  libcaf_core/caf/actor_proxy.hpp
  libcaf_core/caf/forwarding_actor_proxy.cpp
  libcaf_core/caf/forwarding_actor_proxy.hpp
  libcaf_core/caf/local_actor.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/monitorable_actor.cpp
  libcaf_core/caf/monitorable_actor.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_test/caf/test/dsl.hpp
  manual/Actors.rst
Labels: refactoring

#1704 Add lp robot tests
  .cirrus.yml
  .github/workflows/check-windows.yml
  robot/CMakeLists.txt
  robot/lp/communication.robot
Labels: testing

#1726 Remove the behavior_changer mixin
  libcaf_core/caf/actor_companion.hpp
  libcaf_core/caf/all.hpp
  libcaf_core/caf/event_based_actor.hpp
  libcaf_core/caf/keep_behavior.hpp
  libcaf_core/caf/mixin/behavior_changer.hpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/typed_event_based_actor.hpp
  libcaf_io/caf/io/broker.hpp
  libcaf_io/caf/io/typed_broker.hpp
Labels: refactoring

#1721 Fix DLL builds with MSVC
  .ci/windows/build.cmd
  .ci/windows/test.cmd
  CHANGELOG.md
  CMakeLists.txt
  libcaf_core/caf/chunk.hpp
  libcaf_core/caf/detail/private_thread_pool.hpp
  libcaf_core/caf/function_view.hpp
  libcaf_core/caf/type_id.hpp
  libcaf_io/caf/io/network/ip_endpoint.hpp
Labels: bugfix

#1732 Add missing unit tests to the CMake file
  libcaf_core/CMakeLists.txt
Labels: testing

#1730 Remove obsolete files
  libcaf_core/caf/async/blocking_for_each.test.cpp
  libcaf_core/caf/detail/tick_emitter.test.cpp
  libcaf_core/tests/legacy/policy/categorized.cpp
  libcaf_net/caf/net/middleman_backend.cpp
  libcaf_net/caf/net/packet_writer.cpp
  libcaf_net/tests/legacy/net/datagram_transport.cpp
  libcaf_net/tests/legacy/net/prometheus/server.cpp
  libcaf_net/tests/legacy/net/string_application.cpp
  libcaf_net/tests/legacy/net/web_socket/flow.cpp
Labels: refactoring

#1729 Use more concise C++17 namespace syntax
  libcaf_core/caf/detail/padded_size.hpp
Labels: refactoring

#1727 Simplify and streamline existing send functions
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/actor_companion.cpp
  libcaf_core/caf/actor_companion.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/check_typed_input.hpp
  libcaf_core/caf/detail/init_fun_factory.hpp
  libcaf_core/caf/detail/send_type_check.hpp
  libcaf_core/caf/detail/stream_bridge.cpp
  libcaf_core/caf/event_based_actor.hpp
  libcaf_core/caf/local_actor.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/message.hpp
  libcaf_core/caf/mixin/requester.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/response_promise.hpp
  libcaf_core/caf/response_type.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/send.cpp
  libcaf_core/caf/send.hpp
  libcaf_core/caf/typed_actor_view.hpp
  libcaf_core/caf/typed_event_based_actor.hpp
  libcaf_io/caf/io/broker.cpp
  libcaf_io/caf/io/broker.hpp
  libcaf_net/caf/net/actor_shell.hpp
  libcaf_test/caf/test/dsl.hpp
  libcaf_test/caf/test/fixture/deterministic.cpp
  libcaf_test/caf/test/fixture/deterministic.hpp
Labels: refactoring

#1735 Fix build on MSVC
  libcaf_core/caf/mixin/requester.hpp
Labels: bugfix

#1734 Remove obsolete utility classes
  libcaf_core/caf/actor_companion.hpp
  libcaf_core/caf/detail/type_list.hpp
  libcaf_core/caf/event_based_actor.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/type_id_list.hpp
  libcaf_core/caf/typed_event_based_actor.hpp
  libcaf_io/caf/io/broker.hpp
  libcaf_io/caf/io/typed_broker.hpp
Labels: refactoring

#1736 Modernize metaprogramming utilities
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/detail/type_list.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/detail/typed_actor_util.hpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/metaprogramming.test.cpp
  libcaf_core/caf/typed_behavior.hpp
  libcaf_io/caf/io/middleman.hpp
  libcaf_io/caf/io/typed_broker.hpp
Labels: refactoring

#1733 Allow setting name when using `actor_from_state`
  libcaf_core/caf/actor_from_state.hpp
Labels: improvement
