Repository actor-framework/actor-framework, pull requests merged in 2025-03, with the labels that each got.

#2016 Add combine_latest flow operator
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/detail/combine_latest.hpp
  libcaf_core/caf/flow/combine_latest.test.cpp
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_builder.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/sec.hpp
Labels: new feature

#2021 Add startup check for socket manager in HTTP client factory
  libcaf_net/caf/net/actor_shell.test.cpp
  libcaf_net/caf/net/http/async_client.test.cpp
  libcaf_net/caf/net/http/client.test.cpp
  libcaf_net/caf/net/http/client_factory.cpp
  libcaf_net/caf/net/http/server.test.cpp
  libcaf_net/caf/net/http/server_factory.cpp
  libcaf_net/caf/net/lp/client_factory.cpp
  libcaf_net/caf/net/lp/framing.cpp
  libcaf_net/caf/net/lp/framing.test.cpp
  libcaf_net/caf/net/lp/server_factory.cpp
  libcaf_net/caf/net/multiplexer.cpp
  libcaf_net/caf/net/multiplexer.hpp
  libcaf_net/caf/net/octet_stream/client_factory.cpp
  libcaf_net/caf/net/octet_stream/server_factory.cpp
  libcaf_net/caf/net/typed_actor_shell.test.cpp
  libcaf_net/caf/net/web_socket/with.cpp
  libcaf_net/tests/drivers/autobahn.cpp
Labels: bugfix

#2029 Consistently use byte span aliases
  examples/http/rest.cpp
  libcaf_core/caf/binary_deserializer.cpp
  libcaf_core/caf/binary_deserializer.hpp
  libcaf_core/caf/binary_serializer.cpp
  libcaf_core/caf/binary_serializer.hpp
  libcaf_core/caf/byte_reader.hpp
  libcaf_core/caf/byte_span.cpp
  libcaf_core/caf/byte_span.hpp
  libcaf_core/caf/byte_writer.hpp
  libcaf_core/caf/config_value_reader.cpp
  libcaf_core/caf/config_value_reader.hpp
  libcaf_core/caf/config_value_writer.cpp
  libcaf_core/caf/config_value_writer.hpp
  libcaf_core/caf/deserializer.hpp
  libcaf_core/caf/detail/stringification_inspector.cpp
  libcaf_core/caf/detail/stringification_inspector.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/hash/fnv.hpp
  libcaf_core/caf/hash/sha1.hpp
  libcaf_core/caf/json_builder.cpp
  libcaf_core/caf/json_builder.hpp
  libcaf_core/caf/json_builder.test.cpp
  libcaf_core/caf/json_reader.cpp
  libcaf_core/caf/json_reader.hpp
  libcaf_core/caf/json_writer.cpp
  libcaf_core/caf/json_writer.hpp
  libcaf_core/caf/serializer.hpp
  libcaf_core/caf/serializer.test.cpp
  libcaf_core/caf/span.hpp
  libcaf_io/caf/io/abstract_broker.cpp
  libcaf_io/caf/io/abstract_broker.hpp
  libcaf_io/caf/io/basp/instance.cpp
Labels: refactoring

#2033 List available modules in the manual
  manual/core/ConfiguringActorApplications.rst
Labels: documentation
