Repository actor-framework/actor-framework, pull requests merged in 2025-05, with the labels that each got.

#2069 Add missing separator for nested array
  libcaf_core/caf/json_writer.cpp
  libcaf_core/caf/json_writer.test.cpp
Labels: bugfix

#2052 Add timeout for await_running_count_equal
  libcaf_core/caf/actor_registry.hpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/typed_event_based_actor.test.cpp
Labels: new feature

#2067 Make the interface part of the handle
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/actor_control_block.cpp
  libcaf_core/caf/actor_control_block.hpp
  libcaf_core/caf/actor_storage.hpp
  libcaf_core/caf/fwd.hpp
  libcaf_core/caf/logger.hpp
  libcaf_core/caf/make_actor.hpp
  libcaf_core/caf/meta/handler.cpp
  libcaf_core/caf/meta/handler.hpp
  libcaf_core/caf/meta/handler.test.cpp
  libcaf_core/caf/scoped_actor.hpp
  libcaf_core/caf/typed_actor.hpp
  libcaf_io/caf/io/abstract_broker.hpp
Labels: new feature

#2066 Allow inheriting from JSON reader/writer
  libcaf_core/caf/json_reader.cpp
  libcaf_core/caf/json_reader.hpp
  libcaf_core/caf/json_reader.test.cpp
  libcaf_core/caf/json_writer.cpp
  libcaf_core/caf/json_writer.hpp
  libcaf_core/caf/json_writer.test.cpp
Labels: refactoring

#2075 Fix `ssl_ctx_chain_if`
  CHANGELOG.md
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/ssl/context.hpp
  libcaf_net/caf/net/ssl/context.test.cpp
  libcaf_net/caf/net/ssl/dtls.hpp
  libcaf_net/caf/net/ssl/errc.hpp
  libcaf_net/caf/net/ssl/format.hpp
  libcaf_net/caf/net/ssl/password.hpp
  libcaf_net/caf/net/ssl/startup.hpp
  libcaf_net/caf/net/ssl/tls.hpp
  libcaf_net/caf/net/ssl/verify.hpp
  libcaf_test/caf/test/runnable.hpp
Labels: bugfix

#2081 Fix in-place parsing of percent encoded URIs
  CHANGELOG.md
  libcaf_core/caf/uri.cpp
  libcaf_core/caf/uri.test.cpp
Labels: bugfix

#2082 Follow RFC 3986 recommendation on query strings
  CHANGELOG.md
  libcaf_core/caf/detail/parser/read_config.test.cpp
  libcaf_core/caf/detail/parser/read_uri.hpp
  libcaf_core/caf/uri.test.cpp
Labels: improvement

#2078 Fix is_constructible assertions for typed actors
  libcaf_core/caf/typed_actor.hpp
  libcaf_core/caf/typed_actor.test.cpp
  libcaf_core/caf/typed_actor_pointer.hpp
Labels: refactoring
