Repository actor-framework/actor-framework, pull requests merged in 2025-01, with the labels that each got.

#1984 Suppress typo checks in byte.test.cpp
  libcaf_core/caf/flow/byte.test.cpp
Labels: diagnostic

#1982 Fix warning in observe-on
  examples/flow/observe-on.cpp
Labels: diagnostic

#1980 Add tests for config_value and remove obsolete code
  libcaf_core/caf/config_value.cpp
  libcaf_core/caf/config_value.test.cpp
Labels: testing

#1986 Implement a mechanism for merging type lists
  libcaf_core/caf/type_list.hpp
  libcaf_core/caf/typed_actor.test.cpp
Labels: new feature

#1979 Add tests for bool vector and fix implementation
  libcaf_core/caf/serialization.test.cpp
Labels: testing

#1989 Fix conversion of invalid handles via `actor_cast`
  CHANGELOG.md
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_cast.hpp
  libcaf_core/caf/actor_cast.test.cpp
  libcaf_core/caf/actor_ostream.cpp
  libcaf_core/caf/actor_pool.cpp
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/attachable.cpp
  libcaf_core/caf/default_attachable.cpp
  libcaf_core/caf/detail/sync_request_bouncer.cpp
  libcaf_core/caf/proxy_registry.cpp
  libcaf_core/caf/proxy_registry.hpp
  libcaf_core/caf/scoped_actor.cpp
  libcaf_core/caf/scoped_actor.hpp
  libcaf_io/caf/io/broker.hpp
  libcaf_io/caf/io/middleman.cpp
  libcaf_io/caf/io/typed_broker.hpp
  libcaf_net/caf/net/actor_shell.cpp
  libcaf_net/caf/net/typed_actor_shell.hpp
  libcaf_openssl/caf/openssl/unpublish.hpp
  libcaf_test/caf/test/runnable.hpp
Labels: bugfix

#1988 Fix GCC warning on ARM
  libcaf_core/caf/detail/print.hpp
Labels: bugfix

#1993 Mark mail types as `[[nodiscard]]`
  libcaf_core/caf/anon_mail.hpp
  libcaf_core/caf/blocking_mail.hpp
  libcaf_core/caf/event_based_mail.hpp
Labels: diagnostic

#1991 Allow setting receive timeouts on sockets
  libcaf_net/caf/net/socket.cpp
  libcaf_net/caf/net/socket.hpp
  libcaf_net/caf/net/stream_socket.cpp
  libcaf_net/caf/net/stream_socket.test.cpp
Labels: new feature

#1996 Remove remnants of caf profiler
  Jenkinsfile
  cmake/build_config.hpp.in
Labels: build harness

#1995 Update pipeline distros
  .ci/fedora-39/Dockerfile
  .ci/fedora-41/Dockerfile
  Jenkinsfile
  libcaf_core/caf/config.hpp
  libcaf_net/caf/net/web_socket/framing.cpp
Labels: diagnostic, pipeline

#1999 Fix run.sh test command for old ctest
  .ci/run.sh
Labels: pipeline
