Repository actor-framework/actor-framework, pull requests merged in 2025-02, with the labels that each got.

#2006 Remove Almalinux 8
  .ci/almalinux-8/Dockerfile
  Jenkinsfile
Labels: pipeline

#2007 Remove mixin::sender
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/actor_companion.hpp
  libcaf_core/caf/blocking_actor.hpp
  libcaf_core/caf/event_based_actor.hpp
  libcaf_core/caf/mixin/sender.hpp
  libcaf_core/caf/mixin/sender.test.cpp
  libcaf_core/caf/typed_event_based_actor.hpp
  libcaf_core/caf/typed_event_based_actor.test.cpp
  libcaf_io/caf/io/broker.hpp
  libcaf_io/caf/io/typed_broker.hpp
  libcaf_net/caf/net/abstract_actor_shell.hpp
  libcaf_net/caf/net/actor_shell.hpp
  libcaf_net/caf/net/typed_actor_shell.hpp
Labels: refactoring

#2010 Turn actor_registry into an interface
  libcaf_core/caf/actor_registry.cpp
  libcaf_core/caf/actor_registry.hpp
  libcaf_core/caf/actor_system.cpp
Labels: refactoring

#2015 Add reuse-address flags to helptext and robot
  libcaf_io/caf/io/middleman.cpp
  libcaf_net/caf/net/middleman.cpp
  robot/middleman/driver.cpp
  robot/middleman/middleman.robot
Labels: testing

#2014 Allow setting max_concurrent for merge operators
  CHANGELOG.md
  libcaf_core/caf/flow/flat_map.test.cpp
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_builder.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/op/merge.hpp
  libcaf_core/caf/flow/op/merge.test.cpp
  manual/core/DataFlows.rst
Labels: new feature

#2022 Update cirrus FreeBSD pipeline
  .ci/freebsd-13/prepare.sh
  .cirrus.yml
Labels: pipeline

#2019 Make it harder to misuse concurrency limits in `merge`
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_builder.hpp
  libcaf_core/caf/flow/op/merge.test.cpp
Labels: refactoring

#2028 Work around internal compiler error in MSVC
  libcaf_core/CMakeLists.txt
Labels: pipeline

#2027 Allow custom HTTP header fields for WebSocket clients
  libcaf_net/caf/net/web_socket/handshake.cpp
  libcaf_net/caf/net/web_socket/handshake.hpp
  libcaf_net/caf/net/web_socket/server.cpp
  libcaf_net/caf/net/web_socket/switch_protocol.cpp
  libcaf_net/caf/net/web_socket/with.cpp
  libcaf_net/caf/net/web_socket/with.hpp
Labels: new feature
