Repository actor-framework/actor-framework, pull requests merged in 2025-06, with the labels that each got.

#2057 Fix -Wconversion warnings
  examples/message_passing/fan_out_request.cpp
  libcaf_core/caf/async/spsc_buffer.hpp
  libcaf_core/caf/chrono.cpp
  libcaf_core/caf/config_option.cpp
  libcaf_core/caf/detail/json.cpp
  libcaf_core/caf/detail/parser/read_floating_point.hpp
  libcaf_core/caf/json_builder.test.cpp
  libcaf_core/caf/telemetry/collector/prometheus.cpp
  libcaf_io/caf/io/network/stream.cpp
  libcaf_net/caf/net/octet_stream/transport.cpp
  libcaf_net/caf/net/receive_policy.hpp
  libcaf_net/caf/net/web_socket/framing.cpp
Labels: diagnostic

#2087 Add missing option for HTTP max response size
  CHANGELOG.md
  libcaf_core/caf/defaults.hpp
  libcaf_net/caf/net/http/client.cpp
  libcaf_net/caf/net/http/client_factory.cpp
  libcaf_net/caf/net/http/client_factory.hpp
Labels: bugfix

#2090 Fix ASAN false positive in json_reader test
  libcaf_core/caf/json_reader.test.cpp
Labels: diagnostic

#2098 Add throttle_last alias for sample
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/op/sample.test.cpp
Labels: new feature

#2097 Add throttle_first flow op
  libcaf_core/CMakeLists.txt
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_decl.hpp
  libcaf_core/caf/flow/op/throttle_first.hpp
  libcaf_core/caf/flow/op/throttle_first.test.cpp
Labels: new feature

#2106 enable wconversion flag in CI
  .ci/debug-flags.cmake
  Jenkinsfile
  libcaf_core/caf/detail/ieee_754.hpp
  libcaf_core/caf/detail/json.cpp
Labels: diagnostic

#2104 Add missing qualifiers in `observable_decl`
  libcaf_core/caf/flow/observable.hpp
Labels: refactoring
