Repository actor-framework/actor-framework, pull requests merged in 2025-04, with the labels that each got.

#2031 Refactor `with` DSL for HTTP
  examples/http/rest.cpp
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/internal/net_config.hpp
  libcaf_net/caf/net/dsl/has_lazy_context.hpp
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/http/client_factory.cpp
  libcaf_net/caf/net/http/client_factory.hpp
  libcaf_net/caf/net/http/server_factory.cpp
  libcaf_net/caf/net/http/server_factory.hpp
  libcaf_net/caf/net/http/with.cpp
  libcaf_net/caf/net/http/with.hpp
Labels: refactoring

#2040 Add label dimension to caf.system.running-actors
  CHANGELOG.md
  libcaf_core/caf/actor_system.cpp
  libcaf_core/caf/actor_system.hpp
  libcaf_core/caf/actor_system_config.cpp
  libcaf_core/caf/local_actor.cpp
  libcaf_core/caf/local_actor.hpp
  libcaf_core/caf/telemetry/metric_registry.test.cpp
  manual/core/Metrics.rst
Labels: new feature

#2035 Refactor with DSL for octet stream
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/octet_stream/client_factory.cpp
  libcaf_net/caf/net/octet_stream/client_factory.hpp
  libcaf_net/caf/net/octet_stream/server_factory.cpp
  libcaf_net/caf/net/octet_stream/server_factory.hpp
  libcaf_net/caf/net/octet_stream/with.cpp
  libcaf_net/caf/net/octet_stream/with.hpp
Labels: refactoring

#2045 Bump clang-format version to 19
  .github/workflows/check-formatting.yml
  libcaf_core/caf/abstract_actor.hpp
  libcaf_core/caf/cow_vector.hpp
  libcaf_core/caf/detail/apply_args.hpp
  libcaf_core/caf/detail/type_traits.hpp
  libcaf_core/caf/expected.hpp
  libcaf_core/caf/log/event.hpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/scheduled_actor.hpp
  libcaf_core/caf/settings.hpp
  libcaf_core/caf/type_id.hpp
  libcaf_net/caf/net/ssl/context.cpp
  libcaf_test/caf/test/bdd_dsl.hpp
Labels: refactoring

#2041 Refactor `with` DSL for length-prefix
  examples/length_prefix_framing/chat-client.cpp
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/fwd.hpp
  libcaf_net/caf/net/lp/client_factory.cpp
  libcaf_net/caf/net/lp/client_factory.hpp
  libcaf_net/caf/net/lp/config.hpp
  libcaf_net/caf/net/lp/server_factory.cpp
  libcaf_net/caf/net/lp/server_factory.hpp
  libcaf_net/caf/net/lp/with.cpp
  libcaf_net/caf/net/lp/with.hpp
Labels: refactoring

#2047 Fix documentation warning
  libcaf_core/caf/flow/observable_decl.hpp
Labels: diagnostic

#2049 Fix parsing of flags on the command line
  CHANGELOG.md
  libcaf_core/caf/config_option_set.cpp
  libcaf_core/caf/config_option_set.test.cpp
Labels: bugfix

#2044 Validate periods for buffer and interval operators
  CHANGELOG.md
  libcaf_core/caf/flow/observable.hpp
  libcaf_core/caf/flow/observable_builder.hpp
  libcaf_core/caf/flow/op/buffer.test.cpp
  libcaf_core/caf/flow/op/cold.hpp
  libcaf_core/caf/flow/op/fail.hpp
  libcaf_core/caf/flow/op/interval.cpp
  libcaf_core/caf/flow/op/interval.test.cpp
  libcaf_core/caf/scheduled_actor.cpp
  libcaf_core/caf/stream.test.cpp
  libcaf_core/caf/typed_stream.test.cpp
Labels: bugfix

#2054 Remove `with` DSL base classes
  CHANGELOG.md
  libcaf_net/CMakeLists.txt
  libcaf_net/caf/net/dsl/base.hpp
  libcaf_net/caf/net/dsl/client_config.cpp
  libcaf_net/caf/net/dsl/client_config.hpp
  libcaf_net/caf/net/dsl/client_factory_base.hpp
  libcaf_net/caf/net/dsl/config_base.cpp
  libcaf_net/caf/net/dsl/config_base.hpp
  libcaf_net/caf/net/dsl/generic_config.hpp
  libcaf_net/caf/net/dsl/get_name.hpp
  libcaf_net/caf/net/dsl/has_accept.hpp
  libcaf_net/caf/net/dsl/has_connect.hpp
  libcaf_net/caf/net/dsl/has_context.hpp
  libcaf_net/caf/net/dsl/has_make_ctx.hpp
  libcaf_net/caf/net/dsl/has_uri_connect.hpp
  libcaf_net/caf/net/dsl/server_config.hpp
  libcaf_net/caf/net/dsl/server_factory_base.hpp
  libcaf_net/caf/net/http/with.cpp
  libcaf_net/caf/net/http/with.hpp
  libcaf_net/caf/net/lp/with.cpp
  libcaf_net/caf/net/lp/with.hpp
  libcaf_net/caf/net/octet_stream/with.cpp
  libcaf_net/caf/net/octet_stream/with.hpp
  libcaf_net/caf/net/web_socket/with.cpp
  libcaf_net/caf/net/web_socket/with.hpp
Labels: refactoring

#2059 Use localtime_s on all windows platforms
  libcaf_core/caf/detail/print.cpp
Labels: bugfix

#2063 Fix build issues on Apple clang
  libcaf_core/caf/config.hpp
  libcaf_core/caf/detail/split_join.hpp
Labels: diagnostic

#2062 Add `mail_cache::stash` overload with no arguments
  CHANGELOG.md
  libcaf_core/caf/mail_cache.cpp
  libcaf_core/caf/mail_cache.hpp
  libcaf_core/caf/mail_cache.test.cpp
Labels: new feature

#2064 Revert "Add `mail_cache::stash` overload with no arguments"
  CHANGELOG.md
  libcaf_core/caf/mail_cache.cpp
  libcaf_core/caf/mail_cache.hpp
  libcaf_core/caf/mail_cache.test.cpp
Labels: improvement

#2065 Fix test flag in CMake
  libcaf_core/CMakeLists.txt
Labels: bugfix
